### ISSUE TITLE
Support prioritization of actions / groups

### ISSUE THREAD

**Issue by rrennick** [woocommerce/action-scheduler#236]
In the WC #core chat there was [some discussion](https://woocommercecommunity.slack.com/archives/C4TNYTR28/p1548954948126400) about expanding the capabilities of Action Scheduler around the increasing number of scheduled tasks. 

The [WooCommerce Admin plugin](https://github.com/woocommerce/wc-admin/) uses scheduled tasks to maintain lookup & statistical tables for the new dashboard. They have asked that we look into implementing [queuing/groups and/or a priority system](https://github.com/woocommerce/wc-admin/issues/1528).

After some discussion with @thenbrent and reviewing the current codebase & custom tables plugin, I have the following proposal for discussion:

1. Implement a priority system using `10` as the default priority (consistent with WP hook priority)
2. Expand groups to allow
-- programatic registration
-- user defined via the dashboard
-- default priority for the group
3. Update the [custom tables](https://github.com/Prospress/action-scheduler-custom-tables/) to reflect 1 & 2
4. Implement custom tables (#77) with limited backward compatibility (ie. new functionality is only available with custom tables)

**Comment by thenbrent** [comment]
> 2\. Expand groups

I really like the idea of using Groups to manage priority vs using hooks. 💯 

Subscriptions doesn't use groups (yet), so existing stores using wouldn't benefit from that. We can change that easily enough though for future actions. We can also make sure webhooks and WC Admin, which are using groups, use a priority > the default as well so that subscription actions are still run.

> 4\. new functionality is only available with custom tables

That sounds like a smart approach to me.

**Comment by pmgarman** [comment]
I support this implementation.

Thoughts - when you have something like the high volume plugin running and you're running multiple "threads"... the ability to specify some of those threads to specific groups/queues would be interesting. In a case like this where there is infrastructure to support it, having dedicated subscription threads and dedicated wc admin threads / etc could be useful. I'm sure the WP CLI commands will support running against specific groups though so maybe that will be enough. Our large sites we run cron via WP CLI anyways for a variety of reasons.

**Comment by rrennick** [comment]
@pmgarman Thanks, good suggestions. Adding group support to the high volume plugin could probably be added to that plugin independently of the changes happening here.

Currently, the WP CLI command only supports a single group but adding support for multiple groups would be a nice enhancement.

**Comment by rrennick** [comment]
Closing this as we haven't seen a situation with 3.X where this was needed.
