### ISSUE TITLE
Admin List table counts on post store inaccurate

### ISSUE THREAD

**Issue by rrennick** [woocommerce/action-scheduler#318]
When you `Delete` actions using the bulk edit, the post status is updated to trash. When actions are canceled using the `Cancel` link, the post status is updated to canceled. 

Trashed actions are included in the list table but not tallied correctly. In the screenshots/data below one canceled action is missing:

```shell
mysql> select post_status, count(*) from wp_posts where post_type = 'scheduled-action' group by post_status;
+-------------+----------+
| post_status | count(*) |
+-------------+----------+
| canceled    |        1 |
| failed      |        1 |
| pending     |        4 |
| publish     |      317 |
| trash       |       43 |
```

<img width="1157" alt="Screen Shot 2019-06-18 at 12 12 36 PM" src="https://user-images.githubusercontent.com/343847/59696484-75599980-91c2-11e9-9303-cdd9756227b2.png">

**Comment by barryhughes** [comment]
Closing, since this is specific to the (effectively deprecated) post store.
