### ISSUE TITLE
Add code sniffing

### ISSUE THREAD

**Issue by rrennick** [woocommerce/action-scheduler#331]
Follow up from https://github.com/Prospress/action-scheduler/pull/323#discussion_r302058476

> The question on that is which set of standards should it follow? It definitely doesn't follow WP standards yet.

[WP coding standards for newer versions of PHP](https://make.wordpress.org/core/2019/07/12/php-coding-standards-changes/)

The WP standards all seemed fine for me except prohibiting the use of short array syntax. With appropriate spacing, I find the short syntax easier to read (partly because it is formatted similar to JSON). 

Since that is the first pass at standards for the newer language features, it may change in the future based on community reaction so we shouldn't feel bound to that.

**Comment by claudiosanches** [comment]
I started a Pull Request using the dev tools that we use on WooCommerce, I hope this may help you all #383

**Comment by barryhughes** [comment]
With the work done in [PR #383](https://github.com/woocommerce/action-scheduler/pull/383) seems like this can be closed (and we can follow-up in further issues if we want to take it further, such as integrating with GH Actions or similar)—feel free to re-open if I'm mistaken!
