### ISSUE TITLE
action-scheduler doesn't load properly unless I change 'plugins_loaded' to 'after_setup_theme' in action-scheduler.php

### ISSUE THREAD

**Issue by Dylan-at-LION** [woocommerce/action-scheduler#359]
I've been using this library in my theme, and if I include it as is, `action_scheduler_register_2_dot_2_dot_5` and `action_scheduler_initialize_2_dot_2_dot_5` in `action-scheduler.php` are never executed. Unless I change `plugins_loaded` to `after_setup_theme`.

https://github.com/Prospress/action-scheduler/blob/master/action-scheduler.php

I've installed it using Composer, and included `action-scheduler.php` at the top of the file where the action is initialized.

I could always just make a fork but I'm wondering if this is an actual issue or it seems like I'm doing something wrong?

**Comment by rrennick** [comment]
> I've been using this library in my theme

`plugins_loaded` has always run before any theme files are loaded. You cannot use the AS library in a theme because the theme files are not loaded in all WP contexts (WP CRON for example).

**Comment by Dylan-at-LION** [comment]
If you cannot use this in a theme then why is this in the repo tagline?

> Specifically designed for distribution in WordPress plugins (and themes)

Granted the [official documentation](https://actionscheduler.org/usage/) removed the confusing part and amended it to:

> Designed for distribution in WordPress plugins

The library is in fact working in a theme, with that small change I mentioned. I mind as well use it as a plugin since that's how it was meant to be used and would probably avoid issues down the line, but it is working so far.

**Comment by thenbrent** [comment]
@rrennick I don't see any reason we shouldn't make it possible to work with themes also. As @Dylan-at-LION points out, I had intended for it to work in themes.

Is there a hook we can use instead of `plugins_loaded` to support use in themes that is also loaded in all WP contexts? (unlike `'after_setup_theme'`).

**Comment by thenbrent** [comment]
> `init` is the hook immediately `after after_setup_theme`. We could test to see if the async runner works with AS initialized in `after_setup_theme`.

Perhaps we could switch to use `init` with a negative priority, like `-1000` (the priority needs to be < 10 to work with WP Cron, and < 0 to run before everything in `ActionScheduler::init()`).

**Comment by rrennick** [comment]
> Perhaps we could switch to use init with a negative priority, like -1000 

That sounds good. Any priority less than 0 would work. `-10` might be a good signal to not hook any related functionality before it.

**Comment by thenbrent** [comment]
@Dylan-at-LION I've submitted #372 to address this. As mentioned in the comments, it's a breaking change so we will attempt to release it with 3.0.0, but if we find it breaking compatibility with 3rd party code, we may have to revert it and instead document alternative, more manual methods for Action Scheduler to be compatible with themes.

If you could please test #372 to confirm Action Scheduler is now working with your theme, that would be greatly appreciated. Please note, that the `issue/359` branch is based on the 3.0.0 codebase, which migrates data to custom tables, so once you have checked out the `issue/359` branch, a migration process will be. If you want to revert to a `2.n` version of Action Scheduler after that, you will need to make a backup of your database prior to checking out the `issue/359` branch.

The 3.0.0 codebase is now in `master`, and currently in beta testing, with expected official release in about 2 weeks, so it is stable enough to remain using in development (i.e. rolling back your database to a backup should not be required).

**Comment by Dylan-at-LION** [comment]
@thenbrent I can confirm that `issue/359` works in my theme with no issues. Thanks for the update.
