### ISSUE TITLE
"Cannot declare class" error

### ISSUE THREAD

**Issue by nielash** [woocommerce/action-scheduler#385]
I am running 3.0.0-RC-2 and getting the following error:

`An error of type E_COMPILE_ERROR was caused in line 19 of the file [root directory]/wp-content/plugins/action-scheduler-master/classes/migration/Config.php. Error message: Cannot declare class Action_Scheduler\Migration\Config, because the name is already in use`

I think I've narrowed it down to a conflict with the "[Admin Columns Pro](https://www.admincolumns.com/)" plugin -- both plugins work fine when the other is deactivated but not when both are activated. I notice that Admin Columns also has a Config class, but I would have thought that the namespace would prevent conflicts. [Here's a link](https://github.com/codepress/admin-columns/blob/fd80f71741a245bcd6d446e3fccb9314f5cbbaa1/classes/Config.php#L5) to the class declaration in the free version, but note that the error does not seem to occur in the free version, so that might be a red herring. Also worth noting that the issue does not occur with Action Scheduler 2.2.5.

Entirely possible that this is ACP's fault, in which case feel free to disregard.

Steps to reproduce:

1. Activate both Action Scheduler 3.0.0-RC-2 and Admin Columns Pro 4.7.2
2. Navigate to any of: 
`/wp-admin/upload.php`
`/wp-admin/edit.php`
`/wp-admin/users.php`

**Comment by rrennick** [comment]
@nielash Would you be able to test #388 to see if it addresses the issue for you?

**Comment by nielash** [comment]
@rrennick I just tested it and can confirm this fixes it. Thanks!
