### ISSUE TITLE
Security Issue

### ISSUE THREAD

**Issue by korndev** [woocommerce/action-scheduler#396]
How should a potential security issue be disclosed?

I setup Action Schedule on an internal project for a company I work with that runs CheckMarx on all new code introduced and something was flagged.

Thanks,
Justin

**Comment by rrennick** [comment]
Hi Justin, Thanks for contacting us. Use https://hackerone.com/automattic .

**Comment by korndev** [comment]
@rrennick I'm in over my head with making a report. I'm not a hacker and really don't know what the majority of the questions being asked are within the report form. Any other way to communicate the issue. I can create a pull request with what I believe the fix would be, but don't want to do that if the issue should be patched before disclosure in public, etc.

**Comment by rrennick** [comment]
Can you check the 3.0.0 RC to see if it has the vulnerability? https://github.com/woocommerce/action-scheduler/releases

If you join the WooCommerce community slack, you can PM me there (same handle as here) https://woocommerce.com/community-slack/

**Comment by korndev** [comment]
Using RC-4 - going to check on a few things and then reach out to you via Slack. Thanks!
