### ISSUE TITLE
Add migration failure warning

### ISSUE THREAD

**Issue by rrennick** [woocommerce/action-scheduler#398]
If for some reason the post store is unable to delete an action after it has been migrated to the custom tables then the migration process continues indefinitely adding copies of the action to the custom tables store.

Reproduce using the following:
- Activate WooCommerce to have AS 2.2.5 active
- Ensure there is at least one existing action in the post store
- Add this filter
```
add_filter( 'pre_delete_post', function( $delete, $post ) {
	if ( ! class_exists( 'ActionScheduler_wpPostStore' ) ) {
		return $delete;
	}
	if ( $post->post_type === ActionScheduler_wpPostStore::POST_TYPE ) {
		return false;
	}
	return $delete;
}, 10, 2 );
```
- Activate AS 3.0.0RC

Alternatives we could consider
- stop the migration
- mark the action as migrated
- add a warning to the dashboard

**Comment by thenbrent** [comment]
> mark the action as migrated

I think that's likely the best approach. We'd need to introduce a whole new system for that, like adding a post meta flag or something to it (before it's deleted in case the deletion fails) and then checking that flag when attempting to migrate it.
