### ISSUE TITLE
Recurring after firing adds duplicated and runs twice

### ISSUE THREAD

**Issue by jesperkaae** [woocommerce/action-scheduler#400]
When im adding an recurring schedule, with the following code:

`    public function simulat_daily_data_cron(){
        $date = strtotime(date('m/d/Y')." 02:11");
        if ( false === as_next_scheduled_action( 'run_simulat_daily_data' ) ) {
          as_schedule_recurring_action($date, HOUR_IN_SECONDS, 'run_simulat_daily_data' );
        }
    }`

It creates just 1 recurring under "Scheduled Actions", but after it have been fired 3-4 times, it adds a duplicate of the same schedule which runs at the exactly same time, after a few times it gets fired. 

<img width="1069" alt="Skærmbillede 2019-12-05 kl  09 55 54" src="https://user-images.githubusercontent.com/12173563/70219808-c2680280-1745-11ea-94b5-f5af8b025d7c.png">

**Comment by rrennick** [comment]
@jesperkaae Thanks for reporting the issue. It had been reported earlier and has been fixed in #392 .

Closing this as a duplicate.
