### ISSUE TITLE
Actions with args more than 191 characters long prevent migration in AS 3.0.0 from completing

### ISSUE THREAD

**Issue by wvega** [woocommerce/action-scheduler#401]
If an action cannot be saved to the destination data store because the action's args no longer fit the maximum number of characters in the column, the **Action Scheduler migration in progress. The list of scheduled actions may be incomplete** notice will continue to be shown indefinitely.

You can reproduce this If you create a recurring action using the code below in AS 2.2.5 and then activate AS 3.0.0.

```php
as_schedule_recurring_action(
    strtotime( '+2 hours' ),
    DAY_IN_SECONDS,
    'as_test_hook',
    array_fill( 0, 100, 9999 )
);
```

I don't think there is much that AS can do about those actions directly. The code that registered the action is likely the only one that would know how to split it into smaller actions that achieve the same result.

I saw this issue once with a task from TaxJar, but I'm not sure how common it can really be. So I guess the purpose of this issue is to raise awareness.

As a suggestion, the Action Scheduler section in the WooCommerce > System Status could show the hooks of actions that couldn't be migrated for the reason mentioned above. That would make it easier to understand why the migration never finishes if the issue comes up and would allow support requests to be redirected to the owners of the plugins that registered those actions to handle the migration.

**Comment by wvega** [comment]
As a related note, AS 2.2.5 currently shows a notice when you try to create such an action, but the action is still created.

>ActionScheduler_Action::$args was called <strong>incorrectly</strong>. To ensure the action args column can be indexed, action args should not be more than 191 characters when encoded as JSON. Support for strings longer than this will be removed in a future version.

On AS 3.0.0, trying to create the same action throws a RuntimeException:

>Error saving action: Error saving action: Database error.

**Comment by thenbrent** [comment]
This is a tricky one. Thanks for reporting @wvega!

> I saw this issue once with a task from TaxJar

Do you happen to know which TaxJar plugin? We could submit a patch directly. That's the only known offender atm, so I'd prefer to fix it directly ASAP rather than making more widespread changes to AS 3.0, like allowing > 191 chars again...

> As a suggestion, the Action Scheduler section in the WooCommerce > System Status could show the hooks of actions that couldn't be migrated for the reason mentioned above.

We can also:

1. make sure the action is marked as `failed` during migration; or
1. block the migration and only begin it once we know for sure there are no actions with `args` > 191 characters (the safest approach, that will ensure no data corruption, but also hacky)

@rrennick @james-allan thoughts on those two options?

**Comment by wvega** [comment]
>Do you happen to know which TaxJar plugin?

@thenbrent it was an action from [TaxJar - Sales Tax Automation for WooCommerce](https://wordpress.org/plugins/taxjar-simplified-taxes-for-woocommerce/) (seems to be offered in https://woocommerce.com/products/taxjar/ too).

Unlike my example above, they use `as_schedule_single_action()`, with the same result:

https://plugins.trac.wordpress.org/browser/taxjar-simplified-taxes-for-woocommerce/trunk/includes/class-wc-taxjar-transaction-sync.php#L196

At the time I saw the action that couldn't be migrated, the TaxJar queue was also long enough that the plugin was no longer able to schedule additional actions due to the RuntimeException.

A quick solution in that case was to use [the `taxjar_record_batch_size ` filter](https://plugins.trac.wordpress.org/browser/taxjar-simplified-taxes-for-woocommerce/trunk/includes/class-wc-taxjar-transaction-sync.php#L192) to reduce the length of the `$args` parameter, but a direct verification would be better.

**Comment by rrennick** [comment]
> the safest approach, that will ensure no data corruption, but also hacky

I'd prefer this because it won't affect the majority of users and it allows us to implement a more comprehensive solution in 3.1.
