### ISSUE TITLE
Very slow WP CLI Processing

### ISSUE THREAD

**Issue by colmtroy** [woocommerce/action-scheduler#403]
I manage one WC website that is currently averaging approx. 2,400 new scheduled actions per hour at peak times (but averaging out at around 24,000 new actions per day).

When I attempt to run the queue via WP CLI, pending actions start piling up quite quickly.

I also installed the default runner disabler to ensure everything is being processed via WP CLI.
https://github.com/woocommerce/action-scheduler-disable-default-runner.

When I run this via terminal:

```
wp action-scheduler run --batch-size=200 --batches=10 --force
```
I can see it takes 10-15 mins for a batch of 200 actions to be processed, but given the creation rate is much faster you can see my problem.

Questions!
1.) I assumed the --batches flag meant concurrent batches - is this the case?
2.) After the first 200 actions are processed I see a "Warning: Attempting to reduce used memory" message. I've tons of memory/CPU available so I'm wondering what value I need to tweak to ensure the processing break can be removed.
3.) When I revert back to the High Volume Action Scheduler plugin in WP Admin actions are processed much quicker. But I'd prefer to have more control over the process via WP CLI if possible.

Is there something special about how the High Volume plugin works that allows batches to run concurrently that I can't avail of via WP CLI??

Thanks!

**Comment by thenbrent** [comment]
>  1.) I assumed the --batches flag meant concurrent batches - is this the case?

No. For concurrent queues, you need to run additional WP CLI commands.

The `--batches` flag defines the number of batches that will be processed before ending the WP CLI command. i.e. with `--batch-size=200`, your WP CLI command will process 2,000 action then terminate.

> 2.) After the first 200 actions are processed I see a "Warning: Attempting to reduce used memory" message. I've tons of memory/CPU available so I'm wondering what value I need to tweak to ensure the processing break can be removed.

Nothing on your end. It probably shouldn't say `Warning`, it's really just letting you know it's taking that step in the process.

>  3.) When I revert back to the High Volume Action Scheduler plugin in WP Admin actions are processed much quicker. But I'd prefer to have more control over the process via WP CLI if possible.

The speed different is most likely because multiple queues are not running with WP CLI. If you can get 10 or more queues running via 10 or more WP CLI separate commands, you will likely see much faster processing.

If you are not using AS 3.0 RC yet, I would also highly recommend upgrading to that, as it will significantly increase processing time bother on the default runner, and WP CLI runner.

Please be sure to test it on a staging environment first though, so it migrates all your scheduled action data in a way that is not reversible.

Hope that helps!

**Comment by colmtroy** [comment]
@thenbrent thanks for the quick reply and helpful clarifications! I plan on taking a closer look at the 3.0 RC next week - but I'll see what I can squeeze out of WP CLI in the meantime :)

**Comment by lkraav** [comment]
> > 2.) After the first 200 actions are processed I see a "Warning: Attempting to reduce used memory" message. I've tons of memory/CPU available so I'm wondering what value I need to tweak to ensure the processing break can be removed.

> Nothing on your end. It probably shouldn't say Warning, it's really just letting you know it's taking that step in the process.

I just updated to WooCommerce 4.0 RC, and my staging cron (=== non-existent workload) is now outputting "Attempting to reduce used memory..." on every run.

https://github.com/woocommerce/action-scheduler/blob/3.1.1/classes/ActionScheduler_DataController.php#L137 how often does `free_memory()` execute? Not really possible to tell externally looking at the blocking condition. Either way, not sure if this warning is appropriate to spam crons with - I mean is there any action to take either way? I'd rather hear about things when they actually go wrong.

Your thoughts?

**Comment by rrennick** [comment]
> Your thoughts?

@lkraav I'm happy to look at a PR that adds filter(s) to disable either the message and/or the memory reduction.

**Comment by lkraav** [comment]
> I'm happy to look at a PR that adds filter(s) to disable either the message and/or the memory reduction.

It looks like this message is triggered only in the initial migration phases maybe. It stopped spamming cron some time after I typed the previous comment. Might be that noop is OK here, but I'll let yall know once the live server upgrades to WC 4.0.

**Comment by thenbrent** [comment]
> It looks like this message is triggered only in the initial migration phases maybe.

That's very likely given the increased rate of work AS needs to do during migration to migrate all the actions.
