### ISSUE TITLE
Update docs/*.md for v3.0

### ISSUE THREAD

**Issue by slaFFik** [woocommerce/action-scheduler#411]
Right now `index.md` is not up-to-date with the code.
For example, it mentions CPTs that v3 is not using anymore (if I understood correctly the release post on woocommerce.wordpress.com).

---

File `api.md`:
> `as_schedule_single_action()` & `as_schedule_recurring_action()` will return the post ID of the scheduled action...

And I believe it should omit the word `post`.

**Comment by thenbrent** [comment]
Thanks for the report @slaFFik. I've fixed up that incorrect reference, and made a number of other improvements to the docs for v3.0 in #414.
