### ISSUE TITLE
Investigation: composer and packagist

### ISSUE THREAD

**Issue by slaFFik** [woocommerce/action-scheduler#413]
In your docs you mention the ability to install via composer.
You don't provide a code snippet for that, but that's ok.
I open `composer.json` file and see `woocommerce/action-scheduler` as a package name.
I try `composer require woocommerce/action-scheduler` and get an error about "typo in package name", which doesn't make sense. I see that name in your `composer.json` file!
Ok, I try to find the package `woocommerce/action-scheduler` on packagist.org - no such thing exists there. So that means in the doc you say about composer but the package is not published?
I'm searching even more, and find a ticket about composer issue that mentions autoload of your main lib file and there is a `vendor` path there: `prospress/action-scheduler`.
So you have a published (but outdated) `prospress/action-scheduler` package [here](https://packagist.org/packages/prospress/action-scheduler) - there is v3.0 there, only RC4.
And no one can install using composer and the package name from your `composer.json` file: `woocommerce/action-scheduler`

It would be nice if you could clean up this inconsistency.

**Comment by thenbrent** [comment]
@slaFFik thanks for the report.

@rrennick could you please update Packagist to point to the new GitHub organisation? It looks like we may need to [adandon the old package and create a new one](https://github.com/composer/packagist/issues/47), because the current package includes `/prospress/` in the name and Packagist doesn't allow a package to be renamed.

**Comment by unfulvio** [comment]
as a temporary workaround you can point composer to a git repository:

```json
 "repositories": [
    {
      "type": "vcs",
      "url": "https://github.com/woocommerce/action-scheduler"
    }
  ],
  "require": {
    "woocommerce/action-scheduler": "3.0.0"
  },
}

**Comment by rrennick** [comment]
> could you please update Packagist to point to the new GitHub organisation?

Package has been updated: https://packagist.org/packages/prospress/action-scheduler
