### ISSUE TITLE
Minimum PHP version?

### ISSUE THREAD

**Issue by slaFFik** [woocommerce/action-scheduler#422]
There is no PHP version defined in `composer.json` file, and from the code, I see that the library requires at least PHP 5.4, maybe even more modern.

I know that WC is PHP 5.6 and soon PHP 7+ soon, but what about the lib?

In `tests/phpunit.xml.dist` I see PHP 5.6, but that's for tests.
In `classes/ActionScheduler_DataController.php` I see this:
```php
/** Migration minimum required PHP version. */
const MIN_PHP_VERSION = '5.5';
```

**Comment by rrennick** [comment]
@slaFFik Thanks for the report. I've created #423 if you would like to provide any feedback.
