### ISSUE TITLE
Actions showing up in comments.php in admin when AS is loaded manually

### ISSUE THREAD

**Issue by maximebj** [woocommerce/action-scheduler#429]
Hi. When loading manually the library in a project, actions are shown in comments.php.
In my project, I now use AS from WooCommerce directly and  I don't have the issue anymore.

But recently, WooCommerce Subscription stated to use AS and they load the library manually :

`require_once( dirname( __FILE__ ) . '/includes/libraries/action-scheduler/action-scheduler.php' );`

I don't know why, as WooCommerce is required, why they have to load it again. 
And in that way the issue is back : actions are displayed in the comments admin page. They disappear if I comment the line above.

However, I can see a hook on `pre_get_commets` in the lib that I suspect is here (from 2014) for this very purpose. 

An idea of what is going on? 

Before posting this, I've searched for other plugins using `pre_get_commets` on my website and got 2. I deactivated them without noticing any difference. 

I'm really sorry if I missed an obvious thing but I'm searching for a while without finding what causes this. Thanks !

**Comment by maximebj** [comment]
Ok thanks for the quick answer. 
So WooCommerce prevents displaying things, but they must have been deleted automatically by another action cleanup_wp_comment_logs

I've checked, this action doesn't exist. I've also lost 3 of my actions the day I've updated Subscription. Can I schedule again a cleanup_wp_comment_logs manually? 

But so it's a Woo Subscription issue, and not an AS issue. 

Here are my last actions listed (from this morning)
- wcs_report_update_cache
- woocommerce_scheduled_subscription_payment

I can also see my own actions. 

Do you know why Subscription includes AS, whereas it's already included in WooCommerce Core ? when I use AS functions without including AS, it works well without issue.

Anyway, I've opened a Woo support ticket, they'll get back to me soon. You can close this issue as it's non related to AS directly.

**Comment by maximebj** [comment]
Ok so, I've searched and here what I've found : 

AS is a CPT, that supports Comments, so abviously the'll appear in comments.php 
AS has a hook on pre_get_comments to add action_log_filter  but it does nothing (maybe used for later cleanup) 

So I don't mind if a cleanup should occurs today, in 6 month, but user shouldn't have AS log right in their comments panel. 

On my website, I just added : 

`
add_filter( 'pre_get_comments', 'hide_actions_scheduler_notifications'  );
function hide_actions_scheduler_notifications( $query ) {
    $query->query_vars['type__not_in'] = ['action_log'];
}
`

And they don't appear. 

I'm not yet expert with all of this and sorry if my question is silly, but can you tell me : why such filter is not included by default in AS core, so people using it won't have the comments polluted ? 
And why the WooCommerce way (Tools > Actions) is not default too ? Maybe we could use a constant to define if we want to show actions UI, or not (like debug const which is helpful to show/hide errors on dev)

**Comment by rrennick** [comment]
> Do you know why Subscription includes AS, whereas it's already included in WooCommerce Core ?

AS is always included in WC Subscriptions. New versions of AS go out in WC Subs before being updated in WC core.

> On my website, I just added 

That snippet is fine.

> I suggest than AS gets its own UI, like WooCommerce currently does (Tools > Actions).

That screen is added by Action Scheduler.

> So I don't mind if a cleanup should occurs today, in 6 month

If you want to remove them now you can schedule the action to run immediately with

```
as_enqueue_async_action( 'action_scheduler/cleanup_wp_comment_logs' );
```

Once it's run, remove the code. Otherwise it will continue scheduling another instance of the action.

**Comment by maximebj** [comment]
Ok! everything is clear. Thanks for your answers !

I'll run the cleanup action. And maybe also keep my snippet active in case theses actions come back in comments.

**Comment by rrennick** [comment]
> And maybe also keep my snippet active in case theses actions come back in comments.

You shouldn't see any new instances of action logs in the comments.

**Comment by maximebj** [comment]
Correct ! 

I removed my snippet. Thanks a lot!
