### ISSUE TITLE
Ability to hide "Tools > Scheduler Actions" page

### ISSUE THREAD

**Issue by slaFFik** [woocommerce/action-scheduler#431]
Not always a page "Scheduled Actions" is needed to be public in the admin area.

I would like to be able to hide it using a built-in filter in `\ActionScheduler::init()`, similar to what is done with deprecated functions (using `action_scheduler_load_deprecated_functions` filter).

Of course, I can hide it like this:
```php
add_action( 'admin_menu', function() {
	remove_submenu_page( 'tools.php', 'action-scheduler' );
}, PHP_INT_MAX );
```
with own conditions (when to actually hide it) in that closure, but a native filter, `action_scheduler_load_admin_view`, would be preferrable.

**Comment by crstauf** [comment]
@slaFFik Note that this has been resolved and will be available in [3.2.0](https://github.com/woocommerce/action-scheduler/tree/version_3_2_0).

**Comment by rrennick** [comment]
Addressed in #476

**Comment by fidoboy** [comment]
How can this menu be restored with some kind of filter into functions.php?

**Comment by rrennick** [comment]
@fidoboy You need to find where it's being removed. It can be removed with a snippet like the one in the issue description or with the filter in #476.
