### ISSUE TITLE
docs/Usage page sections order is incorrect

### ISSUE THREAD

**Issue by slaFFik** [woocommerce/action-scheduler#432]
Steps at the top of the page:
> 1. installing the library
> 1. scheduling and action
> 1. attaching a callback to that action

But later in the doc, you start with Scheduling first, then Installation. 
And the 3rd step doesn't make sense, as there is no such section on a page at all.

So, imo, the text on a page should be re-arranged, and steps should be tweaked.

**Comment by slaFFik** [comment]
With 3.1 (where composer.json `autoload` changes were implemented) the composer usage should be specifically outlined.

**Comment by rrennick** [comment]
@slaFFik Thanks for reporting this. If you have a few minutes could you review #438 to see if I missed anything?
