### ISSUE TITLE
Add async runner filter to docs

### ISSUE THREAD

**Issue by rrennick** [woocommerce/action-scheduler#438]
We are seeing some reports of deadlocks & 503s from the aync runner. We should add a section to the 3.0 page with instructions for using the `'action_scheduler_async_request_sleep_seconds'` filter to reduce the async runner load frequency or `'action_scheduler_allow_async_request_runner'` to disable it completely.

**Comment by thenbrent** [comment]
Are the issues only during migration? If so, we could [remove chaining DBStore migration](https://github.com/woocommerce/action-scheduler/pull/349) by reinstate the throttle by [increasing the interval back to 30](https://github.com/woocommerce/action-scheduler/commit/a90dcaced1ebfebfa83b979e945886930e9254f0), or something lower.

> We are seeing some reports of deadlocks & 503s from the aync runner.

If the issues are ongoing and widespread, we should also consider disabling the async runner by default, and only switching it on via the filter, instead of switching it off using that.

**Comment by glagonikas** [comment]
In our case (unreported so far) we saw the deadlocks long after the migration was complete yesterday morning.

We received 3 of the following
`WordPress database error Deadlock found when trying to get lock; try restarting transaction for query UPDATE wp_actionscheduler_actions SET attempts = attempts+1, status='in-progress', last_attempt_gmt = '2020-01-27 22:06:07', last_attempt_local = '2020-01-27 22:06:07' WHERE action_id = 1689450 made by do_action_ref_array('action_scheduler_run_queue'), WP_Hook->do_action, WP_Hook->apply_filters, ActionScheduler_QueueRunner->run, ActionScheduler_QueueRunner->do_batch, ActionScheduler_Abstract_QueueRunner->process_action, ActionScheduler_DBStore->log_execution`

and one of the following
`WordPress database error Deadlock found when trying to get lock; try restarting transaction for query UPDATE wp_actionscheduler_actions SET attempts = attempts+1, status='in-progress', last_attempt_gmt = '2020-01-27 22:08:02', last_attempt_local = '2020-01-27 22:08:02' WHERE action_id = 1689600 made by do_action('wp_ajax_nopriv_as_async_request_queue_runner'), WP_Hook->do_action, WP_Hook->apply_filters, WP_Async_Request->maybe_handle, ActionScheduler_AsyncRequest_QueueRunner->handle, do_action('action_scheduler_run_queue'), WP_Hook->do_action, WP_Hook->apply_filters, ActionScheduler_QueueRunner->run, ActionScheduler_QueueRunner->do_batch, ActionScheduler_Abstract_QueueRunner->process_action, ActionScheduler_DBStore->log_execution`

We have some custom code that uses sends out emails using AS (similar to Follow-up emails) and was working flawlessly before the update.

We have also disabled wp-cron and call wp-cron.php via cron job once a minute. Not sure if that's related.

p.s. Considering the deadlocks issue is reported deep inside the unrelated issue https://github.com/woocommerce/action-scheduler/issues/436 it might be worth creating a new issue specifically for this?

**Comment by rrennick** [comment]
> we should also consider disabling the async runner by default, and only switching it on via the filter

I think the deadlocks are mainly being reported on migration because the migration has intensive activity on the AS tables. But there are enough reports of deadlocks occurring after migration that turning it off by default seems like the best mitigation for 3.0. Longer term we can look at a better strategy for arbitrating between CRON and the async runner.

> Considering the deadlocks issue is reported deep inside the unrelated issue #436 it might be worth creating a new issue specifically for this?

I created #441. @glagonikas Thanks for the detailed info. Could you try out the filter in https://github.com/woocommerce/action-scheduler/issues/436#issuecomment-579012904 and let us know how effective that is for the deadlocks?

**Comment by glagonikas** [comment]
@rrennick will do. I'll check if deadlocks will occur tonight also. If they do, i'll add the code and check tomorrow.

**Comment by thenbrent** [comment]
@glagonikas are you using WP CLI to process actions too? If so, two follow-up questions:

1. have you ever seen deadlocks using CLI?
1. are CLI commands running at the same time as Async or WP Cron runners?

> But there are enough reports of deadlocks occurring after migration that turning it off by default seems like the best mitigation for 3.0. Longer term we can look at a better strategy for arbitrating between CRON and the async runner.

@rrennick a less extreme option for now is to increase [the wait time to 5 seconds (from 1 second)](https://github.com/woocommerce/action-scheduler/blob/3.0.0/classes/ActionScheduler_AsyncRequest_QueueRunner.php#L90-L95) applied to [throttle chained loopback requests](https://github.com/woocommerce/action-scheduler/blob/3.0.0/classes/ActionScheduler_AsyncRequest_QueueRunner.php#L54-L60). I know that longer sleep time worked for AutomateWoo previously with similar issues doing background processing (though we never knew why, which is partly why I went with the more aggressive 1 second in AS).

**Comment by glagonikas** [comment]
Hi @thenbrent i don't think we use WP CLI

**Comment by glagonikas** [comment]
Just to mention that we are still getting deadlocks occasionally, after updating to the latest version of WC. We use v3.1.4 that comes with it.

The deadlocks are relating to `wc-admin_import_orders` and `wc-admin_import_customers`. We've been unable to import the data so far.

I've added the filter linked in [#436 (comment)](https://github.com/woocommerce/action-scheduler/issues/436#issuecomment-579012904) but we still get deadlocks.

For the record, wp cron is disabled on our site and we call wp-cron.php via a cron job every minute

**Comment by rrennick** [comment]
> I've added the filter linked in #436 (comment) but we still get deadlocks.

@glagonikas Where did you add the filter?

**Comment by glagonikas** [comment]
mu-plugins

**Comment by rrennick** [comment]
@glagonikas This PR is just for the documentation update. 

`mu-plugins` would be a good location for the filter so I'm not sure how you would be getting deadlocks with just WP Cron running actions now if you weren't before. In AS 2.X, the cron runner would have been contending with other users of the post tables. Once your site is migrated AS is the only user of the action tables. Do you have an estimate of how many actions are being created and run on an average day?

**Comment by glagonikas** [comment]
It's to do with the amount of actions that run after we upgraded to WC4. To populate the reports, WC has created a lot of actions (24k yesterday, 23k so far today) and there is some conflict there.

Before WC4, we would primarily use AS for WC Subscription renewals, so we would never have so many actions running in a single day.

While WC updates the reports, we get around 1-2 deadlocks a minute.

**Comment by rrennick** [comment]
@glagonikas How many new orders in a day? There are 2 actions created for each new order.

**Comment by thenbrent** [comment]
> It's to do with the amount of actions that run after we upgraded to WC4.

Interesting. I wonder if deadlocks are being caused by requests _creating_ actions, rather than just AS processing actions (which is what the `action_scheduler_allow_async_request_runner` filter changes).

There's many plugins that create actions on `init` or similar hooks, so if a site is seeing a lot of activity, and there's no throttle on creating those actions, that could lead to deadlocks.

**Comment by glagonikas** [comment]
> @glagonikas How many new orders in a day? There are 2 actions created for each new order.

We have a busy site with new and subscription orders running in the hundreds daily


> Interesting. I wonder if deadlocks are being caused by requests _creating_ actions, rather than just AS processing actions (which is what the `action_scheduler_allow_async_request_runner` filter changes).

Not sure if it helps, but the deadlocks are the following
`WordPress database error Deadlock found when trying to get lock; try restarting transaction for query UPDATE wp_actionscheduler_actions SET attempts = attempts+1, status='in-progress', last_attempt_gmt = '2020-04-20 17:00:02', last_attempt_local = '2020-04-20 18:00:02' WHERE action_id = 1877421 made by do_action('wp_ajax_as_async_request_queue_runner'), WP_Hook->do_action, WP_Hook->apply_filters, WP_Async_Request->maybe_handle, ActionScheduler_AsyncRequest_QueueRunner->handle, do_action('action_scheduler_run_queue'), WP_Hook->do_action, WP_Hook->apply_filters, ActionScheduler_QueueRunner->run, ActionScheduler_QueueRunner->do_batch, ActionScheduler_Abstract_QueueRunner->process_action, ActionScheduler_DBStore->log_execution, QM_DB->query`
and
`WordPress database error Deadlock found when trying to get lock; try restarting transaction for query UPDATE wp_actionscheduler_actions SET attempts = attempts+1, status='in-progress', last_attempt_gmt = '2020-04-20 17:02:08', last_attempt_local = '2020-04-20 18:02:08' WHERE action_id = 1877473 made by do_action_ref_array('action_scheduler_run_queue'), WP_Hook->do_action, WP_Hook->apply_filters, ActionScheduler_QueueRunner->run, ActionScheduler_QueueRunner->do_batch, ActionScheduler_Abstract_QueueRunner->process_action, ActionScheduler_DBStore->log_execution`

They don't look like create actions to me, but I don't know the ins and outs of AS.
You can ignore Query Monitor, the issue persists even when it's disabled.

**Comment by rrennick** [comment]
> They don't look like create actions to me, but I don't know the ins and outs of AS.

A deadlock requires two or more database queries running at the same time. If there are only two queries then the deadlock affects the second one starting. The error log doesn't contain any information on what the first query is.

> `do_action('wp_ajax_as_async_request_queue_runner')`

The async runner is still active. Can you comment with the filter you added to your `mu-plugins` folder?

**Comment by glagonikas** [comment]
I had just this
`add_filter( 'action_scheduler_allow_async_request_runner', '__return_false' );`

Here's the deadlock details too

```
------------------------
LATEST DETECTED DEADLOCK
------------------------
2020-04-21 14:44:56 0x7f121c442700
* (1) TRANSACTION:
TRANSACTION 269973366, ACTIVE 4 sec updating or deleting
mysql tables in use 1, locked 1
LOCK WAIT 4 lock struct(s), heap size 1136, 3 row lock(s), undo log entries 1
MySQL thread id 2099893, OS thread handle 139742331373312, query id 218071551 xxx.xxx.xxx.xxx yyyyy Updating
UPDATE wp_actionscheduler_actions SET attempts = attempts+1, status='in-progress', last_attempt_gmt = '2020-04-21 13:44:52', last_attempt_local = '2020-04-21 14:44:52' WHERE action_id = 1890552
* (1) WAITING FOR THIS LOCK TO BE GRANTED:
RECORD LOCKS space id 3524 page no 2736 n bits 672 index status of table `yyyyy`.`wp_actionscheduler_actions` trx id 269973366 lock_mode X insert intention waiting
Record lock, heap no 1 PHYSICAL RECORD: n_fields 1; compact format; info bits 0
 0: len 8; hex 73757072656d756d; asc supremum;;

* (2) TRANSACTION:
TRANSACTION 269971034, ACTIVE 202 sec fetching rows
mysql tables in use 3, locked 3
3310 lock struct(s), heap size 385232, 339898 row lock(s)
MySQL thread id 2099912, OS thread handle 139715760367360, query id 218027094 xxx.xxx.xxx.xxx yyyyy Init for update
UPDATE wp_actionscheduler_actions SET claim_id=183806, last_attempt_gmt='2020-04-21 13:41:34', last_attempt_local='2020-04-21 14:41:34' WHERE claim_id = 0 AND scheduled_date_gmt <= '2020-04-21 13:41:34' AND status='pending' ORDER BY attempts ASC, scheduled_date_gmt ASC, action_id ASC LIMIT 100
* (2) HOLDS THE LOCK(S):
RECORD LOCKS space id 3524 page no 2736 n bits 672 index status of table `yyyyy`.`wp_actionscheduler_actions` trx id 269971034 lock_mode X
Record lock, heap no 1 PHYSICAL RECORD: n_fields 1; compact format; info bits 0
 0: len 8; hex 73757072656d756d; asc supremum;;

* (2) WAITING FOR THIS LOCK TO BE GRANTED:
RECORD LOCKS space id 3524 page no 2737 n bits 776 index status of table `yyyyy`.`wp_actionscheduler_actions` trx id 269971034 lock_mode X waiting
Record lock, heap no 665 PHYSICAL RECORD: n_fields 2; compact format; info bits 32
 0: len 7; hex 70656e64696e67; asc pending;;
 1: len 8; hex 00000000001cd8f8; asc         ;;

* WE ROLL BACK TRANSACTION (1)
------------
TRANSACTIONS
------------
Trx id counter 269973434
Purge done for trx's n:o < 269973434 undo n:o < 0 state: running but idle
History list length 0
LIST OF TRANSACTIONS FOR EACH SESSION:
---TRANSACTION 421217314710296, not started
0 lock struct(s), heap size 1136, 0 row lock(s)
---TRANSACTION 421217314582616, not started
0 lock struct(s), heap size 1136, 0 row lock(s)
---TRANSACTION 269973429, ACTIVE 2 sec starting index read
mysql tables in use 3, locked 3
LOCK WAIT 2 lock struct(s), heap size 1136, 1 row lock(s)
MySQL thread id 2100342, OS thread handle 139715226101504, query id 218072430 xxx.xxx.xxx.xxx yyyyy Init for update
UPDATE wp_actionscheduler_actions SET claim_id=183868, last_attempt_gmt='2020-04-21 13:44:57', last_attempt_local='2020-04-21 14:44:57' WHERE claim_id = 0 AND scheduled_date_gmt <= '2020-04-21 13:44:57' AND status='pending' ORDER BY attempts ASC, scheduled_date_gmt ASC, action_id ASC LIMIT 100
------- TRX HAS BEEN WAITING 2 SEC FOR THIS LOCK TO BE GRANTED:
RECORD LOCKS space id 3524 page no 3281 n bits 824 index claim_id of table `yyyyy`.`wp_actionscheduler_actions` trx id 269973429 lock_mode X waiting
Record lock, heap no 2 PHYSICAL RECORD: n_fields 2; compact format; info bits 0
 0: len 8; hex 0000000000000000; asc         ;;
 1: len 8; hex 00000000001975ed; asc       u ;;
```

**Comment by rrennick** [comment]
> I had just this `add_filter( 'action_scheduler_allow_async_request_runner', '__return_false' );`

How did you add it to the `mu-plugins` folder?

**Comment by glagonikas** [comment]
Just made a PHP file and threw this code in. Is there anything in particular you're worried about or a specific way this filter works?

**Comment by rrennick** [comment]
> Is there anything in particular you're worried about a specific way this filter works?

Given the deadlock is occurring in the async runner either the filter doesn't work as designed or your implementation of the filter isn't being applied.

**Comment by glagonikas** [comment]
I think it would be important to understand why the deadlocks happen in the first place. We don't have duplicate cron jobs, so #528 doesn't apply to us.

Based on the deadlock details i sent above, it seems the code is trying to log the execution (log_execution), before it's done claiming all jobs, so one update query bumps onto the other.

If that's the case, making the claim query faster (or smaller) or delaying log_execution might help?

**Comment by rrennick** [comment]
> it seems the code is trying to log the execution (log_execution), before it's done claiming all jobs

All of the error log entries I've seen for this occurred in the async runner and none in the WP CLI or WP Cron runners. That suggests it's related to a process flow in some way. Since this issue was for updating documentation I'll create a separate issue for discussing the deadlocks.
