### ISSUE TITLE
Deadlocks being reported after migration is complete

### ISSUE THREAD

**Issue by rrennick** [woocommerce/action-scheduler#441]
Multiple users have reported sporadic deadlocks occurring after the migration is complete. We'll use this issue to collect some of those reports and discuss disabling the async runner by default.

**Comment by rrennick** [comment]
Ref: https://github.com/woocommerce/action-scheduler/issues/438#issuecomment-579199506 
Ref: https://github.com/woocommerce/action-scheduler/issues/436#issuecomment-578978796

**Comment by abhishek-pokhriyal** [comment]
Deadlocks errors caught in the error logs when the following code was in my functions.php

```php
add_filter( 'action_scheduler_async_request_sleep_seconds', function() { return 5; } );
```

Timestamps of errors like the following on my live site:
```
WordPress database error Deadlock found when trying to get lock; try restarting transaction for query UPDATE wp_actionscheduler_actions SET attempts = attempts+1, status='in-progress', last_attempt_gmt = '?', last_attempt_local = '?' WHERE action_id = ?
```

1. [Tue Jan 28 01:34:03.397995 2020]
1. [Tue Jan 28 02:01:11.287185 2020]
1. [Tue Jan 28 03:01:51.943810 2020]
1. [Tue Jan 28 05:32:09.038074 2020]
1. [Tue Jan 28 07:43:13.758270 2020]
1. [Tue Jan 28 09:26:06.491452 2020]
1. [Tue Jan 28 15:45:39.654545 2020]
1. [Tue Jan 28 15:45:40.461459 2020]
1. [Tue Jan 28 15:54:21.981596 2020]
1. [Tue Jan 28 17:10:03.854901 2020]
1. [Tue Jan 28 17:13:23.175276 2020]

**Comment by rrennick** [comment]
@abhishek-pokhriyal Thanks. Can you replace that filter with the one posted in https://github.com/woocommerce/action-scheduler/issues/436#issuecomment-579012904 and see if it clears up the deadlocks?

**Comment by abhishek-pokhriyal** [comment]
Done, @rrennick. I'm monitoring the logs and will share the results after some time.

**Comment by thenbrent** [comment]
As mentioned in https://github.com/woocommerce/action-scheduler/issues/438#issuecomment-579561599, from experience seeing a similar issue with another background processing library that uses loopback requests (like the Async Runner), this is likely caused by only waiting [1 second before initiating a loopback request](https://github.com/woocommerce/action-scheduler/blob/3.0.0/classes/ActionScheduler_AsyncRequest_QueueRunner.php#L90-L95) to [throttle chained processing](https://github.com/woocommerce/action-scheduler/blob/3.0.0/classes/ActionScheduler_AsyncRequest_QueueRunner.php#L54-L60).

If we increase that to 5, we can hopefully continue to provide the higher throughput of chained aysnc processing without causing deadlocks.

**Comment by thenbrent** [comment]
@glagonikas to help confirm my suspicion above, rather than [disabling the async runner](https://github.com/woocommerce/action-scheduler/issues/436#issuecomment-579012904) as [requested here](https://github.com/woocommerce/action-scheduler/issues/438#issuecomment-579255597), could you please increase the sleep time using a snippet like this:

```php
function as_increase_async_request_sleep_time() {
	return 5;
}
add_filter( 'action_scheduler_async_request_sleep_seconds', 'as_increase_async_request_sleep_time' );
```

**Comment by abhishek-pokhriyal** [comment]
I added the following filter to my functions.php at around `2020-01-28 16:50:00 UTC`

```php
add_filter( 'action_scheduler_allow_async_request_runner', '__return_false' );
```

In the time period `Tue Jan 28 16:50 2020` to `Wed Jan 29 14:04:26 2020`, I found three occurrences of the deadlock issue in the error logs:

1. [Tue Jan 28 17:10:03 2020]
1. [Tue Jan 28 17:13:23 2020]
1. [Tue Jan 28 18:22:20 2020]


#### Results after that in case you want to find out some correlation

1. Renewals that were attempted in this period
	```sql
	SELECT
	  `status`, `last_attempt_gmt`
	FROM
	  `wp_actionscheduler_actions`
	WHERE
	  `hook` = 'woocommerce_scheduled_subscription_payment'
	  AND `last_attempt_gmt` >= '2020-01-28 16:50:00'
	  AND `last_attempt_gmt` < '2020-01-29 14:00:00'
	ORDER BY `last_attempt_gmt`;
	```

	| status   | last_attempt_gmt    |
	|----------|---------------------|
	| canceled | 2020-01-28 18:18:15 |
	| **complete** | 2020-01-28 18:51:09 |
	| **complete** | 2020-01-28 19:34:16 |
	| canceled | 2020-01-28 19:34:36 |
	| canceled | 2020-01-28 20:15:16 |
	| canceled | 2020-01-28 21:02:12 |
	| canceled | 2020-01-28 21:04:44 |
	| canceled | 2020-01-28 21:23:58 |
	| canceled | 2020-01-28 21:25:04 |
	| **complete** | 2020-01-28 21:54:10 |
	| **complete** | 2020-01-28 22:44:11 |
	| **complete** | 2020-01-28 23:26:10 |
	| canceled | 2020-01-28 23:38:52 |
	| canceled | 2020-01-29 01:03:06 |
	| canceled | 2020-01-29 01:13:18 |
	| canceled | 2020-01-29 01:31:27 |
	| canceled | 2020-01-29 01:40:10 |
	| canceled | 2020-01-29 01:48:36 |
	| canceled | 2020-01-29 01:54:24 |
	| canceled | 2020-01-29 02:03:51 |
	| canceled | 2020-01-29 02:18:00 |
	| canceled | 2020-01-29 02:27:18 |
	| **complete** | 2020-01-29 02:28:09 |
	| canceled | 2020-01-29 03:20:45 |
	| canceled | 2020-01-29 03:54:46 |
	| canceled | 2020-01-29 04:08:34 |
	| canceled | 2020-01-29 04:14:42 |
	| canceled | 2020-01-29 05:41:07 |
	| canceled | 2020-01-29 07:44:38 |
	| canceled | 2020-01-29 07:45:59 |
	| canceled | 2020-01-29 11:34:22 |

1. What was the status of the actions which were attempted to run in this period-
	```sql
	SELECT
	  `status`, count(*)
	FROM
	  `wp_actionscheduler_actions`
	WHERE
	  `last_attempt_gmt` >= '2020-01-28 16:50:00'
	  AND `last_attempt_gmt` < '2020-01-29 14:00:00'
	GROUP BY
	  `status`;
	```

	| status   | count(*) |
	|----------|----------|
	| canceled |       29 |
	| complete |      791 |

1. The actions that completed in this period with their count.
	```sql
	SELECT
	  `hook`, count(*)
	FROM
	  `wp_actionscheduler_actions`
	WHERE
	  `status` = 'complete'
	  AND `last_attempt_gmt` >= '2020-01-28 16:50:00'
	  AND `last_attempt_gmt` < '2020-01-29 14:00:00'
	GROUP BY
	  `hook`
	ORDER BY
	  count(*) DESC;
	```

	| hook                                                            | count(*) |
	|-----------------------------------------------------------------|----------|
	| wc-admin_import_orders                                          |      484 |
	| woocommerce_deliver_webhook_async                               |      152 |
	| sfn_followup_emails                                             |       51 |
	| wc-admin_import_customers                                       |       49 |
	| wc_admin_unsnooze_admin_notes                                   |       42 |
	| woocommerce_scheduled_subscription_payment                      |        6 |
	| wcs_report_update_cache                                         |        5 |
	| sfn_send_usage_report                                           |        1 |
	| woocommerce_subscriptions_privacy_anonymize_ended_subscriptions |        1 |
     
	**A side question, I'll be highly grateful if anyone can explain this: Follow up emails is deactivated on my site still I see there were 51 actions on the hook `sfn_followup_emails` that ran to completion. How is that even possible? Those should just remain in the pending state. Shouldn't they?**

**Comment by rrennick** [comment]
> Those should just remain in the pending state. Shouldn't they?

No. Action Scheduler doesn't keep track of sources of scheduled actions. It runs the action based on when it's scheduled.

**Comment by abhishek-pokhriyal** [comment]
> It runs the action based on when it's scheduled.

Okay, but when I downgraded WCS from `3.0.1` to `2.5.7`, the scheduled renewal actions didn't complete, until I upgraded WCS back to `3.0.1`. You provided an explanation for that [here](https://github.com/woocommerce/action-scheduler/issues/436#issuecomment-578758531). Wondering why the same thing does not happen when I deactivated follow up (mails are not going but actions move from pending to complete state).

**Comment by rrennick** [comment]
When you switched back to WCS 2.5.7, the actions in the `wp_actionscheduler_*` tables weren't accessible so none of those actions would be run. When you updated back to 3.0.1, they were accessible but still in their `pending` state. Because WCS was active, the renewals were processed properly when the pending actions were processed.

**Comment by glagonikas** [comment]
Hi @thenbrent I left this running without the filter for a few days and the deadlocks kept showing at the rate of 2-3 a day.

I added your filter a couple of days ago, and I've seen just one since then. The filter seems to have helped, but it doesn't fix the issue fully.

**Comment by thenbrent** [comment]
Thanks for confirming @glagonikas.

**Comment by abhishek-pokhriyal** [comment]
@rrennick Since this is closed now, I've 2 questions:

1. My functions files still contain the code you provided me [here](https://github.com/woocommerce/action-scheduler/issues/436#issuecomment-579012904). What should I do with it?
1. I saw the PR that fixes this, does increasing `action_scheduler_async_request_sleep_seconds` from 1 to 5 seconds correctly fix the issue or is it merely a "safe" guess?

**Comment by rrennick** [comment]
> What should I do with it?

You can remove it then monitor your logs.

> does increasing action_scheduler_async_request_sleep_seconds from 1 to 5 seconds correctly fix the issue or is it merely a "safe" guess?

See https://github.com/woocommerce/action-scheduler/issues/441#issuecomment-581244678 for reasoning for the change.
