### ISSUE TITLE
When AS 3.0 migration from 2.0 is run will comments and posts related to AS be removed after migration

### ISSUE THREAD

**Issue by lukecav** [woocommerce/action-scheduler#444]
When the AS 3.0 migration of existing data is run will comments, comment meta, posts and post meta related to AS on older versions be preserved or removed?

**Comment by thenbrent** [comment]
@lukecav existing data is removed from the posts & comment tables after it is migrated to the new tables. Action Scheduler has always had data stores to abstract the database schema, so any interaction with the database should have gone through that abstraction.

Let us know if you've got some integration that is querying data directly using the old schema.

**Comment by lukecav** [comment]
@thenbrent 

Thank you.
