### ISSUE TITLE
Using API helper functions with Composer Autoload

### ISSUE THREAD

**Issue by michaelbourne** [woocommerce/action-scheduler#445]
Howdy,

I'm just in the process of adding this to a plugin via Autoload. I was wondering if there was a recommended method of usage after that (since the docs focus more around including the plugin file directly, and not with composer).

Should I still include the main plugin file? The API functions file? Abstract my own? Access the class directly?

Many ways to make this work, but I was hoping to hear from the source.

Super appreciated.

**Comment by rrennick** [comment]
> Should I still include the main plugin file? 

Yes, you need to include the main plugin file only. That ensures that the latest version of the plugin is the only one active.

**Comment by michaelbourne** [comment]
Thanks for clearing that up. Am I wrong in thinking I can now include this plugin as part of my composer.json setup?

```
  "require": {
    "woocommerce/action-scheduler": "dev-master"
  },
```
```
// load vendor files.
require_once FWCOMMERCE_ROOT . 'vendor/autoload.php';
// load Action Scheduler.
require_once FWCOMMERCE_ROOT . 'vendor/woocommerce/action-scheduler/action-scheduler.php';
```

This is loading the main plugin file. The classes are available. The hooks are registering in Query Monitor. But I still get an error when using the API functions (as per the example code on your site, hooked into init.

`PHP Fatal error:  Uncaught Error: Call to undefined function as_enqueue_async_action()`

**Comment by rrennick** [comment]
> Am I wrong in thinking I can now include this plugin as part of my composer.json setup?

@michaelbourne Yes, you can use composer. Can you give this a try with the latest master?

**Comment by slaFFik** [comment]
@michaelbourne Please read this thread: https://github.com/woocommerce/action-scheduler/issues/463. The last comment (as of now) has the solution.
Basically, you should load AS and only after that vendor. In your code:

```php
// load Action Scheduler.
require_once FWCOMMERCE_ROOT . 'vendor/woocommerce/action-scheduler/action-scheduler.php';
// load vendor files.
require_once FWCOMMERCE_ROOT . 'vendor/autoload.php';
```

**Comment by michaelbourne** [comment]
Awesome, much appreciated.
