### ISSUE TITLE
Action scheduler writing in blog comments

### ISSUE THREAD

**Issue by abhishek-pokhriyal** [woocommerce/action-scheduler#446]
I'm not sure if this is a feature or what but my comments are filled with Action Scheduler data. This looks more like log data.

![image](https://user-images.githubusercontent.com/11808845/73882683-80b02100-4888-11ea-883f-e1bc7c94057c.png)

**Comment by thenbrent** [comment]
@abhishek-pokhriyal if using Action Scheduler 3.0, those comments should have been deleted. They may relate to orphaned comments or some kind of migration failure.

Please read over [this thread](https://github.com/woocommerce/action-scheduler/issues/429) and take the action recommended in [this comment](https://github.com/woocommerce/action-scheduler/issues/429#issuecomment-576713079) to remove the comments.
