### ISSUE TITLE
Fatal errors on activation when embedded in a plugin

### ISSUE THREAD

**Issue by rrennick** [woocommerce/action-scheduler#447]
When Action Scheduler is included in another plugin and that plugin is first activated with WP CLI, it throws some fatal errors. Subsequent activations proceed normally.

```
$ wp plugin activate woocommerce
Plugin 'woocommerce' activated.
Success: Activated 1 of 1 plugins.
Notice: Undefined property: wpdb::$actionscheduler_actions in /Sites/test/wp-includes/wp-db.php on line 659
Notice: Undefined property: wpdb::$actionscheduler_actions in /Sites/test/wp-includes/wp-db.php on line 659
Notice: Undefined property: wpdb::$actionscheduler_actions in /Sites/test/wp-includes/wp-db.php on line 659
Notice: Undefined property: wpdb::$actionscheduler_actions in /Sites/test/wp-includes/wp-db.php on line 659
Notice: Undefined property: wpdb::$actionscheduler_groups in /Sites/test/wp-includes/wp-db.php on line 659
Notice: Undefined property: wpdb::$actionscheduler_groups in /Sites/test/wp-includes/wp-db.php on line 659
Notice: Undefined property: wpdb::$actionscheduler_actions in /Sites/test/wp-includes/wp-db.php on line 659
Fatal error: Uncaught RuntimeException: Error saving action: Error saving action: Incorrect table name '' in /Users/ronrennick/Sites/test/wp-content/plugins/woocommerce/packages/action-scheduler/classes/migration/ActionScheduler_DBStoreMigrator.php:44
```

**Comment by peterfabian** [comment]
This seems to happen also when not using WP CLI on `shutdown` right after activation:

Incorrect table name ''

ActionScheduler_DBStore.php:53, ActionScheduler_DBStoreMigrator->save_action()
ActionScheduler_DBStoreMigrator.php:31, ActionScheduler_DBStoreMigrator->save_action()
ActionScheduler_HybridStore.php:225, ActionScheduler_HybridStore->save_action()
ActionScheduler_ActionFactory.php:177, ActionScheduler_ActionFactory->store()
ActionScheduler_ActionFactory.php:84, ActionScheduler_ActionFactory->single()
functions.php:30, as_schedule_single_action()
Scheduler.php:89, Action_Scheduler\Migration\Scheduler->schedule_migration()
Controller.php:99, Action_Scheduler\Migration\Controller->schedule_migration()
class-wp-hook.php:286, WP_Hook->apply_filters()
class-wp-hook.php:312, WP_Hook->do_action()
plugin.php:478, do_action()
load.php:947, shutdown_action_hook()
load.php:0, {main}()

**Comment by peterfabian** [comment]
Guessing, but maybe because on activation, `init` would not run with `\ActionScheduler_HybridStore::init` hooked into place yet, so the `\ActionScheduler_Abstract_Schema::register_tables` hasn't run before the `shutdown`?

**Comment by claudiosanches** [comment]
@peterfabian yes, seems like `ActionScheduler_Abstract_Schema::register_tables` runs late.

**Comment by claudiosanches** [comment]
@rrennick Need to call `ActionScheduler_Abstract_Schema::register_tables` early, on WooCommerce we set some values for `$wpdb` on `WooCommerce::__construct`, and also we hook into `switch_blog`.

**Comment by claudiosanches** [comment]
Also we can just avoid setting values for `$wpdb`, this should solve any issue like that.
