### ISSUE TITLE
CRITICAL Uncaught Error: Call to undefined method ActionScheduler_DBLogger::unhook_stored_action()

### ISSUE THREAD

**Issue by AngelT91** [woocommerce/action-scheduler#454]
Someone else generates this error the migration

**Comment by rrennick** [comment]
@AngelT91 Thanks for reporting this. Can you provide a list of you active plugins?

**Comment by AngelT91** [comment]
It's all these, thanks for answering I've been trying to correct for two days

AppCommerce
AppLMS
AppPresser
AppPresser sample API code
AppPush
AppWoo
Better 2Checkout for WooCommerce
BuddyBoss Platform
CB Change Mail Sender
Checkout Field Editor for WooCommerce
Elementor
Elementor Pro
Follow-Up Emails
Imsanity
LearnDash LMS
LearnDash LMS - Notifications
Mailster - Email Newsletter Plugin for WordPress
Mailster AmazonSES Integration
Modal Survey
Nav Menu Roles
Podcast API
Podcast COVER
Pods - Custom Content Types and Fields
Posts Table Pro
Really Simple SSL
Vimeotheque PRO
Weight Tracker
Woo - Send Email on Cancelled or Failed Order
WooCommerce
WooCommerce Conditional Payment Methods
WooCommerce Memberships
WooCommerce PayPal Checkout Gateway
WooCommerce Stripe Gateway
WooCommerce Subscriptions
WooCommerce URL Coupons
WooCommerce Western Union Gateway
WP Ultimate Recipe Premium

**Comment by rrennick** [comment]
What version of Follow-Up Emails do you have?

**Comment by AngelT91** [comment]
Is the version 4.8.15

**Comment by rrennick** [comment]
> Is the version 4.8.15

You need to update to the most recent version or deactivate it. Older versions of FUE initialized Action Scheduler incorrectly creating a conflict with AS 3.0.

**Comment by rrennick** [comment]
Closing this. If updating FUE did not resolve this issue please let us know.

**Comment by AngelT91** [comment]
Hi, thank you very much, updating the plugin was the solution

**Comment by dhruvins** [comment]
Hi @rrennick 

Thanks for the information regarding incompatibility with an older version of FUE.

We are using Action Scheduler 3.0 in one of our plugins and one of the user too reported this issue to us but we are checking as to which plugins does he have active on the site. Is there any other way to handle this error? or maybe some way to detect the incompatibilities.

I will share the list of plugins once I receive a response from him.

**Comment by rrennick** [comment]
> or maybe some way to detect the incompatibilities.

@dhruvins If you can search the plugins then look for ones containing action-scheduler. The alternative is doing a conflict test.

**Comment by thenbrent** [comment]
@dhruvins in case it helps, this was the code manually loading the files and causing this in Follow-up Emails:

```php
if ( ! class_exists( 'ActionScheduler_wpCommentLogger' ) ) {
	require_once 'lib/action-scheduler/classes/ActionScheduler_Logger.php';
	require_once 'lib/action-scheduler/classes/ActionScheduler_wpCommentLogger.php';
}
```
