### ISSUE TITLE
[3.0] Actions lost when migrating if `action_scheduler_migration_status` option is already set

### ISSUE THREAD

**Issue by vedanshujain** [woocommerce/action-scheduler#460]
Option `action_scheduler_migration_status` can be set by either updating to 4.0 beta, or more realistically by installing WooCommerce Services plugin which ships AS 3.0.

The problem is, if you have previously installed, but then disabled the WooCommerce Services plugin, the option still remains set, which means that when you upgrade to WC 4.0, all your current actions will lost because AS 3.0 will think that migration is already completed. 

We should perhaps use a different method for checking migration status, like count(post_type = scheduled_action) > 0.

**Comment by rrennick** [comment]
@vedanshujain Thanks for reporting this. We already encountered this when WC Subscriptions  3.0 was released and WooCommerce Memberships had unintentionally shipped a version with the AS 3.0 beta. 

For the affected customers, the happiness team has instructions for deleting the option via the dashboard (which reactivates the migration). From my perspective, based on the number of reports from above, this is an edge case that doesn't warrant adding a frequent query indefinitely to all WC installs. But, I'll leave this open for discussion.

**Comment by peterfabian** [comment]
I _think_ it might be better to check for posts, as there is a default WP `KEY type_status_date (post_type,post_status,post_date,ID),`, it shouldn't be too costly to check. 

Especially since some cleanup actions (`\ActionScheduler_WPCommentCleaner::init`) depend only on this option being set, potentially deleting action logs data?

**Comment by rrennick** [comment]
As an alternative, would deleting the option in the WC 4.0 upgrade routine cover most of the edge cases? If there aren't any actions in the posts table it will be marked as complete again within a couple minutes.

**Comment by vedanshujain** [comment]
Deleting the option in upgrade routine, as well as in plugins activate/deactivate hooks sounds like a good approach to me. Although I would say that since we are shipping AS 3.0 with WC Service for some time now, its probably not an edge case anymore.

**Comment by rrennick** [comment]
Addressed in #470.

**Comment by jaredatch** [comment]
> For the affected customers, the happiness team has instructions for deleting the option via the dashboard (which reactivates the migration). From my perspective, based on the number of reports from above, this is an edge case that doesn't warrant adding a frequent query indefinitely to all WC installs

Just a heads up. WPForms 1.5.9 includes AS 3.1. We've seen this issue come up at least a dozen times that have been reported.

So given we have 3M+ installs, I wouldn't say it's been a huge problem, but there were definitely users caught in the cross fire with this, which is unfortunate and not ideal. Telling customers to delete options is not a people first helpful solution.

I imagine the number of cases will be exponentially greater then this when WC includes AS 3.X, given the odds of those users having previously ran addons that caused this are much higher.

**Comment by thenbrent** [comment]
> Telling customers to delete options is not a people first helpful solution.

@jaredatch ICYMI, that was not the solution chosen to close this.

When a plugin using AS is deactivated, like WPForms, the option is now deleted automatically. For details, see https://github.com/woocommerce/action-scheduler/pull/470/

**Comment by rrennick** [comment]
> When a plugin using AS is deactivated, like WPForms, the option is now deleted automatically.

This was added to version 3.1.1.
