### ISSUE TITLE
ActionScheduler_Action::$args too long

### ISSUE THREAD

**Issue by cahspar** [woocommerce/action-scheduler#465]
Hi,
I'm having a bit of a problem with my current WooCommerce setup. The site used to run fine, no manual changes have been made but just updating plugins and the theme. 

It must have happened with a recent update that my WC orders are not being processed any more. Means: The order gets accepted, the customer sees the confirmation page and the order is logged with a status "pending" in my backend. But from there it's stuck:

* No order confirmation email going out to customer (especially a problem where the customer selected payment in advance and is waiting for bank details now)
* No new order email going to the internal team

 When looking into the order, the following notice shows:

**Error saving action: ActionScheduler_Action::$args too long. To ensure the args column can be indexed, action args should not be more than 191 characters when encoded as JSON.**

Now I've found several issues here that are related to that problem but mainly its developers asking on how they could work around that issue with their plugins. I would like to find out which plugin is causing the problem and wonder if there is a way / log file to look into?

* My WC logs don't show up anything interesting apart from such lines: 

2020-02-17T06:57:48+00:00 ERROR Status transition of order #33885 errored!
2020-02-17T12:36:24+00:00 ERROR Status transition of order #33889 errored!
2020-02-17T12:41:51+00:00 ERROR Status transition of order #33891 errored!
2020-02-17T12:45:23+00:00 ERROR Status transition of order #33893 errored!

* No errors in the server http log
* No errors in the php error log

Would love to make a step forward and maybe one can point me the direction.

Thanks
Christian

**Comment by rrennick** [comment]
@cahspar Download and install version 3.1.0 https://github.com/woocommerce/action-scheduler/releases. You can remove it when you update to WC 4.0.

**Comment by cahspar** [comment]
That worked like a charm! Thank you very much.
