### ISSUE TITLE
Duplicated actions & migration action fail

### ISSUE THREAD

**Issue by cahspar** [woocommerce/action-scheduler#466]
Hi,
I've just manually updated to AS 3.1 after I had problems with order processing on WC 3.9.2 ref. #465.

Indeed I've never looked deeper into AS as it just worked perfectly in the background. Now that I've encountered and fixed that problem with the update, it seems like some actions got duplicated and one job even failed "action_scheduler/migration_hook".

It came to my attention just now and I did not encounter any problems with my site so far. But a failed migration job seems critical to me.

What went wrong? 

Thanks again
Christian

Edit: It is not possible to cancel / delete the duplicated actions from the interface. Clicking the cancel button gives me a 30sec loading time and then nothing has changed.

![failed_migration_job](https://user-images.githubusercontent.com/61154272/74677283-ca193e00-51af-11ea-92a2-3712dd3cd993.JPG)

![duplicated_actions](https://user-images.githubusercontent.com/61154272/74677290-cb4a6b00-51af-11ea-98eb-a54205bc5a27.JPG)

**Comment by rrennick** [comment]
> ref. #465.

You can still comment on closed issues. We can re-open issues if we learn that some related development work needs to be done.

> But a failed migration job seems critical to me.

That's actually not a problem. Depending on how many actions there are in a site there might be 1000+ migration batches. If one of those fails, AS creates a new action pending action to retry / continue.

> Edit: It is not possible to cancel / delete the duplicated actions from the interface.

These work fine in my install. If you need assistance in tracking down the issue in your install and you are a WooCommerce customer, contact support at https://woocommerce.com/contact-us/.
