### ISSUE TITLE
Access action id in action

### ISSUE THREAD

**Issue by tillkruss** [woocommerce/action-scheduler#477]
Is there an easy way to access the action's ID inside the actions callback hook? Similar to `get_the_ID()` but for the action.

**Comment by crstauf** [comment]
@tillkruss Not that I've been able to find, but you could use the AS store to find an action based on the hook and arguments (`ActionScheduler_Store::instance()->find_action( $hook, $args )`).

What are you doing where you want to know the action's ID?

**Comment by tillkruss** [comment]
Maybe setting a global variable using the `action_scheduler_begin_execute` hook?

**Comment by rrennick** [comment]
> Not that I've been able to find

Just confirming this. An action object isn't aware of what its id is in the DB.
