### ISSUE TITLE
Init order

### ISSUE THREAD

**Issue by peterfabian** [woocommerce/action-scheduler#484]
Not an issue, just a question as I was looking at the code today and this comment 

https://github.com/woocommerce/action-scheduler/blob/59dbd87de0c8a826b08142fd122279409dffadf7/classes/abstracts/ActionScheduler.php#L153

got me thinking if the order of init functions is correct?
https://github.com/woocommerce/action-scheduler/blob/59dbd87de0c8a826b08142fd122279409dffadf7/classes/abstracts/ActionScheduler.php#L157-L160

**Comment by rrennick** [comment]
@peterfabian Nice catch.
