### ISSUE TITLE
Uncaught InvalidArgumentException in system status

### ISSUE THREAD

**Issue by peterfabian** [woocommerce/action-scheduler#486]
We have a couple of similar reports where code is complaining about action id not being valid, e.g.

```

2020-03-11T09:58:16+00:00 CRITICAL Uncaught InvalidArgumentException: Ongeïdentificeerde actie 3 in /mnt/web419/b0/82/59534982/htdocs/WordPress_03/wp-content/plugins/woocommerce/packages/action-scheduler/classes/data-stores/ActionScheduler_wpPostStore.php:495
Stack trace:
#0 /mnt/web419/b0/82/59534982/htdocs/WordPress_03/wp-content/plugins/woocommerce/packages/action-scheduler/classes/data-stores/ActionScheduler_wpPostStore.php(482): ActionScheduler_wpPostStore->get_date_gmt('3')
#1 /mnt/web419/b0/82/59534982/htdocs/WordPress_03/wp-content/plugins/woocommerce/packages/action-scheduler/classes/data-stores/ActionScheduler_HybridStore.php(274): ActionScheduler_wpPostStore->get_date('3')
#2 /mnt/web419/b0/82/59534982/htdocs/WordPress_03/wp-content/plugins/woocommerce/packages/action-scheduler/classes/ActionScheduler_wcSystemStatus.php(78): ActionScheduler_HybridStore->get_date('3')
#3 /mnt/web419/b0/82/59534982/htdocs/WordPress_03/wp-content/plugins/woocommerce/packages/action-scheduler/classes/ActionScheduler_wcSystemStatus.php(52): ActionSchedu in /mnt/web419/b0/82/59534982/htdocs/WordPress_03/wp-content/plugins/woocommerce/packages/action-scheduler/classes/data-stores/ActionScheduler_wpPostStore.php op de lijn 495

2020-03-11T10:00:08+00:00 CRITICAL Uncaught InvalidArgumentException: Ongeïdentificeerde actie 3 in /mnt/web419/b0/82/59534982/htdocs/WordPress_03/wp-content/plugins/woocommerce/packages/action-scheduler/classes/data-stores/ActionScheduler_wpPostStore.php:495
Stack trace:
#0 /mnt/web419/b0/82/59534982/htdocs/WordPress_03/wp-content/plugins/woocommerce/packages/action-scheduler/classes/data-stores/ActionScheduler_wpPostStore.php(482): ActionScheduler_wpPostStore->get_date_gmt('3')
#1 /mnt/web419/b0/82/59534982/htdocs/WordPress_03/wp-content/plugins/woocommerce/packages/action-scheduler/classes/data-stores/ActionScheduler_HybridStore.php(274): ActionScheduler_wpPostStore->get_date('3')
#2 /mnt/web419/b0/82/59534982/htdocs/WordPress_03/wp-content/plugins/woocommerce/packages/action-scheduler/classes/ActionScheduler_wcSystemStatus.php(78): ActionScheduler_HybridStore->get_date('3')
#3 /mnt/web419/b0/82/59534982/htdocs/WordPress_03/wp-content/plugins/woocommerce/packages/action-scheduler/classes/ActionScheduler_wcSystemStatus.php(52): ActionSchedu in /mnt/web419/b0/82/59534982/htdocs/WordPress_03/wp-content/plugins/woocommerce/packages/action-scheduler/classes/data-stores/ActionScheduler_wpPostStore.php op de lijn 495

2020-03-11T10:00:23+00:00 CRITICAL Uncaught InvalidArgumentException: Ongeldig actie ID. Geen status gevonden. in /mnt/web419/b0/82/59534982/htdocs/WordPress_03/wp-content/plugins/woocommerce/packages/action-scheduler/classes/data-stores/ActionScheduler_wpPostStore.php:740
Stack trace:
#0 /mnt/web419/b0/82/59534982/htdocs/WordPress_03/wp-content/plugins/woocommerce/packages/action-scheduler/classes/data-stores/ActionScheduler_HybridStore.php(326): ActionScheduler_wpPostStore->get_status('3')
#1 /mnt/web419/b0/82/59534982/htdocs/WordPress_03/wp-content/plugins/woocommerce/packages/action-scheduler/classes/ActionScheduler_ListTable.php(533): ActionScheduler_HybridStore->get_status('3')
#2 /mnt/web419/b0/82/59534982/htdocs/WordPress_03/wp-content/plugins/woocommerce/packages/action-scheduler/classes/abstracts/ActionScheduler_Abstract_ListTable.php(659): ActionScheduler_ListTable->prepare_items()
#3 /mnt/web419/b0/82/59534982/htdocs/WordPress_03/wp-content/plugins/woocommerce/packages/action-scheduler/classes/ActionScheduler_AdminView.php(94): Act in /mnt/web419/b0/82/59534982/htdocs/WordPress_03/wp-content/plugins/woocommerce/packages/action-scheduler/classes/data-stores/ActionScheduler_wpPostStore.php op de lijn 740

2020-03-11T10:02:33+00:00 CRITICAL Uncaught InvalidArgumentException: Ongeïdentificeerde actie 3 in /mnt/web419/b0/82/59534982/htdocs/WordPress_03/wp-content/plugins/woocommerce/packages/action-scheduler/classes/data-stores/ActionScheduler_wpPostStore.php:495
Stack trace:
#0 /mnt/web419/b0/82/59534982/htdocs/WordPress_03/wp-content/plugins/woocommerce/packages/action-scheduler/classes/data-stores/ActionScheduler_wpPostStore.php(482): ActionScheduler_wpPostStore->get_date_gmt('3')
#1 /mnt/web419/b0/82/59534982/htdocs/WordPress_03/wp-content/plugins/woocommerce/packages/action-scheduler/classes/data-stores/ActionScheduler_HybridStore.php(274): ActionScheduler_wpPostStore->get_date('3')
#2 /mnt/web419/b0/82/59534982/htdocs/WordPress_03/wp-content/plugins/woocommerce/packages/action-scheduler/classes/ActionScheduler_wcSystemStatus.php(78): ActionScheduler_HybridStore->get_date('3')
#3 /mnt/web419/b0/82/59534982/htdocs/WordPress_03/wp-content/plugins/woocommerce/packages/action-scheduler/classes/ActionScheduler_wcSystemStatus.php(52): ActionSchedu in /mnt/web419/b0/82/59534982/htdocs/WordPress_03/wp-content/plugins/woocommerce/packages/action-scheduler/classes/data-stores/ActionScheduler_wpPostStore.php op de lijn 495

2020-03-11T10:03:57+00:00 CRITICAL Uncaught InvalidArgumentException: Ongeïdentificeerde actie 177 in /mnt/web419/b0/82/59534982/htdocs/WordPress_03/wp-content/plugins/woocommerce/packages/action-scheduler/classes/data-stores/ActionScheduler_wpPostStore.php:457
Stack trace:
#0 /mnt/web419/b0/82/59534982/htdocs/WordPress_03/wp-content/plugins/woocommerce/packages/action-scheduler/classes/data-stores/ActionScheduler_HybridStore.php(248): ActionScheduler_wpPostStore->cancel_action('177')
#1 /mnt/web419/b0/82/59534982/htdocs/WordPress_03/wp-content/plugins/woocommerce/packages/action-scheduler/classes/abstracts/ActionScheduler_Store.php(290): ActionScheduler_HybridStore->cancel_action('177')
#2 /mnt/web419/b0/82/59534982/htdocs/WordPress_03/wp-content/plugins/woocommerce/packages/action-scheduler/classes/abstracts/ActionScheduler_Store.php(275): ActionScheduler_Store->bulk_cancel_actions(Array)
#3 /mnt/web419/b0/82/59534982/htdocs/WordPress_03/wp-content/plugins/woocommerce/packages/woocommerce-admin/src/Schedulers/SchedulerTraits.php(356): Actio in /mnt/web419/b0/82/59534982/htdocs/WordPress_03/wp-content/plugins/woocommerce/packages/action-scheduler/classes/data-stores/ActionScheduler_wpPostStore.php op de lijn 457

2020-03-11T10:04:10+00:00 CRITICAL Uncaught InvalidArgumentException: Ongeïdentificeerde actie 3 in /mnt/web419/b0/82/59534982/htdocs/WordPress_03/wp-content/plugins/woocommerce/packages/action-scheduler/classes/data-stores/ActionScheduler_wpPostStore.php:495
Stack trace:
#0 /mnt/web419/b0/82/59534982/htdocs/WordPress_03/wp-content/plugins/woocommerce/packages/action-scheduler/classes/data-stores/ActionScheduler_wpPostStore.php(482): ActionScheduler_wpPostStore->get_date_gmt('3')
#1 /mnt/web419/b0/82/59534982/htdocs/WordPress_03/wp-content/plugins/woocommerce/packages/action-scheduler/classes/data-stores/ActionScheduler_HybridStore.php(274): ActionScheduler_wpPostStore->get_date('3')
#2 /mnt/web419/b0/82/59534982/htdocs/WordPress_03/wp-content/plugins/woocommerce/packages/action-scheduler/classes/ActionScheduler_wcSystemStatus.php(78): ActionScheduler_HybridStore->get_date('3')
#3 /mnt/web419/b0/82/59534982/htdocs/WordPress_03/wp-content/plugins/woocommerce/packages/action-scheduler/classes/ActionScheduler_wcSystemStatus.php(52): ActionSchedu in /mnt/web419/b0/82/59534982/htdocs/WordPress_03/wp-content/plugins/woocommerce/packages/action-scheduler/classes/data-stores/ActionScheduler_wpPostStore.php op de lijn 495

```

[report 1](https://wordpress.org/support/topic/fatal-error-in-scheduler/)
[report 2](https://wordpress.org/support/topic/action-scheduler-critical-uncaught-invalidargumentexception/)

What I find a bit perplexing is that (by having a quick look), this code wants to get information about actions with relatively low post ids, which seems suspicious (post id 3 or 2 in these cases).

**Comment by rrennick** [comment]
@peterfabian I believe this was caused by #457. When the two threads were running concurrently one of them succeeded in creating an action before the demarkation ID was set https://github.com/woocommerce/action-scheduler/blob/52bd35581c73c77094b0b2dd4b639e595a009457/classes/data-stores/ActionScheduler_HybridStore.php#L105 which created a handful of actions in the table data store that have IDs below the demarkation ID.

**Comment by jeffstieler** [comment]
@rrennick has the fix in https://github.com/woocommerce/action-scheduler/pull/458 not been shipped, or do we need to reopen #457?

**Comment by rrennick** [comment]
@jeffstieler I have a manual fix that we had used a few sites that experienced it. AFAIK, this is limited to sites that had AS 3.0.X installed that reverted back to pre-3.0. I think we can do an upgrade routine that checks for the presence of these & mitigate through that.

**Comment by streamworksaudio** [comment]
Installed WooCommerce 4.0.1 (the change log shows that the Action Scheduler was updated) however I am still seeing errors with this package.   The log shows...

```
2020-03-21T02:55:17+00:00 CRITICAL Uncaught InvalidArgumentException: Unidentified action 116 in /var/www/html/wp-content/plugins/woocommerce/packages/action-scheduler/classes/data-stores/ActionScheduler_wpPostStore.php:495
Stack trace:
#0 /var/www/html/wp-content/plugins/woocommerce/packages/action-scheduler/classes/data-stores/ActionScheduler_wpPostStore.php(482): ActionScheduler_wpPostStore->get_date_gmt('116')
#1 /var/www/html/wp-content/plugins/woocommerce/packages/action-scheduler/classes/data-stores/ActionScheduler_HybridStore.php(274): ActionScheduler_wpPostStore->get_date('116')
#2 /var/www/html/wp-content/plugins/woocommerce/packages/action-scheduler/classes/ActionScheduler_wcSystemStatus.php(78): ActionScheduler_HybridStore->get_date('116')
#3 /var/www/html/wp-content/plugins/woocommerce/packages/action-scheduler/classes/ActionScheduler_wcSystemStatus.php(52): ActionScheduler_wcSystemStatus->get_action_status_date('pending', 'oldest')
#4 /var/www/html/wp-content/plugins/woocommerce/packages/action-scheduler/classes/ActionScheduler_w in /var/www/html/wp-content/plugins/woocommerce/packages/action-scheduler/classes/data-stores/ActionScheduler_wpPostStore.php on line 495
```

In fact there are some new oddities too.  The scheduled actions tab now shows there are pending actions, but they do not show up in the list.

<img width="1390" alt="Screen Shot 2020-03-21 at 11 59 51 AM" src="https://user-images.githubusercontent.com/20709333/77218142-91340680-6b6b-11ea-9d06-499352c89385.png">

I do have DISABLE_WP_CRON set to true in wp-config.php but I am running php -q /var/www/html/wp-cron.php from the shell and still no change.

**Comment by streamworksaudio** [comment]
I could not get the action scheduler to do anything.  So I deleted all the wp_actionscheduler_ tables in the database and after WooCommerce re-created them, the issue see to have been resolved.  Perhaps during the update the tables were corrupted.

**Comment by StSaens** [comment]
I'm still having this issue on 4.0.1.
(the first post's error code is from my website)

``
> 2020-03-24T13:42:18+00:00 CRITICAL Uncaught InvalidArgumentException: Ongeïdentificeerde actie 221 in /mnt/web419/b0/82/59534982/htdocs/WordPress_03/wp-content/plugins/woocommerce/packages/action-scheduler/classes/data-stores/ActionScheduler_wpPostStore.php:495
> Stack trace:
> #0 /mnt/web419/b0/82/59534982/htdocs/WordPress_03/wp-content/plugins/woocommerce/packages/action-scheduler/classes/data-stores/ActionScheduler_wpPostStore.php(482): ActionScheduler_wpPostStore->get_date_gmt('221')
> #1 /mnt/web419/b0/82/59534982/htdocs/WordPress_03/wp-content/plugins/woocommerce/packages/action-scheduler/classes/data-stores/ActionScheduler_HybridStore.php(274): ActionScheduler_wpPostStore->get_date('221')
> #2 /mnt/web419/b0/82/59534982/htdocs/WordPress_03/wp-content/plugins/woocommerce/packages/action-scheduler/classes/ActionScheduler_wcSystemStatus.php(78): ActionScheduler_HybridStore->get_date('221')
> #3 /mnt/web419/b0/82/59534982/htdocs/WordPress_03/wp-content/plugins/woocommerce/packages/action-scheduler/classes/ActionScheduler_wcSystemStatus.php(52): Acti in /mnt/web419/b0/82/59534982/htdocs/WordPress_03/wp-content/plugins/woocommerce/packages/action-scheduler/classes/data-stores/ActionScheduler_wpPostStore.php op de lijn 495




### WordPress Environment ###

WordPress address (URL): https://xxx.xxx
Site address (URL): https://xxx.xxx
WC Version: 4.0.1
REST API Version: ✔ 1.0.7
WC Blocks Version: ✔ 2.5.14
Action Scheduler Version: ✔ 3.1.4
WC Admin Version: ✔ 1.0.3
Log Directory Writable: ✔
WP Version: 5.3.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: nl_NL
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.41 (Unix)
PHP Version: 7.3.15
PHP Post Max Size: 76 MB
PHP Time Limit: 240
PHP Max Input Vars: 4000
cURL Version: 7.54.0
OpenSSL/1.0.2k

SUHOSIN Installed: –
MySQL Version: 5.6.42-log
Max Upload Size: 64 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 4.0.1
WC Database Prefix: wp_
Totale databasegrootte: 19.57MB
Database datagrootte: 15.35MB
Database index grootte: 4.22MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.09MB + Index: 0.05MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.52MB + Index: 0.53MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_comments: Data: 0.39MB + Index: 0.16MB + Engine MyISAM
wp_duplicator_packages: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_et_social_stats: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_feedmanager_channel: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_feedmanager_country: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_feedmanager_feed_status: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_feedmanager_field_categories: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_feedmanager_product_feed: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_feedmanager_product_feedmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_feedmanager_source: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_links: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_mollie_pending_payment: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_options: Data: 1.30MB + Index: 0.11MB + Engine MyISAM
wp_postmeta: Data: 6.23MB + Index: 1.15MB + Engine MyISAM
wp_posts: Data: 5.11MB + Index: 0.24MB + Engine MyISAM
wp_redirection_404: Data: 0.16MB + Index: 0.11MB + Engine InnoDB
wp_redirection_groups: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_redirection_items: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_redirection_logs: Data: 0.06MB + Index: 0.08MB + Engine InnoDB
wp_smush_dir_images: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.04MB + Engine MyISAM
wp_term_relationships: Data: 0.04MB + Index: 0.09MB + Engine MyISAM
wp_term_taxonomy: Data: 0.03MB + Index: 0.03MB + Engine MyISAM
wp_tm_taskmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_tm_tasks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_usermeta: Data: 0.13MB + Index: 0.09MB + Engine MyISAM
wp_users: Data: 0.01MB + Index: 0.01MB + Engine MyISAM
wp_wcpdf_invoice_number: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wcs_payment_retries: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.05MB + Index: 0.09MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_webwinkelkeur_invite_error: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_yoast_seo_links: Data: 0.09MB + Index: 0.05MB + Engine InnoDB
wp_yoast_seo_meta: Data: 0.20MB + Index: 0.00MB + Engine InnoDB

### Post Type Counts ###

attachment: 648
custom_css: 2
customize_changeset: 2
et_pb_layout: 12
event: 1
nav_menu_item: 18
oembed_cache: 18
page: 54
post: 46
product: 51
product_variation: 69
revision: 260
saswp: 1
schema: 2
shop_coupon: 11
shop_order: 382
shop_order_refund: 11
shop_subscription: 8

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (3) ###

WooCommerce Subscriptions: door WooCommerce – 3.0.2
WooCommerce: door Automattic – 4.0.1
WP Mail SMTP: door WPForms – 1.9.0

### Inactive Plugins (22) ###

Advanced Cron Manager: door BracketSpace – 2.3.10
Autoptimize: door Frank Goossens (futtta) – 2.6.2
Duplicate Post: door Enrico Battocchi – 3.2.4
Duplicator: door Snap Creek – 1.3.28
Google Tag Manager for Wordpress: door Thomas Geiger – 1.11.4
Google XML Sitemaps: door Arne Brachhold – 4.1.0
Kadence WooCommerce Email Designer: door Kadence WP – 1.4.0
Limit Login Attempts: door Johan Eenfeldt – 1.7.1
Mollie Payments for WooCommerce: door Mollie – 5.5.1
Really Simple SSL: door Rogier Lankhorst
Mark Wolters – 3.3

Redirection: door John Godley – 4.7.1
Schema & Structured Data for WP & AMP: door Magazine3 – 1.9.28
Smush: door WPMU DEV – 3.6.1
User Role Editor: door Vladimir Garagulya – 4.53.1
WebwinkelKeur: door Albert Peschar – 1.8 – Niet getest met de actieve versie van WooCommerce
WooCommerce MyParcel: door Adem Demir – 3.2.0 – Niet getest met de actieve versie van WooCommerce
WooCommerce NL Postcode Checker: door Ewout Fernhout – 2.3.1 – Niet getest met de actieve versie van WooCommerce
WooCommerce PDF Invoices & Packing Slips: door Ewout Fernhout – 2.4.7
WP-Optimize - Clean, Compress, Cache: door David Anderson
Ruhani Rabin
Team Updraft – 3.0.16

WP Fastest Cache: door Emre Vona – 0.9.0.4
WP Product Feed Manager: door Michel Jongbloed – 1.20.1
Yoast SEO: door Team Yoast – 13.3

### Must Use Plugins (1) ###

ET Support Center :: Must-Use Plugins Autoloader: door Elegant Themes –

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: EUR (€)
Currency Position: left
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔

### WC Pages ###

Winkelbasis: #28533 - /winkel/
Winkelmand: #28534 - /winkelmand/
Afrekenen: #28535 - /afrekenen/
Mijn account: #28536 - /mijn-account/
Algemene voorwaarden: #31505 - /algemenevoorwaarden/

### Theme ###

Name: Storefront
Version: 2.5.5
Author URL: https://woocommerce.com/
Child Theme: ❌ – Als je wijzigingen aanbrengt in WooCommerce of in een hoofdthema dat je niet zelf gebouwd hebt
raden we het gebruik van een child thema aan. Zie: Hoe maak je een child thema

WooCommerce Support: ✔

### Templates ###

Overrides: –

### Abonnementen ###

WCS_DEBUG: ✔ Nee
Subscriptions Mode: ❌ Staging
Subscriptions Live URL: https://yyy.yyy
Subscription Statuses: wc-active: 2
wc-expired: 2
wc-cancelled: 4

WooCommerce Account Connected: ✔ Yes
Active Product Key: ✔ Yes
Custom Retry Rules: ✔ No
Custom Retry Rule Class: ✔ No
Custom Raw Retry Rule: ✔ No
Custom Retry Rule: ✔ No
Retries Migration Status: ✔ Completed
Report Cache Enabled: ✔ Ja
Cache Update Failures: ✔ 0 failure

### Winkel instellingen ###

Country / State: Nederland

### Subscriptions by Payment Gateway ###

other: wc-active: 1
wc-cancelled: 1
wc-active: 1
wc-cancelled: 3
wc-expired: 2


### Payment Gateway Support ###

Rembours: products
`

**Comment by rrennick** [comment]
@StSaens Can you create a new issue? Add a comment that you have WC 4.0.1 instead of including the system status report. This issue was addressing an issue in the Scheduled Actions screen.

**Comment by DaGenius** [comment]
Please help. I keep getting this error on my woocommerce site "There has been a critical error on your website."

When I checked the error log, here's what I found
`[08-Oct-2020 23:23:35 UTC] WordPress database error Incorrect table definition; there can be only one auto column and it must be defined as a key for query ALTER TABLE wp_xobh_wc_customer_lookup CHANGE COLUMN `customer_id` customer_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT made by require('wp-blog-header.php'), require_once('wp-load.php'), require_once('wp-config.php'), require_once('wp-settings.php'), do_action('init'), WP_Hook->do_action, WP_Hook->apply_filters, Automattic\WooCommerce\Admin\Install::check_version, Automattic\WooCommerce\Admin\Install::install, Automattic\WooCommerce\Admin\Install::create_tables, dbDelta
[08-Oct-2020 23:23:35 UTC] WordPress database error Duplicate entry '14' for key 'PRIMARY' for query ALTER TABLE wp_xobh_wc_customer_lookup ADD PRIMARY KEY  (`customer_id`) made by require('wp-blog-header.php'), require_once('wp-load.php'), require_once('wp-config.php'), require_once('wp-settings.php'), do_action('init'), WP_Hook->do_action, WP_Hook->apply_filters, Automattic\WooCommerce\Admin\Install::check_version, Automattic\WooCommerce\Admin\Install::install, Automattic\WooCommerce\Admin\Install::create_tables, dbDelta
[08-Oct-2020 23:23:35 UTC] WordPress database error Duplicate entry '786' for key 'user_id' for query ALTER TABLE wp_xobh_wc_customer_lookup ADD UNIQUE KEY `user_id` (`user_id`) made by require('wp-blog-header.php'), require_once('wp-load.php'), require_once('wp-config.php'), require_once('wp-settings.php'), do_action('init'), WP_Hook->do_action, WP_Hook->apply_filters, Automattic\WooCommerce\Admin\Install::check_version, Automattic\WooCommerce\Admin\Install::install, Automattic\WooCommerce\Admin\Install::create_tables, dbDelta
[08-Oct-2020 23:23:35 UTC] PHP Fatal error:  Uncaught RuntimeException: Error saving action: Error saving action: Database error. in /home/maracrui/public_html/wp-content/plugins/woocommerce/packages/action-scheduler/classes/migration/ActionScheduler_DBStoreMigrator.php:44
Stack trace:
#0 /home/maracrui/public_html/wp-content/plugins/woocommerce/packages/action-scheduler/classes/data-stores/ActionScheduler_HybridStore.php(242): ActionScheduler_DBStoreMigrator->save_action(Object(ActionScheduler_Action), NULL)
#1 /home/maracrui/public_html/wp-content/plugins/woocommerce/packages/action-scheduler/classes/ActionScheduler_ActionFactory.php(177): ActionScheduler_HybridStore->save_action(Object(ActionScheduler_Action))
#2 /home/maracrui/public_html/wp-content/plugins/woocommerce/packages/action-scheduler/classes/ActionScheduler_ActionFactory.php(84): ActionScheduler_ActionFactory->store(Object(ActionScheduler_Action))
#3 /home/maracrui/public_html/wp-content/plugins/woocommerce/packages/action-scheduler/functions.php(36): ActionScheduler_ActionFactory->single in /home/maracrui/public_html/wp-content/plugins/woocommerce/packages/action-scheduler/classes/migration/ActionScheduler_DBStoreMigrator.php on line 44`
