### ISSUE TITLE
Move source code to /src ❗

### ISSUE THREAD

**Issue by szepeviktor** [woocommerce/action-scheduler#500]
Would you merge a PR that renames /classes to /src like in WooCommerce?

Related: https://github.com/php-stubs/woocommerce-stubs/pull/1

**Comment by rrennick** [comment]
WooCommerce has most of its source code in the `/includes/` folder https://github.com/woocommerce/woocommerce/tree/master/includes

> Related: php-stubs/woocommerce-stubs#1

Any plugin using Action Scheduler as a library should `require` the main plugin file. Accessing any other file in AS directly will create conflicts with other instances of AS.

**Comment by szepeviktor** [comment]
I am running a WC stubs project, see the link above.

All WC packages use the `/src` directory.
Would it be possible to move classes there?

**Comment by rrennick** [comment]
> Would it be possible to move classes there?

I read through the issue in your project. We won't be taking on another code re-org at this time.

**Comment by szepeviktor** [comment]
Thank you for reading that.
