### ISSUE TITLE
action_scheduler_queue_runner_time_limit is not setting time limit.

### ISSUE THREAD

**Issue by raghavtact9** [woocommerce/action-scheduler#501]
I am trying to set the 30 second restriction on this filter. 'action_scheduler_queue_runner_time_limit' . And I am returning an action from my data store with my custom data hook. 

There I put a PHP sleep() method for 90 seconds on that data hook, hoping that it would stop after 30 seconds as I have set the queue runner time limit to 30. But it keeps running, and executed successfully. 

For more info, The max_execution_time set for PHP is 300. But I want to stop the Action on timeout and throw an error. Let me know any solution for this.

**Comment by rrennick** [comment]
> I am trying to set the 30 second restriction on this filter. 'action_scheduler_queue_runner_time_limit' .

The 30 second limit isn't applied to the run time of the individual action hooks. It's applied to the runner (ie. once the time limit is reached AS will stop the queue). So, in your test, if that was the first action, the queue would stop when it completed.

**Comment by raghavtact9** [comment]
Also I am hosting Kinsta as my hosting Provider, and their Max Execution Time is 300. But time limit still is not set to 30. Because it is checking if the limit is under max execution time. then it will return. So runner will now keep running actions till 300 seconds.

**Comment by rrennick** [comment]
@raghavtact9 A max PHP execution time of 300 isn't particularly unusual. The default time limit on the queue runner is [30 seconds](https://github.com/woocommerce/action-scheduler/blob/master/classes/abstracts/ActionScheduler_Abstract_QueueRunner.php#L130). 

If your site is running for 300 then look for code on your site that is using one of the filters below the code I linked to above. I'm not familiar with Kinsta so I can't provide any more detailed suggestions.
