### ISSUE TITLE
Action Scheduler on migration to 4.0.1 acting up

### ISSUE THREAD

**Issue by StSaens** [woocommerce/action-scheduler#502]
Hi.

I just did an upgrade from 3.x to 4.0.1 on my staging and seeing strange things.
What I did
1. made db-export using duplicator
2. copied files from production to staging
3. restored DB on staging
4. disabled all plugins on restoring
5. log into staging and enable Woocommerce, Woocommerce Subscriptions.
6. in scheduled actions I can see the log and pending actions/subscription renewals
7. I update Woocommerce subscriptions to latest version
8. I still see pending scheduled actions
9. I update Woocommerce to 4.0.1 (from 3.9.2)
10. A message in scheduled actions that next queue will process in x seconds
<wait>
11.

_>  Failed action in scheduler:
> woocommerce_run_update_callback:
>     2020-03-24 14:45:53 +0000
>     actie aangemaakt
>     2020-03-24 14:45:53 +0000
>     action started via WP Cron
>     2020-03-24 14:45:53 +0000
>     unexpected shutdown: PHP Fatal error Uncaught Error: Undefined class constant 'QUEUE_GROUP' in /mnt/web419/b0/82/59534982/htdocs/WordPress_03/wp-content/plugins/woocommerce/packages/woocommerce-admin/includes/wc-admin-update-functions.php:70 Stack trace: #0 /mnt/web419/b0/82/59534982/htdocs/WordPress_03/wp-content/plugins/woocommerce/includes/class-wc-install.php(223): wc_admin_update_0251_remove_unsnooze_action() #1 /mnt/web419/b0/82/59534982/htdocs/WordPress_03/wp-includes/class-wp-hook.php(288): WC_Install::run_update_callback('wc_admin_update...') #2 /mnt/web419/b0/82/59534982/htdocs/WordPress_03/wp-includes/class-wp-hook.php(312): WP_Hook->apply_filters('', Array) #3 /mnt/web419/b0/82/59534982/htdocs/WordPress_03/wp-includes/plugin.php(544): WP_Hook->do_action(Array) #4 /mnt/web419/b0/82/59534982/htdocs/WordPress_03/wp-content/plugins/woocommerce/packages/action-scheduler/classes/actions/ActionScheduler_Action.php(22): do_action_ref_array('woocommerce_run...', Array) #5 /mnt/web419/b0/82/59534982/htdocs/WordPress_03/wp-content/plugins/wooco in /mnt/web419/b0/82/59534982/htdocs/WordPress_03/wp-content/plugins/woocommerce/packages/woocommerce-admin/includes/wc-admin-update-functions.php on line 70_

<wait some minutes more>
12. Hit the update database button showing in top of screen

13. "Woocommerce database update in progress"

< wait some more>

14. When I look in the database I can see the update of something with "stock" won't complete and it's stuck there. See attached screenshot.

![update_stock](https://user-images.githubusercontent.com/11319160/77439927-f3993b00-6de7-11ea-8135-76298b76c32c.jpg)

15. When I go to Action Scheduler in WP-admin, it's empty. Message saying a migration is in progress. 

And that's it.

The log in woocommerce shows:

> 2020-03-24T15:02:03+00:00 CRITICAL Uncaught InvalidArgumentException: Ongeïdentificeerde actie 98 in /mnt/web419/b0/82/59534982/htdocs/WordPress_03/wp-content/plugins/woocommerce/packages/action-scheduler/classes/data-stores/ActionScheduler_wpPostStore.php:495
> Stack trace:
> #0 /mnt/web419/b0/82/59534982/htdocs/WordPress_03/wp-content/plugins/woocommerce/packages/action-scheduler/classes/data-stores/ActionScheduler_wpPostStore.php(482): ActionScheduler_wpPostStore->get_date_gmt('98')
> #1 /mnt/web419/b0/82/59534982/htdocs/WordPress_03/wp-content/plugins/woocommerce/packages/action-scheduler/classes/data-stores/ActionScheduler_HybridStore.php(274): ActionScheduler_wpPostStore->get_date('98')
> #2 /mnt/web419/b0/82/59534982/htdocs/WordPress_03/wp-content/plugins/woocommerce/packages/action-scheduler/classes/ActionScheduler_wcSystemStatus.php(78): ActionScheduler_HybridStore->get_date('98')
> #3 /mnt/web419/b0/82/59534982/htdocs/WordPress_03/wp-content/plugins/woocommerce/packages/action-scheduler/classes/ActionScheduler_wcSystemStatus.php(52): ActionSc in /mnt/web419/b0/82/59534982/htdocs/WordPress_03/wp-content/plugins/woocommerce/packages/action-scheduler/classes/data-stores/ActionScheduler_wpPostStore.php op de lijn 495

**Comment by rrennick** [comment]
The initial error is `PHP Fatal error Uncaught Error: Undefined class constant 'QUEUE_GROUP' in /mnt/web419/b0/82/59534982/htdocs/WordPress_03/wp-content/plugins/woocommerce/packages/woocommerce-admin/includes/wc-admin-update-functions.php:70`

That will be addressed in https://github.com/woocommerce/woocommerce-admin/issues/3982. For now you should be able to eliminate the error by reactivating the version of WooCommerce Admin you had active before the WC upgrade.
