### ISSUE TITLE
Callback not called

### ISSUE THREAD

**Issue by picocodes** [woocommerce/action-scheduler#513]
Hello all,

Thanks for this great library. I have an issue though. My callback is not being triggered.

Here is how I registered it:-

```
as_schedule_single_action(
        strtotime( $subscription->expiration ),
        'wpinv_renew_manual_subscription_profile',
        array( $invoice_id ),
        'invoicing'
);
```
The action fires successfully and is marked as complete. However, the `wpinv_renew_manual_subscription_profile` callback is never called.

I know this because I'm logging a message at the top of `wpinv_renew_manual_subscription_profile` but it is not logged. Nothing appears in my error logs too.

Any help on where to check or how to debug will be greatly appreciated.

**Comment by thenbrent** [comment]
> the wpinv_renew_manual_subscription_profile callback is never called.

Action Scheduler is used to scheduled actions / hooks, not callbacks. You need to attach the callback to the scheduled action.

If the callback you want to run is called `wpinv_renew_manual_subscription_profile`, to make sure it's called with the snippet you have above, add this code:

```php
add_action( 'wpinv_renew_manual_subscription_profile', 'wpinv_renew_manual_subscription_profile', 10, 1 );
```

(I'd recommend changing the hook name though, to something like:  `wpinv_trigger_renew_manual_subscription_profile`)
