### ISSUE TITLE
Error adding action with NO_ZERO_DATE

### ISSUE THREAD

**Issue by rrennick** [woocommerce/action-scheduler#519]
This is a follow up issue to #503, #437. My dev install MySQL 5.7 is still configured with

```
sql_mode=STRICT_TRANS_TABLES,NO_ZERO_DATE
```

Using `as_schedule_single_action()` generates the following error

```
[09-Apr-2020 16:27:33 UTC] WordPress database error Incorrect datetime value: '0000-00-00 00:00:00' for column 'last_attempt_gmt' at row 1 for query INSERT INTO `wp_actionscheduler_actions` (`hook`, `status`, `scheduled_date_gmt`, `scheduled_date_local`, `schedule`, `group_id`, `last_attempt_gmt`, `last_attempt_local`, `args`) VALUES ('as-db-test', 'pending', '2020-04-09 17:27:33', '2020-04-09 14:27:33', 'O:30:\"ActionScheduler_SimpleSchedule\":2:{s:22:\"\0*\0scheduled_timestamp\";i:1586453253;s:41:\"\0ActionScheduler_SimpleSchedule\0timestamp\";i:1586453253;}', '0', '0000-00-00 00:00:00', '0000-00-00 00:00:00', '[]')
```

I tested using `1000-01-01 00:00:00` based on https://stackoverflow.com/questions/36374335/error-in-mysql-when-setting-default-value-for-date-or-datetime for both attempt date fields and that eliminated the error.

From https://github.com/woocommerce/action-scheduler/pull/503#issuecomment-606338844

> I'm pretty sure I've seen 0000-00-00 00:00:00 in the posts table before. Maybe for auto-draft posts?

In my install with the Gutenberg editor enabled, an `auto-draft` post isn't created and there are no errors logged when creating a new post.

**Comment by rrennick** [comment]
> In my install with the Gutenberg editor enabled, an auto-draft post isn't created and there are no errors logged when creating a new post.

Correcting this. I had switched databases. These were created when I checked the correct DB. They do have the `0000-00-00 00:00:00` dates in the `gmt` dates so I will investigate this further.

**Comment by AashikP** [comment]
Not sure if this should be posted in https://github.com/woocommerce/woocommerce-admin/issues/4255

Posting it here as the user in 3017746-zen is also on `MySQL 5.7.28-nmm1-log`

Further discussions in p1591264280258300-slack-woo-team-ohana

For now, I'm requesting them to temporarily install [Action Scheduler - Disable Default Queue Runner](https://github.com/woocommerce/action-scheduler-disable-default-runner) plugin, and see how it goes.

**Comment by rrennick** [comment]
> Not sure if this should be posted in woocommerce/woocommerce-admin#4255

@AashikP The issue where WC Admin creating the high number of actions was unrelated to this MySQL NO_ZERO_DATE issue. The issue here is investigating a situation where no actions could be created.

**Comment by danieliser** [comment]
So I've been testing this today as I found the issue and found our test servers using `NO_ZERO_DATE` and `NO_ZERO_IN_DATE`.

- I can see 2 `auto-draft` posts that have the `0000-00-00 00:00:00` set for `post_date_gmt`. So $wpdb is able to get them in somehow.
- I can't locally run inserts locally (see below).
```
INSERT INTO wp_posts ( post_title, post_date, post_date_gmt, post_modified, post_modified_gmt ) VALUES ( 'test', '0000-00-00 00:00:00', '0000-00-00 00:00:00', '0000-00-00 00:00:00', '0000-00-00 00:00:00' );
```
Results in `1292 - Incorrect datetime value: '0000-00-00 00:00:00' for column 'post_date' at row 1`

- There are async actions that did run properly with the `0000-00-00 00:00:00` date in the database.
- Again cannot manually insert them even if I copy the export statement for that row and run it.

```
INSERT INTO `wp_actionscheduler_actions`(`action_id`, `hook`, `status`, `scheduled_date_gmt`, `scheduled_date_local`, `args`, `schedule`, `group_id`, `attempts`, `last_attempt_gmt`, `last_attempt_local`, `claim_id`, `extended_args`) VALUES (2, 'pum_analytics_run_aggregator_process', 'complete', '0000-00-00 00:00:00', '0000-00-00 00:00:00', '[\"PUM\\\\Analytics\\\\Aggregator\\\\MacroStats2\",\"schedule_actions\"]', 'O:28:\"ActionScheduler_NullSchedule\":0:{}', 1, 1, '2020-06-06 17:14:00', '2020-06-06 13:14:00', 0, NULL);
```
Results in the same `1292 - Incorrect datetime value: '0000-00-00 00:00:00' for column 'scheduled_date_gmt' at row 1`

Not sure if it's helpful or not, but just to confirm, WP is bypassing those https://github.com/WordPress/WordPress/blob/master/wp-includes/wp-db.php#L855-L878

**Comment by rrennick** [comment]
> Not sure if it's helpful or not, but just to confirm, WP is bypassing those modes

@danieliser Thanks, I'll have a look.
