### ISSUE TITLE
Is Action Scheduler suitable for sending verification email triggered in every user registration?

### ISSUE THREAD

**Issue by dbjpanda** [woocommerce/action-scheduler#531]
I am trying to create a user registration form that sends OTP over Email and SMS and display an OTP screen after the whole process completes.

How can I make the send_mail and send_sms to be in the background? I know it can be done through Ajax directly to reduce the processing time. But I am making this plugin on top of another one. So ajax way is not to fit in my case. I need to complete the whole thing in one PHP process. So I chose action-scheduler that schedules the jobs (send_mail and send_sms), complete the PHP process, and display an OTP screen to the user.

What will happen if 1000 users registered at once? Considering send_email and send_sms takes 10 sec, how much time it will take to send email and SMS to the 1000th user who is last in the queue? Is that user going to get the OTP after 999*10sec? An OTP after 999*10 sec to too much of waiting time. Is it viable for my application?

**Comment by rrennick** [comment]
> How can I make the send_mail and send_sms to be in the background?

Moving this type of process is a common use for Action Scheduler.

> What will happen if 1000 users registered at once?

If you were expecting this volume of registrations you would need to do the same architecture evaluation regardless of the method used for processing in the background. Regardless of how long each transaction takes, once you reach the time length for 1000 transactions, you then have 1000 transactions being processed in the length of one transaction.

**Comment by dbjpanda** [comment]
@rrennick Thank you.  I have one more query. As I said I have to send mail and sms both as soon as the user registers. So should I define both the functionalities in one action hook? Or should I go for two different action hooks for two different tasks?  Which would be faster and efficient?

**Comment by rrennick** [comment]
> I am concerned about why sometimes ActionScheduler takes 3 actions in a queue and sometimes more?

AS only runs actions that are pending where the scheduled date is in the past. For your other questions the answers vary depending on the specifics of the use cases.

**Comment by dbjpanda** [comment]
What does it mean by `The next queue will begin processing in approximately n seconds.` .  Most of the time Actions are created at a time but processed after 30-40 seconds which makes this library unusable for my case.  Can't we start processing of the queue as soon as one action is created?

**Comment by thenbrent** [comment]
By default, Action Scheduler only initiates a loopback request to process a queue on admin requests every 60 seconds. This "lock" or "throttle" can be seen in `ActionScheduler_QueueRunner::maybe_dispatch_async_request()`. 

It is possible to start processing of the queue as soon as one action is created. There is no lock on `ActionScheduler_AsyncRequest_QueueRunner::maybe_dispatch()`, so that could be attached to `shutdown` whenever a new async job is added (via `as_enqueue_async_action()` or `ActionScheduler::factory()->async()`) so that it's run much sooner.

This behaviour was going to be part of the original PR to add async actions, but for all the use cases we had at the time, we didn't require that, so it wasn't added. Especially as it risks taking down sites by running the non-cached queries used by `ActionScheduler::runner()->has_maximum_concurrent_batches()` and `Store::has_pending_actions_due()` whenever an async job is added, which could be _many_ requests.

If you want to submit a patch, we can review it, but please be mindful of what happens when 10,000+ jobs need to be added and run at once.

**Comment by dbjpanda** [comment]
@thenbrent Thank you for a nice clarification. Definitely I will try to provide one patch if I can. But yet I haven't entered deep into the codebase. I just wanted to use its API. 

I have one query. Does Actions Scheduler only start processing the queue when it is in the Admin Context? Does it mean when someone browses the WordPress dashboard then only the processing of actions is triggered? It is hard to believe that. Or there are two different ways where `maybe_dispatch()` is triggered. If you are in admin context actions are processed in an interval of 60 sec. If not in admin context actions are processed asap.

https://github.com/woocommerce/action-scheduler/blob/cffcb29c6e9d2099b03c5de2d0b7b420b79a2559/classes/ActionScheduler_QueueRunner.php#L85-L109

**Comment by rrennick** [comment]
> Does Actions Scheduler only start processing the queue when it is in the Admin Context?

The async runner only runs in the admin context. The cron runner runs on WP Cron and the WP CLI runner can be used adhoc or via a scheduled server cron job.

**Comment by dbjpanda** [comment]
@rrennick Then there is no use of the `async runner` incase someone submits a form from the frontend. They will never get an OTP over email or SMS until and unless one Wordpress admin triggers the queue by manually browsing the WordPress dashboard.

**Comment by rrennick** [comment]
> unless one Wordpress admin triggers the queue by manually browsing the WordPress dashboard.

Yes, the async runner requires someone to be logged into the dashboard but dashboard screens runs ajax requests in the background and loading new (or the same screen) isn't necessary. 

The CRON runner runs every minute. If you are looking to have tasks triggered with less of a delay than that from the front end of the site then AS is probably not going to serve your purpose.

**Comment by thenbrent** [comment]
An important note - the WP Cron runner also uses the async runner to chain processing in multiple loopback requests after it started in the WP Cron requeust.

If WP Cron starts processing a queue, and there are remaining actions once it reaches it process limit (~20 seconds is usually the limit reached), `maybe_dispatch()` will make an async request to run those actions.

**Comment by thenbrent** [comment]
> If you are looking to have tasks triggered with less of a delay than that from the front end of the site then AS is probably not going to serve your purpose.

It could be made to serve this purpose relatively easily with the patch mentioned here: https://github.com/woocommerce/action-scheduler/issues/531#issuecomment-619715263

**Comment by rrennick** [comment]
@dbjpanda I'm closing the issue as the original questions seem to be answered. If you were to decide to submit a PR for triggering the async runner from the front end, please let us know and we will re-open.
