### ISSUE TITLE
Pending Actions not always created for the next renewal

### ISSUE THREAD

**Issue by mdmoore** [woocommerce/action-scheduler#532]
From p1586912865170300-slack-lambda @jorgeatorres and @james-allan recommend that this be created.  

@james-allan Mentions the following: 

> the non-strict comparison is failing because as_next_scheduled_action()  returns true if the action is currently running, that change is relatively new. See this commit https://github.com/woocommerce/action-scheduler/commit/83f8a2a4b8218ec15b2aaf9d572a3c19827e4e2b

**Comment by rrennick** [comment]
@mdmoore Closing this as the discussion referred to creating an issue in a different repo. p1587659738000800-slack
