### ISSUE TITLE
Action Scheduler migration in progress. The list of scheduled actions may be incomplete.

### ISSUE THREAD

**Issue by rahulnrathodkcl** [woocommerce/action-scheduler#534]
The above titled issue occured after upgrading the staged site from woocommerce 3.8.1 to 4.0.1, and now the scheduled task are not getting completed. 

The **"WooCommerce is updating the database in the background. The database update process may take a little while, so please be patient."** message is showed constantly even after waiting for 5-6 hours. 

I have even tried installing action scheduler in form of plugin but the result is same, the scheduled task are not getting executed. The live site is with same hosting provider, with no issues at all.

**The log shows following error :** 

2020-04-25T14:36:49+00:00 CRITICAL Uncaught Error: Class 'ActionScheduler_Store' not found in /opt/bitnami/apps/wordpress/htdocs/dev/wp-content/plugins/woocommerce/includes/libraries/action-scheduler/classes/ActionScheduler.php:20
Stack trace:
#0 /opt/bitnami/apps/wordpress/htdocs/dev/wp-content/plugins/woocommerce/includes/libraries/action-scheduler/classes/ActionScheduler.php(93): ActionScheduler::store()
#1 /opt/bitnami/apps/wordpress/htdocs/dev/wp-content/plugins/woocommerce/includes/libraries/action-scheduler/action-scheduler.php(44): ActionScheduler::init('/opt/bitnami/ap...')
#2 /opt/bitnami/apps/wordpress/htdocs/dev/wp-content/plugins/woocommerce/includes/libraries/action-scheduler/classes/ActionScheduler_Versions.php(59): action_scheduler_initialize_2_dot_2_dot_5()
#3 /opt/bitnami/apps/wordpress/htdocs/dev/wp-includes/class-wp-hook.php(285): ActionScheduler_Versions::initialize_latest_version()
#4 /opt/bitnami/apps/wordpress/htdocs/dev/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters(NULL, Array)
#5 /opt/bitnami/apps/wordpre in /opt/bitnami/apps/wordpress/htdocs/dev/wp-content/plugins/woocommerce/includes/libraries/action-scheduler/classes/ActionScheduler.php on line 20

2020-04-25T14:37:04+00:00 CRITICAL Uncaught Error: Class 'ActionScheduler_Store' not found in /opt/bitnami/apps/wordpress/htdocs/dev/wp-content/plugins/woocommerce/includes/libraries/action-scheduler/classes/ActionScheduler.php:20
Stack trace:
#0 /opt/bitnami/apps/wordpress/htdocs/dev/wp-content/plugins/woocommerce/includes/libraries/action-scheduler/classes/ActionScheduler.php(93): ActionScheduler::store()
#1 /opt/bitnami/apps/wordpress/htdocs/dev/wp-content/plugins/woocommerce/includes/libraries/action-scheduler/action-scheduler.php(44): ActionScheduler::init('/opt/bitnami/ap...')
#2 /opt/bitnami/apps/wordpress/htdocs/dev/wp-content/plugins/woocommerce/includes/libraries/action-scheduler/classes/ActionScheduler_Versions.php(59): action_scheduler_initialize_2_dot_2_dot_5()
#3 /opt/bitnami/apps/wordpress/htdocs/dev/wp-includes/class-wp-hook.php(285): ActionScheduler_Versions::initialize_latest_version()
#4 /opt/bitnami/apps/wordpress/htdocs/dev/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters(NULL, Array)
#5 /opt/bitnami/apps/wordpre in /opt/bitnami/apps/wordpress/htdocs/dev/wp-content/plugins/woocommerce/includes/libraries/action-scheduler/classes/ActionScheduler.php on line 20

**Comment by rahulnrathodkcl** [comment]
So, I have read on some threads that deleting the tables related to action_scheduler solves the problem. So, I deleted action_scheduler related tables, but in vain, still the problem exists.

**Comment by rrennick** [comment]
> So, I deleted action_scheduler related tables, but in vain, still the problem exists.

Did you make a backup of the tables before you deleted them? If so, restore those tables from the backup. Once you have done that, go through conflict testing https://docs.woocommerce.com/document/how-to-test-for-conflicts/.

**Comment by rahulnrathodkcl** [comment]
No I did not make the backup. But this was done, after I staged a site. So, I just deleted the staged stage, and did the same of table deletion again.

The error was shown even if the tables were not deleted.

**Comment by rahulnrathodkcl** [comment]
Regarding conflict testing, will check that. But it does not seem like a conflict, as the website seem to work fine, the only problem is this error is not going away. And the database update related notification is also sitting there on admin panel.

**Comment by jeremynikolic** [comment]
It seems that I am encountering a similar issue. 
I started developing a plugin which integrates ActionScheduler.

The "action_scheduler/migration_hook" seems to never be triggered and there is the same message as described by @rahulnrathodkcl .
Also no other actions are running either, even if they are displayed in the scheduled actions table.

Here is what I've done so far:
- Setup ActionScheduler inside my plugin as explained inside the [Documenation](https://actionscheduler.org/usage/)
- register the package file
`require_once '.../packages/action-scheduler/action-scheduler.php';`
- Registered a recurring action and a single one:
```php
        function test_log_action()
        {
             error_log('hit the job');
        }

        add_action('test_log', [$this, 'test_log_action']);
        add_action('test_log_2', [$this, 'test_log_action']);

        if (as_next_scheduled_action('test_log') === false) {
            as_schedule_recurring_action(time(), MINUTE_IN_SECONDS, 'test_log');
        }

        if (as_next_scheduled_action('test_log_2') === false) {
            as_schedule_single_action(time() + MINUTE_IN_SECONDS, 'test_log_2');
        }
```

Anything I did wrong ?

I've also setup the last version of woocommerce which seems to hang too with the scheduled actions.

**Comment by rrennick** [comment]
@jeremynikolic If you are working in a dev/staging site you may need to run actions manually. WP cron relies on front end traffic to run and the async runner doesn't run in some dev/staging setups.

**Comment by jeremynikolic** [comment]
@rrennick 
Yes I am running on a dev setup. I'll have a look to set it up properly then

I had the impression that ActionScheduler was being triggered by something else than frontend traffic. 
Would there be alternative/solution for low traffic websites ? pinging the site from an external site ?

**Comment by rrennick** [comment]
> Would there be alternative/solution for low traffic websites ?

It would have to be extremely low traffic for cron to not work on live sites. Even if you have indexing disabled in your robots file, usually there are enough rogue bots to trigger cron on an ongoing basis.

AS includes [WP CLI support](https://actionscheduler.org/wp-cli/) which can be set up on a server cron task.

**Comment by rrennick** [comment]
> /woocommerce/includes/libraries/action-scheduler/classes/ActionScheduler.php

Closing this as the original error was being logged by WooCommerce 3.X.
