### ISSUE TITLE
Use date_i18n() on outputs?

### ISSUE THREAD

**Issue by corsonr** [woocommerce/action-scheduler#537]
Just wondering why `date_i18n()` isn't used here https://github.com/woocommerce/action-scheduler/blob/04eb26256455f9ff3c4a2960af14019b88c42da6/classes/ActionScheduler_wcSystemStatus.php#L123 - is that on purpose?

**Comment by rrennick** [comment]
@corsonr Probably for consistency. Most of the date displays in AS are in UTC. `date_i18n()` doesn't support both `$timestamp` and `$gmt` https://developer.wordpress.org/reference/functions/date_i18n/#parameters . Is there a case for changing it?

**Comment by corsonr** [comment]
I guess that I should have emphasized the use of `get_option( 'date_format' )` which is what I had in mind, that's to say having dates displayed using the WP chosen date format

**Comment by rrennick** [comment]
@corsonr I'd be happy to look at a PR.

**Comment by corsonr** [comment]
ok, I'll do one when I find a bit of time

**Comment by crstauf** [comment]
My thoughts:

1. Changing the format of the timestamp on WooCommerce system status would mean that WooCommerce support staff have to interpret many possible formats, and the format may not include potentially helpful values (ex: offset).

2. This makes more sense on the Scheduled Actions table, but even in that context, a readout of `Thursday, December 23rd, 2019 9:00:00 AM UTC` would take a lot more time for a developer to process than `2019-12-23 09:00:00 +0000` does. This would especially crowd the log column, which is already difficult to read depending on screen size.

I do really like the idea of the timestamps being local, but given that the WordPress setting is used primarily to adjust the display of date and times on the front, and the more technical nature of Action Scheduler data, I don't think that is the proper setting to use. Ideally, WordPress allowed for custom inputs in Screen Options, where a user could specify their desired format there.

**Comment by corsonr** [comment]
good point @crstauf

**Comment by rrennick** [comment]
I'll close this with a won't fix.
