### ISSUE TITLE
v.3.1.5

### ISSUE THREAD

**Issue by LGx0** [woocommerce/action-scheduler#540]
Fatal error: Uncaught RuntimeException: Error saving action: Error saving action: Table 'b10850.wp0z_actionscheduler_actions' doesn't exist in /web/htdocs4/szegedicukraszdainfo/home/www/wp-content/plugins/action-scheduler-3.1.5/classes/migration/ActionScheduler_DBStoreMigrator.php:44 Stack trace: #0 /web/htdocs4/szegedicukraszdainfo/home/www/wp-content/plugins/action-scheduler-3.1.5/classes/data-stores/ActionScheduler_HybridStore.php(242): ActionScheduler_DBStoreMigrator->save_action(Object(ActionScheduler_Action), NULL) #1 /web/htdocs4/szegedicukraszdainfo/home/www/wp-content/plugins/action-scheduler-3.1.5/classes/ActionScheduler_ActionFactory.php(177): ActionScheduler_HybridStore->save_action(Object(ActionScheduler_Action)) #2 /web/htdocs4/szegedicukraszdainfo/home/www/wp-content/plugins/action-scheduler-3.1.5/classes/ActionScheduler_ActionFactory.php(84): ActionScheduler_ActionFactory->store(Object(ActionScheduler_Action)) #3 /web/htdocs4/szegedicukraszdainfo/home/www/wp-content/plugins/action-scheduler-3.1.5/functions in /web/htdocs4/szegedicukraszdainfo/home/www/wp-content/plugins/action-scheduler-3.1.5/classes/migration/ActionScheduler_DBStoreMigrator.php on line 44

**Comment by rrennick** [comment]
@LGx0 Can you provide some context?

**Comment by LGx0** [comment]
What do you think?

**Comment by rrennick** [comment]
> What do you think?

The error message says the `wp0z_actionscheduler_actions` doesn't exist. Can you check your database to see whether it exists now?

**Comment by LGx0** [comment]
> The error message says the `wp0z_actionscheduler_actions` doesn't exist. Can you check your database to see whether it exists now?

Doesn't exist, how do I create it?

**Comment by rrennick** [comment]
> Doesn't exist, how do I create it?

If you visit the Tools -> Scheduled Actions screen Action Scheduler will attempt to create the tables. If you still don't see the tables in your database, contact your hosting support to see if they can help you identify what is preventing the tables from being created.

**Comment by LGx0** [comment]
> 
> 
> > Doesn't exist, how do I create it?
> 
> If you visit the Tools -> Scheduled Actions screen Action Scheduler will attempt to create the tables. If you still don't see the tables in your database, contact your hosting support to see if they can help you identify what is preventing the tables from being created.

I can't find anything there, I'll upload and install it, but it gives the error mentioned above.

**Comment by rrennick** [comment]
> I'll upload and install it

Which plugin are you uploading?

**Comment by rrennick** [comment]
Closing for lack of feedback.
