### ISSUE TITLE
Humongous tables

### ISSUE THREAD

**Issue by abhishek-pokhriyal** [woocommerce/action-scheduler#541]
Hey there,

Ever since I upgraded to the new version of the action scheduler (via WCS), the rate of increase in the sizes of the custom tables has really scared me out.

Table                                     | Size              | Rows
---------------------------|-------------|-------------
`actionscheduler_logs`      | `14.3 GB`    | `114256961`
`actionscheduler_actions` | `~24.5 GB` | `38086253`

Is there a way to optimize/free-up this a bit?

**Comment by thenbrent** [comment]
@abhishek-pokhriyal with those sizes, you might be encountering the issues reported previously in #517 and being worked on in https://github.com/woocommerce/woocommerce-admin/issues/4255.

**Comment by abhishek-pokhriyal** [comment]
@thenbrent I went through the thread and it seems like it's related to woocommerce admin. In my case, however, the number of of pending actions looks believable. 

### Pending actions
| hook                                                   | count(*) |
|--------------------------------------------------------|----------|
| sfn_followup_emails                                    |     1027 |
| sfn_send_usage_report                                  |        1 |
| wc_admin_unsnooze_admin_notes                          |        2 |
| wc_customer_order_export_cleanup_exports               |        1 |
| wc_customer_order_export_validate_automations          |        1 |
| wcs_report_update_cache                                |        5 |
| woocommerce_scheduled_subscription_end_of_prepaid_term |        6 |
| woocommerce_scheduled_subscription_payment             |      604 |


However, a large number of actions looks to be completed.

### Complete actions

| hook                                                            | count(*) |
|-----------------------------------------------------------------|----------|
| MailChimp_WooCommerce_Cart_Update                               |    58794 |
| MailChimp_WooCommerce_Process_Coupons_Initial_Sync              |      168 |
| MailChimp_WooCommerce_Process_Orders                            |     6651 |
| MailChimp_WooCommerce_Process_Products                          |       17 |
| MailChimp_WooCommerce_Single_Order                              |    25888 |
| MailChimp_WooCommerce_Single_Product                            |      340 |
| MailChimp_WooCommerce_SingleCoupon                              |      347 |
| MailChimp_WooCommerce_User_Submit                               |     8080 |
| sfn_followup_emails                                             | 37990781 |
| sfn_send_usage_report                                           |       78 |
| wc_admin_unsnooze_admin_notes                                   |     3728 |
| wc_customer_order_export_cleanup_exports                        |       32 |
| wc_customer_order_export_validate_automations                   |       32 |
| wc-admin_import_customers                                       |     7571 |
| wc-admin_import_orders                                          |    27735 |
| wc-admin_queue_batches_report_exporter                          |       86 |
| wcs_report_update_cache                                         |      390 |
| woocommerce_admin_email_report_download_link                    |        6 |
| woocommerce_admin_report_export                                 |      306 |
| woocommerce_deliver_webhook_async                               |     4922 |
| woocommerce_scheduled_subscription_end_of_prepaid_term          |       31 |
| woocommerce_scheduled_subscription_payment                      |     2930 |
| woocommerce_subscriptions_privacy_anonymize_ended_subscriptions |       78 |
| woocommerce_update_marketplace_suggestions                      |        9 |


### Other actions

### Failed actions

| hook                                       | count(*) |
|--------------------------------------------|----------|
| action_scheduler/migration_hook            |      115 |
| MailChimp_WooCommerce_Cart_Update          |     1465 |
| MailChimp_WooCommerce_Process_Orders       |        2 |
| MailChimp_WooCommerce_Process_Products     |        1 |
| MailChimp_WooCommerce_Single_Order         |        3 |
| MailChimp_WooCommerce_Single_Product       |        1 |
| sfn_followup_emails                        |      103 |
| wc_admin_unsnooze_admin_notes              |        2 |
| wcs_report_update_cache                    |        1 |
| woocommerce_deliver_webhook_async          |        9 |
| woocommerce_scheduled_subscription_payment |       52 |


### Canceled actions

| hook                               | count(*) |
|------------------------------------|----------|
| MailChimp_WooCommerce_Cart_Update  |      777 |
| MailChimp_WooCommerce_Single_Order |        1 |
| MailChimp_WooCommerce_SingleCoupon |        1 |
| MailChimp_WooCommerce_User_Submit  |       67 |
| sfn_followup_emails                |        6 |

**Comment by rrennick** [comment]
@abhishek-pokhriyal The `canceled` and `completed` actions are automatically purged after 30 days. Based on your comments related to the migration on other issues, it looks like you may have had multiple copies of some actions. 

You can temporarily shorten the purge period to 15 days with the following filter added to a plugin

```add_filter( 'action_scheduler_retention_period', function( $retention ) {
        return 15 * DAY_IN_SECONDS;
} );
```

Given the number of actions you have it will take a while for the actions to be purged off. You can use Scheduled Actions -> Tools to determine when you only have 15 days of actions. At that point you can decide whether to keep the filter or remove it. Keep in mind that the actions for the subscription renewals will be purged as well.

**Comment by abhishek-pokhriyal** [comment]
Thanks, @rrennick for getting back. I have a few things I wanted to bring to your attention:

> Based on your comments related to the migration on other issues, it looks like you may have had multiple copies of some actions.

Yes, that could be the case.

> The `canceled` and `completed` actions are automatically purged after 30 days.

I just ran the following query and it returned `22717`. I was expecting `0`. Does it mean the purging is not working on my site?

```sql
SELECT count(*)
FROM wp_actionscheduler_actions
WHERE (status = 'canceled'
       OR status = 'completed')
  AND last_attempt_gmt <= '2020-03-31 00:00:00';
```

> You can temporarily shorten the purge period to 15 days with the following filter added to a plugin

There is something missing in the code.

> Keep in mind that the actions for the subscription renewals will be purged as well.

Can this be an issue? I believe the default functionality of AS is to remove it anyways in 30 days. We are just reducing that to 15 days. Or are the subscription renewal actions handled in a different way?

**Comment by abhishek-pokhriyal** [comment]
I also wanted to bring one more thing to your attention, an issue I am facing on my staging site, and was discussing with the WooCommerce support. The source of that issue somehow looked to be connected to this one:

1. It started when I wasn't able to access the WooCommerce status page. I started getting 502.
1. To replicate, I copied my production to staging and we were able to replicate the issue.
1. We then deactivated all the plugins, switched to the Storefront theme, upgraded WooCommerce to the latest version. After that, I couldn't get WooCommerce activated again. I started getting 502 again.
1. In the error logs, the following errors started popping: 
	> WordPress database error MySQL server has gone away for query SELECT a.action_id FROM wp_actionscheduler_actions a WHERE 1=1 AND a.status='canceled' AND a.last_attempt_gmt <= '2020-03-31 11:30:02' ORDER BY a.scheduled_date_gmt ASC LIMIT 0, 20 /* From [mywcstore/wp-cron.php?doing_wp_cron] in [/nas/content/live/mywcstore/wp-content/plugins/woocommerce/packages/action-scheduler/classes/data-stores/ActionScheduler_DBStore.php:410] */ made by do_action_ref_array('action_scheduler_run_queue'), WP_Hook->do_action, WP_Hook->apply_filters, ActionScheduler_QueueRunner->run, ActionScheduler_Abstract_QueueRunner->run_cleanup, ActionScheduler_QueueCleaner->clean, ActionScheduler_QueueCleaner->delete_old_actions, ActionScheduler_DBStore->query_actions 

1. I then manually ran the SQL query mentioned in the error. It executed successfully but took **1 min and 34.34 sec**.
1. I checked with my hosting and they told me that 60 sec is the upper limit. That looked like the reason why we were getting those database errors.


So, I'm hoping that when this purging issue is resolved, that will also fix those 502 issues, and probably some more issues like action getting timed out (#514).

Do let me know if you see any gaps in my understanding.

**Comment by rrennick** [comment]
> That looked like the reason why we were getting those database errors.

That's also why the purge is falling behind. You can give this SQL a try in your staging environment:

```
DELETE lg FROM wp_actionscheduler_logs lg
LEFT JOIN wp_actionscheduler_actions aa
ON aa.action_id = lg.action_id
WHERE aa.status IS 'complete'
AND aa.hook IS 'sfn_followup_emails'

DELETE FROM wp_actionscheduler_actions aa
WHERE aa.status IS 'complete'
AND aa.hook IS 'sfn_followup_emails'
```

That will remove all of the completed actions for Follow Up Emails. If that works in staging then you can refresh staging (so you have a backup) and run the SQL on live when the site is at a low activity time.

**Comment by lkraav** [comment]
@abhishek-pokhriyal from `mywcstore/wp-cron.php?doing_wp_cron` it looks like you haven't moved to server (pref. WP-CLI based) cron yet? You should, esp. when running a subscriptions site.

**Comment by abhishek-pokhriyal** [comment]
@lkraav Is it so? I was under the impression that we've disabled WP Cron and enabled a server-level cron. I also just checked the `wp-config.php` and I could see:

```php
define( 'DISABLE_WP_CRON', true );
```

Does `mywcstore/wp-cron.php?doing_wp_cron` means it's the default WP Cron and not a server-level cron?

**Comment by abhishek-pokhriyal** [comment]
@rrennick I ran the first query with a modification - changed `IS` to `=`.  It's over 10 minutes since I ran this and right now I'm looking at this:

![image](https://user-images.githubusercontent.com/11808845/80814085-df1b4000-8be8-11ea-85fa-42d893034e3c.png)

Not sure if it has hung up or is still running! 🤞

**Comment by abhishek-pokhriyal** [comment]
@rrennick just checking if you have any idea whether the query is computationally feasible or not? It's not one of those that take `2^256 seconds` type, right?

**Comment by rrennick** [comment]
> It's over 20 minutes since I ran this and right now I'm looking at this:

If you were doing it through PHPMyAdmin or similar it probably timed out on the server side and the browser wasn't aware of it.

> I'm looking for some other way to execute it.

You could add `LIMIT 100000` to the end of the query so it only tries to delete 100K records at a time. If that works, use the time that the query took to gauge how many rows you could delete in 10 seconds. Then use that limit to run the query multiple times delete all the records. You want to delete all the logs before deleting any of the actions.

**Comment by abhishek-pokhriyal** [comment]
> You could add `LIMIT 100000` to the end of the query

I tried this:

```sql
DELETE lg FROM wp_actionscheduler_logs lg
LEFT JOIN wp_actionscheduler_actions aa
ON aa.action_id = lg.action_id
WHERE aa.status = 'complete'
AND aa.hook = 'sfn_followup_emails'
LIMIT 10000;
```

But that doesn't seem to be supported `You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'LIMIT 10000' at line 6`.


Using [this StackOverflow answer](https://stackoverflow.com/a/12202674/4725018), I converted the query to this and converted the limited the results to 1.

```sql
DELETE lg
FROM wp_actionscheduler_logs lg
LEFT JOIN
  (SELECT wpaa.action_id
   FROM wp_actionscheduler_actions wpaa
   WHERE wpaa.status = 'complete'
     AND wpaa.hook = 'sfn_followup_emails' LIMIT 1) aa ON aa.action_id = lg.action_id;
```

Even then it seems to be taking forever. Possibly because when left joining, it is going through the complete `wp_actionscheduler_logs` table.

Any other workaround? Anyone?

**Comment by rrennick** [comment]
> Even then it seems to be taking forever.

How long does the following take:
```
SELECT action_id
   FROM wp_actionscheduler_actions
   WHERE status = 'complete'
     AND hook = 'sfn_followup_emails' LIMIT 1
```

**Comment by abhishek-pokhriyal** [comment]
> How long does the following take:

![image](https://user-images.githubusercontent.com/11808845/80827965-2feb6280-8c02-11ea-8621-6e86bfa7325a.png)

**Comment by rrennick** [comment]
Try

```
DELETE lg
FROM wp_actionscheduler_logs 
WHERE action_id IN
  (SELECT action_id
   FROM wp_actionscheduler_actions
   WHERE status = 'complete'
     AND hook = 'sfn_followup_emails' LIMIT 1);
```

**Comment by abhishek-pokhriyal** [comment]
This version of MySQL doesn't yet support 'LIMIT & IN/ALL/ANY/SOME subquery'

**Comment by abhishek-pokhriyal** [comment]
Last resort, I've run the query via command line. Let see if that helps. Otherwise, we'll need to change the approach here, I think.

**Comment by abhishek-pokhriyal** [comment]
Nothing's working guys. I got in touch with the hosting to find if there's a way to execute the query, their response was:

> there is a limit on the packet size that would not be able to be adjusted. The best option is to have this query either run in batcher or in lower number of deletion

If anyone has experience using any of the approaches, please let me know.

**Comment by rrennick** [comment]
> If anyone has experience using any of the approaches, please let me know.

You can move the `LIMIT` to the outer query.

**Comment by abhishek-pokhriyal** [comment]
Thanks, @rrennick for getting back. I'm doing it AJAX and `$wpdb`. Essentially, (I don't like using `IN` due to performance drawbacks but what can I do!)

```php
$actions_table = $wpdb->prefix . 'actionscheduler_actions';
$logs_table    = $wpdb->prefix . 'actionscheduler_logs';
$actions_query = sprintf(
	"
	SELECT	action_id
	FROM	%s
	WHERE	status = 'complete'
		AND hook = 'sfn_followup_emails'
	LIMIT	%s
	",
	$actions_table,
	$limit
);
$action_ids      = $wpdb->get_col( $actions_query );
$ids             = implode( ',', array_map( 'absint', $action_ids ) );


$deleted_logs    = $wpdb->query( "DELETE FROM $logs_table WHERE action_id IN ($ids)" );
$deleted_actions = $wpdb->query( "DELETE FROM $actions_table WHERE action_id IN ($ids)" );
```

- I then keep triggering this PHP code via AJAX calls.
- I have a way in frontend to control the `$limit` and have found it works well for `7000` rows at a time (works weird (stalls) for 8000).
- So far I've cleared some 30 million actions (in 4-5 hours).

**Comment by abhishek-pokhriyal** [comment]
@rrennick Could you suggest an easy way to be sure that the purging is working once I'm done with clearing this out?

**Comment by rrennick** [comment]
> Could you suggest an easy way to be sure that the purging is working

After you have cleared out the bulk of them the 30 days old you'll have to wait until the FUE actions get to be 30 days old again. Once there you can check the count. You had about 38M so it looks like AS may have been keeping up with purging about 1.3M actions per day.

**Comment by abhishek-pokhriyal** [comment]
Hey Ron,

Thanks for all the help with this one! The script has finished its run - all the completed FUE actions and their logs have been cleared out. Sharing below the screenshot of how things are looking now with regards to AS. If you look at entries in the `Oldest Scheduled Date` column, for completed and failed status, it reports actions from February and January, respectively. I believe, due to the 30 days purging feature of AS, there shouldn't be any actions older than April 5, 2020. Do you think there is a need to manually clear some more entries?

![image](https://user-images.githubusercontent.com/11808845/81071269-15670100-8f02-11ea-94bf-581df7f7cf59.png)

**Comment by rrennick** [comment]
Only `Canceled` and `Completed` actions are purged at 30 days. Failed ones aren't removed because you may need the info on those well after 30 days (eg. failed renewal on an annual subscription- it might be 3 months before the customer contacts the site owner).

**Comment by abhishek-pokhriyal** [comment]
That makes sense, my bad I didn't realize it was failed status. Any thoughts on the `Completed` one? Do more actions require manual purging or I can wait a day and it'll get automatically purged?

**Comment by abhishek-pokhriyal** [comment]
Seems like some purging did happen, the oldest `complete` scheduled action changed from `22 Feb, 2020` to `March 10, 2020`. I'm wondering why it is not `April 6, 2020` (today - 30 days). 🤔

![image](https://user-images.githubusercontent.com/11808845/81142472-653eda00-8f8d-11ea-8a45-7b3f1a0a78ac.png)

**Comment by abhishek-pokhriyal** [comment]
Looks like it took some time. Now it's looking good:
![image](https://user-images.githubusercontent.com/11808845/81417592-0afa7080-9169-11ea-8337-33859ee1ba10.png)

I'm going to close this ticket now as the original issue has been resolved. If it's possible for you to help me with one last thing: is it possible to conditionally purge logs and actions of a particular hook in less the default 30 days? The reason being, the follow-up actions grow really quickly. Just have a look at the actions of hook `sfn_followup_emails` (we cleared all the completed once 4 days ago):

status| count(*) 
-------|---------
canceled |	7 
complete	|209967
failed	|103 
pending	| 948

Thanks for all the help you did with this @rrennick!

**Comment by rrennick** [comment]
> is it possible to conditionally purge logs and actions of a particular hook in less the default 30 days? 

No, but I think that may be something we look at for a future release.

**Comment by shoutcloudstudios** [comment]
This is a critical need... this amount of logfile data just brought down one of my server due to disk space. Please consider building something into the plugin to manage this.

**Comment by rrennick** [comment]
@shoutcloudstudios The source issue for this was in the WooCommerce Admin version in WooCommerce 4.0. If you update to the latest version of WooCommerce you should not be seeing the large number of actions being created.

**Comment by abhishek-pokhriyal** [comment]
> The source issue for this was in the WooCommerce Admin version in WooCommerce 4.0.

@rrennick Not sure but I think a similar issue is with Follow-up Emails too. I upgraded to `WC 4.1.1 `and FUE to `4.9.1` and cleared all the completed FUE actions. A few days later this is how my FUE actions are looking:
![image](https://user-images.githubusercontent.com/11808845/83769273-47a08580-a69d-11ea-9cc7-ae0bd34e9f4e.png)

The rate at which the new actions are being generated is certainly slow (earlier there were around 50 new FUE complete actions being generated in a minute!).

I'm also seeing duplicate `complete` actions.
![image](https://user-images.githubusercontent.com/11808845/83769484-8e8e7b00-a69d-11ea-8685-3bbd3603cb35.png)

**Comment by rrennick** [comment]
@abhishek-pokhriyal For Follow Up Emails contact support at https://woocommerce.com/contact-us/.
