### ISSUE TITLE
JIT initialize custom data stores instead of "Deprecated: shutdown" notice

### ISSUE THREAD

**Issue by thenbrent** [woocommerce/action-scheduler#545]
Recently, we saw an issue where the `shutdown` hook runs on fatal error, meaning code using AS on the `shutdown` hook could attempt to use data stores even if they weren't initialized, which happens on `init`. For more backstory, see https://github.com/woocommerce/action-scheduler/issues/536.

The approach taken to address this was to deprecate the use of `shutdown` for all AS related functions, see https://github.com/woocommerce/action-scheduler/issues/536.

This is now causing deprecated notices to be thrown across many plugins. It's also imposed additional burden on existing AS users, as they need to figure out other suitable hooks to use for this case. An example is the cache updates Subscriptions does on `'shutdown'` as discussed in woocommerce/woocommerce-subscriptions#3676 (private repo). See also #544, and I expect more to come in the following weeks.

There are likely less heavy handed approaches to address the root issue.

For example, data stores could be initialized on `shutdown` if they weren't successfully initialized earlier. Or going a step further, they could be initialized whenever they are needed, as long as it's after the `init` hook (maintaining backward compatibility).

When asking about this approach in the Subscriptions repo, @rrennick mentioned:

> I didn't test but I expect this would be a problem with the post store.

Given the issue in https://github.com/woocommerce/action-scheduler/issues/536 doesn't exist with the WP post stores, that seems like an acceptable limitation.

**Comment by james-allan** [comment]
One possible issue that @rrennick might have been alluding to [here](https://github.com/woocommerce/woocommerce-subscriptions/issues/3676#issuecomment-624024608), is that 3rd party plugins which hook in to override the AS datastores may not have loaded.

So for example, if an error occurs before plugins loaded is fully complete, and plugin xyz which overrides the custom datastores wasn't loaded - loading the datastores JIT on `shutdown` will cause the incorrect store to be loaded. 

This is a fairly obscure issue, however it might be one worth keeping in mind. From our perspective in WC Subscriptions, this wouldn't be an issue for us because we only hook onto `shutdown` to schedule events for things that happened in the request. If an error happened before plugins were fully loaded, that request is effectively dead and nothing would have happened that is worth recording anyway. 

I can't speak for how other third parties are using `shutdown` though. 

If this is something worth building a fix around, we could look at further changes like: Allow the use of `shutdown`, load the datastores JIT if they haven't - like is suggested above, but throw a `doing_it_wrong()` or similar error if:
   1. The datastores weren't initialised and
   2. We can't reasonably init them knowing that the right store is going to be initialised. ie `'plugins_loaded'` hasn't ran.

In my opinion, it's fairly reasonable that if an error occurs that early in a request that there are going to be APIs which aren't available. So users hooking onto `shutdown` will need to be aware that not everything might have loaded correctly if `shutdown` was triggered by an error so early in the setup.

**Comment by thenbrent** [comment]
> in WC Subscriptions, this wouldn't be an issue for us because we only hook onto shutdown to schedule events for things that happened in the request.

That's an interesting point.

Would it be safe to assume that anything calling AS functions attached to `'shutdown'` shouldn't run when this fatal error occurs? I would say yes. Meaning perhaps AS could just not do anything when it hasn't been initialized properly on `'shutdown'`.

At very least, that isolates any issues with AS not being used to the corner case of an error between `plugins_loaded` and `init`, rather than the current deprecation approach which acts as though it's always bad to use `'shutdown'`, which really it's not.

**Comment by james-allan** [comment]
> Would it be safe to assume that anything calling AS functions attached to 'shutdown' shouldn't run when this fatal error occurs? I would say yes. Meaning perhaps AS could just not do anything when it hasn't been initialized properly on 'shutdown'.

Yeah, that would be my opinion too. If it wasn't initialised by the time `shutdown` runs, throw an error so at least it isn't just silently exiting and do nothing.

**Comment by rrennick** [comment]
> throw an error so at least it isn't just silently exiting and do nothing.

I'm fairly certain either throwing an error or doing nothing would bring back portions of the original issue from Bookings.

> In my opinion, if an error happens later in the request, that's to say after AS has been initialised, I still think it's safe for AS to function without issues.

What if we updated the deprecated logic to check for `did_action( 'init' )` and change it from a deprecated to an unsupported notice? That wouldn't fix the original issue but would eliminate notices where AS was initialized.

**Comment by thenbrent** [comment]
> A similar `did_action( 'init' )` check could be added in shutdown hooks that use as_*. 

Action Scheduler should be the one to manage whether its data stores are initialized. We shouldn't require all plugin developers using AS to know that `'init'` needs to run for API functions to work on `shutdown`. Creating that obligation creates too much potential for 3rd parties to end up _doing it wrong_.

And more importantly, it won't actually change the resultant behaviour in this case as far as I can see.

Here's an example of the behaviour with AS < 3.1.5 reported in #536:

1. `plugins_loaded` triggered
1. AS & Bookings loaded
1. error occurs before `'init'`
1. `'shutdown'` called
1. new error thrown (#516)
1. Result: **Bookings' actions aren't scheduled**.

Here's an example of the behaviour with AS 3.1.5:

1. `plugins_loaded` triggered
1. AS & Bookings loaded
1. error occurs before `'init'`
1. `'shutdown'` called
1. deprecated notice is thrown
1. Result: **Bookings' actions aren't scheduled**.

Here's an example of the behaviour if Bookings changes its code to use a different hook before `'shutdown'`, let's say `'my_pre_shutdown'` on a site with AS > 3.0.0:

1. `plugins_loaded` triggered
1. AS & Bookings loaded
1. error occurs before `'init'`
1. `'my_pre_shutdown'` hook never called
1. Result: **Bookings' actions aren't scheduled**.

Here's an example of the behaviour if Bookings changes its code to check for `did_action( 'init' )` in the method on the `'shutdown'` hook as mentioned above:

1. `plugins_loaded` triggered
1. AS & Bookings loaded
1. error occurs before `'init'`
1. `'shutdown'` called
1. no new error or deprecated notice 🎉 , but
1. Result: **Bookings' actions aren't scheduled**.

Hopefully that illustrates what I was trying to say earlier: even if AS did nothing when the conditions of #536 are encountered, the resulting behaviour will always be the same. So it doesn't make sense to require 3rd parties to change their code.

**Comment by rrennick** [comment]
> Result: Bookings' actions aren't scheduled.

I don't see that it's possible to reliably address this with a custom data store other than Bookings using a different hook.

**Comment by thenbrent** [comment]
Ah OK, I think that's the part I was missing. I assumed AS didn't need to make sure the actions were scheduled. But you're right, because they would have been scheduled in AS < 3.0, and AS doesn't know whether the hooks need to be scheduled in that request (or `'shutdown'` is just being used on every request for a generic hook, so it doesn't matter if one is missed), there is a breaking change there and AS should at least notify the user of that risk.

**Comment by thenbrent** [comment]
I think #546 is the best we're going to get. `ActionScheduler::is_initialized()` is a handy utility and it addresses my concerns about abstracting AS's init logic.

I still wish we could find a way to maintain compatibility for extensions using `'shutdown'` without imposing additional work, but like @rrennick, I don't see that it's possible to do.

@james-allan any bright ideas before we accept the deprecated notice?

**Comment by james-allan** [comment]
>  any bright ideas before we accept the deprecated notice?

Not really. One possible idea would be to create a way for AS to store actions if the datastores haven't been initialised. This would act as a sort of holding area, stored temporarily in a WP core storage mechanism until we have a _"good"_ request where they are moved over to legitimate actions. 

That's pretty extreme though, would require substantial work and refactoring, and very likely to cause further issues. 

> I still wish we could find a way to maintain compatibility for extensions using 'shutdown' without imposing additional work, but like @rrennick, I don't see that it's possible to do.

Just so I've got this right. We're still going with the current approach in #546 right? 

So third parties using `shutdown` is still allowed but if you use it when AS hasn't been initialised, you will get an error. The idea being, third parties like Bookings will need to update their callback to check whether it has been initialised and if it hasn't keep trying until they get a good request (no error before init). The ideal outcome, however, wouldn't require them to make those updates?

**Comment by thenbrent** [comment]
> Just so I've got this right.

Yep exactly what you said after that.

> That's pretty extreme though

That's a good idea. But agreed, while it would work, it's not something we need to pursue. This is only happening in a scenario due to fatal errors. It is fair to _not_ provide handling of it.

**Comment by rrennick** [comment]
> Can i confirm there are currently no issues from using 3.1.5 with the affected plugins (Subscriptions. Bookings etc), apart from the notice on the logs?

The issue with Bookings was a compatibility issue between Bookings and WP Rocket. The next release of Bookings will address that issue. Aside from that and the notices in the log, we have had no reported issues with 3.1.5.

**Comment by glagonikas** [comment]
I'm referring to the
```
PHP Deprecated:  shutdown is <strong>deprecated</strong> since version Action Scheduler 3.0! Use init instead. Action Scheduler function <code>as_next_scheduled_action()</code> should not be used within the WordPress <code>shutdown</code> hook. in /var/www/html/wp-includes/functions.php on line 5088
```
notice we see on our logs.

This was raised on [WCS 3676](https://github.com/woocommerce/woocommerce-subscriptions/issues/3676) and was closed in favour of this issue.

**Comment by rrennick** [comment]
> Can i confirm there are currently no issues from using 3.1.5 with the affected plugins (Subscriptions. Bookings etc), apart from the notice on the logs?

Yes, that's the case.

> I'm referring to this notice we see on our logs

In 3.1.6, there will be a warning logged when `as_*` functions have been called when the data store hasn't been initialized. For WCS, I expect the warning won't be triggered. For the existing version of Bookings that has a Google calendar connected and has WP Rocket, they will see the warning in the error logs.
