### ISSUE TITLE
Fatal Error while clicking on Product Order or WooCommerce link on workpress dashboard

### ISSUE THREAD

**Issue by atifakbar** [woocommerce/action-scheduler#547]
Fatal Error while clicking on Product Order or WooCommerce link on workpress dashboard

**To Reproduce**
1. Go to Wordpress Dashboard '...'
2. Click on wooCommerce or under it Order or Under it Product '....'

Fatal error: Uncaught RuntimeException: Error saving action: Unable to save action. in /homepages/33/d488813334/htdocs/app488813350/wp-content/plugins/woocommerce/includes/libraries/action-scheduler/classes/ActionScheduler_wpPostStore.php:33 Stack trace: #0 /homepages/33/d488813334/htdocs/app488813350/wp-content/plugins/woocommerce/includes/libraries/action-scheduler/classes/ActionScheduler_ActionFactory.php(109): ActionScheduler_wpPostStore->save_action(Object(ActionScheduler_Action)) woocommerce/woocommerce#1 /homepages/33/d488813334/htdocs/app488813350/wp-content/plugins/woocommerce/includes/libraries/action-scheduler/classes/ActionScheduler_ActionFactory.php(59): ActionScheduler_ActionFactory->store(Object(ActionScheduler_Action)) woocommerce/woocommerce#2 /homepages/33/d488813334/htdocs/app488813350/wp-content/plugins/woocommerce/includes/libraries/action-scheduler/functions.php(18): ActionScheduler_ActionFactory->single('woocommerce_upd...', Array, 1588897506, '') woocommerce/woocommerce#3 /homepages/33/d488813334/htdocs/app488813350/wp-content/plugins/woocommerce/includes/queue/clas in /homepages/33/d488813334/htdocs/app488813350/wp-content/plugins/woocommerce/includes/libraries/action-scheduler/classes/ActionScheduler_wpPostStore.php on line 33
There has been a critical error on your website. Please check your site admin email inbox for instructions.

Learn more about debugging in WordPress.

**Comment by rrennick** [comment]
> /wp-content/plugins/woocommerce/includes/libraries/action-scheduler/classes/ActionScheduler_wpPostStore.php

@atifakbar You are running an outdated version (3.X) of WooCommerce. I suggest you update to the latest version. If there is a reason preventing you from doing that then you'll need to look for a conflict. Our guide for that is https://docs.woocommerce.com/document/how-to-test-for-conflicts/.

**Comment by rrennick** [comment]
Closing this for lack of feedback. If there is followup we can re-open if needed.
