### ISSUE TITLE
Action_Scheduler/migration_hook keeps running 

### ISSUE THREAD

**Issue by Alessandro-4EYES** [woocommerce/action-scheduler#548]
Hi,

After an upgrade to woocommerce4.0.1, and also to the dependency Action Scheduler to 3.1.4, I see in the scheduled_actions that the migration_hook keeps running several times / hour.

Some of them are started via Async Request, others by WP-Cron.
They all start and complete, but when it starts, we have some huge lags on the site.

Thanks in advance for feedback!

**Comment by rrennick** [comment]
@Alessandro-4EYES If you have a large number of actions in your install the migration will take some time. You could disable the async runner for the duration of the migration https://actionscheduler.org/version3-0/ (see `I updated to Action Scheduler 3.0+` section).

**Comment by Alessandro-4EYES** [comment]
Well, this is going on for 2 weeks now

**Comment by rrennick** [comment]
> this is going on for 2 weeks now

Try installing 3.1.5 https://github.com/woocommerce/action-scheduler/releases/tag/v3.1.5

**Comment by Alessandro-4EYES** [comment]
I just did disable the async runner and did install Woocommerce update 4.1.0 (which comes with action-scheduler 3.1.5). 
migration_hook did run 5 times now via WP Cron in 20minutes (4 completed, 1 cancelled).

**Comment by rrennick** [comment]
@Alessandro-4EYES did the migration complete?

**Comment by Alessandro-4EYES** [comment]
No. When opening the scheduled actions view I still have the message "Action Scheduler migration in progress. The list of scheduled actions may be incomplete."

And the action_scheduler/migration_hook still runs several times a day.

![image](https://user-images.githubusercontent.com/60977153/81565322-6d39b800-9399-11ea-9a8f-aed767419ab2.png)
Async runner is still disabled in the wp-config.
I also disabled the WP-Cron from WP and enabled it on server level (1 x / hour), but that didn't help.

Strange thing is that it creates 4 x the scheduled action for the migration at the same time.

**Comment by rrennick** [comment]
> Strange thing is that it creates 4 x the scheduled action for the migration at the same time.

AS recurring actions create new actions for each run of the action. Can you check your error logs for an error?

**Comment by Alessandro-4EYES** [comment]
Nothing in the debug logs of WP, and also nothing in the apache error logs.

**Comment by rrennick** [comment]
Can you post the DB tables & Action Scheduler portions of your WooCommerce system status report?

**Comment by Alessandro-4EYES** [comment]
Sure, here it is:

wp_actionscheduler_actions: Data: 0.06MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB

Action Scheduler ###
Complete: 119
Oldest: 2020-05-05 17:28:20 +0200
Newest: 2020-05-12 11:01:20 +0200

Canceled: 16
Oldest: 2020-05-05 20:24:01 +0200
Newest: 2020-05-12 09:30:15 +0200

**Comment by Alessandro-4EYES** [comment]
I also checked any options in the wp_options table, and 0 results were found
`SELECT * FROM wp_options where 'option_name' like '%action_scheduler%'`

**Comment by rrennick** [comment]
Have you been deactivating any plugins?

**Comment by Alessandro-4EYES** [comment]
We installed Jetpack latelly, but that slowed down the complete site so we decided to uninstall it.
That's all

**Comment by rrennick** [comment]
You can add an option to the database `action_scheduler_migration_status` with a value of `complete`.

**Comment by yasirhilali** [comment]
> You can add an option to the database `action_scheduler_migration_status` with a value of `complete`.

@rrennick can you direct me to a read up on how to add that option to the database? Thanks in advance.

**Comment by rrennick** [comment]
If you are using MySQL command line it would be

`INSERT INTO wp_options (option_name,option_value) VALUES ('action_scheduler_migration_status','complete');`

**Comment by Alessandro-4EYES** [comment]
Hi @rrennick,
FYI, i've change the option in the db yesterday, but the migration_hook did run again today :) 

![image](https://user-images.githubusercontent.com/60977153/81812817-f2060c80-9526-11ea-98af-68c0ae7758c4.png)


![image](https://user-images.githubusercontent.com/60977153/81812495-7efc9600-9526-11ea-90fd-72a96a62ae77.png)

**Comment by rrennick** [comment]
Do you still have the notice?

**Comment by Alessandro-4EYES** [comment]
No. But I still see it in the scheduled actions log. Is that normal?

**Comment by rrennick** [comment]
> Is that normal?

Yes. I'll close the issue as it seems resolved.

**Comment by adevade** [comment]
For future solution seekers: 

As per [this reply in the WordPress support forum](https://wordpress.org/support/topic/error-on-update-to-1-5-9-5-from-1-5-8-2/#post-12577788) I _emptied_ the following option fields in the database: `schema-ActionScheduler_StoreSchema`, `schema-ActionScheduler_LoggerSchema` and `action_scheduler_migration_status`. 

After that the hook ran once again and then it finally stopped.
