### ISSUE TITLE
Fatal Error when WooCommerce is not installed

### ISSUE THREAD

**Issue by inred-froehlich** [woocommerce/action-scheduler#549]
Uncaught Error: Call to undefined function wc_help_tip() in /wp-content/plugins/my-plugin/packages/action-scheduler/classes/ActionScheduler_wcSystemStatus.php:101

**Comment by rrennick** [comment]
@inred-froehlich Thanks for reporting the issue. Can you provide some context for the error? The WC system status screen hooked into a WooCommerce hook and is normally unused when WC is not active.

**Comment by inred-froehlich** [comment]
My plugin also have a system status page like woocommerce.
So i also use this filters.
`
if ( class_exists('ActionScheduler') && ( ! defined( 'DOING_AJAX' ) || false == DOING_AJAX ) )
        {
            $admin_view = ActionScheduler::admin_view();

            add_action( 'my_plugin_admin_status_content_action-scheduler', array( $admin_view, 'render_admin_ui' ) );
            add_action( 'my_plugin_system_status_report', array( $admin_view, 'system_status_report' ) );
            add_filter( 'my_plugin_admin_status_tabs', array( $admin_view, 'register_system_status_tab' ) );
        }
`
Is it possible to make a function exists for the wc_help_tip?
Thank you and best regards

**Comment by rrennick** [comment]
> Is it possible to make a function exists for the wc_help_tip?

You could submit a PR for it.

**Comment by crstauf** [comment]
@rrennick Submitted PR.

**Comment by rrennick** [comment]
Addressed in #572
