### ISSUE TITLE
Prevent recurring actions being delayed by time previous action took to run

### ISSUE THREAD

**Issue by sebszocinski** [woocommerce/action-scheduler#552]
We are having trouble setting an action using `as_schedule_recurring_action` to run each night at the same time (3AM). 

The first night it runs at 3AM and can take up to several minutes (we are generating PDF shipping labels). The following night it will run at 3:05, then 3:10... after several weeks it's now running at 4AM, then 5AM....

We need it to run at 3AM every night regardless of how long the previous action took to run...

Is this a bug? how do we get around this?

**Comment by rrennick** [comment]
> We need it to run at 3AM every night regardless of how long the previous action took to run...

@sebszocinski Use a cron action `as_schedule_cron_action()`. See https://actionscheduler.org/api/

**Comment by sebszocinski** [comment]
Thanks @rrennick. I feel the documentation could really be improved to explain this better... currently it does not clearly differentiate the two types (cron vs schedule).... 

It could also explain the fact that by using the schedule option each day will be offset by the time the action took to run on the previous schedule... 

I feel like this is a crucial "feature" to point out..
