### ISSUE TITLE
get_local_timezone_string() and timezone_abbreviations_list() issues

### ISSUE THREAD

**Issue by menakas** [woocommerce/action-scheduler#553]
In the `get_local_timezone_string()` function, the integer value of [the offset is used](https://github.com/woocommerce/action-scheduler/blob/275d0ba54b1c263dfc62688de2fa9a25a373edf8/classes/abstracts/ActionScheduler_TimezoneHelper.php#L55) to guess a timezone string, which makes it inaccurate for offsets like UTC+5:30

In addition, using `timezone_abbreviations_list()` for guessing the timezone string from the offset value also has some problems. For the timezone of Asia/Kolkata or Asia/Calcutta, this list has an offset of 23400, which is UTC+6.30, but it should be actually 19800(or UTC+5:30). This timezone does not have any daylight savings, so it is puzzling why the offset should be off by an hour. I am not sure how accurate this list is with respect to other timezones.

So, as of now, I get the timezone of UTC+5:00 when settings is UTC+5:30. By changing to float, I shall get UTC+6:30 which is also wrong.

Though, at this point, I see only [a single call to this function](https://github.com/woocommerce/action-scheduler/blob/master/classes/abstracts/ActionScheduler_TimezoneHelper.php#L25-L29) which calls this function only when a timezone string is set, thus avoiding the codepath which has the issue, I am not sure if there may be other calls in future.

I have added a comment to woocommerce/woocommerce#24863 -a PR for fixing the `wc_timezone_string()` on which `get_local_timezone_string()` is based.

**Comment by rrennick** [comment]
Addressed in #562
