### ISSUE TITLE
My WooCommerce has a fatal error, can someone help me with this error?

### ISSUE THREAD

**Issue by Gabriel-BIOS** [woocommerce/action-scheduler#557]
Fatal error: Uncaught RuntimeException: Error saving action: Error saving action: [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Unclosed quotation mark after the character string 'O:30:"ActionScheduler_SimpleSchedule":2:{s:22:"'. in C:\xampp\htdocs\BIOSGarden\wp-content\plugins\woocommerce\packages\action-scheduler\classes\migration\ActionScheduler_DBStoreMigrator.php:44 Stack trace: #0 C:\xampp\htdocs\BIOSGarden\wp-content\plugins\woocommerce\packages\action-scheduler\classes\data-stores\ActionScheduler_HybridStore.php(242): ActionScheduler_DBStoreMigrator->save_action(Object(ActionScheduler_Action), NULL) #1 C:\xampp\htdocs\BIOSGarden\wp-content\plugins\woocommerce\packages\action-scheduler\classes\ActionScheduler_ActionFactory.php(177): ActionScheduler_HybridStore->save_action(Object(ActionScheduler_Action)) #2 C:\xampp\htdocs\BIOSGarden\wp-content\plugins\woocommerce\packages\action-scheduler\classes\ActionScheduler_ActionFactory.php(84): ActionScheduler_ActionFactory->store(Object(ActionScheduler_Action)) #3 in C:\xampp\htdocs\BIOSGarden\wp-content\plugins\woocommerce\packages\action-scheduler\classes\migration\ActionScheduler_DBStoreMigrator.php on line 44

Há um erro crítico no seu site. Verifique seu e-mail para instruções.

**Comment by rrennick** [comment]
@mendizzz The cross section of people using MS SQL and Action Scheduler is probably quite small. You might have better luck finding someone using MS SQL & WordPress on StackExchange or similar whose familiar with that MS SQL error.

**Comment by mendizzz** [comment]
Do you know how I can make a website on wordpress using the database? I've been looking for a while ...

> @mendizzz A seção de pessoas que usam o MS SQL e o Action Scheduler é provavelmente muito pequena. Você pode ter melhor sorte em encontrar alguém usando o MS SQL e WordPress no StackExchange ou similar que esteja familiarizado com esse erro do MS SQL.

**Comment by mendizzz** [comment]
@rrennick Do you know how I can make a website on wordpress using the database? I've been looking for a while ...

**Comment by rrennick** [comment]
@mendizzz I can't offer you much help there. The last version of MS Windows I worked with was 2005 Advanced Server.

**Comment by LGx0** [comment]
`
Fatal error: Uncaught RuntimeException: Hiba Hiba Table 'b10850.wp0z_actionscheduler_actions' doesn't exist feladat mentésekkor feladat mentésekkor in /web/htdocs4/szegedicukraszdainfo/home/www/wp-content/plugins/woocommerce/packages/action-scheduler/classes/migration/ActionScheduler_DBStoreMigrator.php:44 Stack trace: #0 /web/htdocs4/szegedicukraszdainfo/home/www/wp-content/plugins/woocommerce/packages/action-scheduler/classes/data-stores/ActionScheduler_HybridStore.php(242): ActionScheduler_DBStoreMigrator->save_action(Object(ActionScheduler_Action), NULL) #1 /web/htdocs4/szegedicukraszdainfo/home/www/wp-content/plugins/woocommerce/packages/action-scheduler/classes/ActionScheduler_ActionFactory.php(177): ActionScheduler_HybridStore->save_action(Object(ActionScheduler_Action)) #2 /web/htdocs4/szegedicukraszdainfo/home/www/wp-content/plugins/woocommerce/packages/action-scheduler/classes/ActionScheduler_ActionFactory.php(84): ActionScheduler_ActionFactory->store(Object(ActionScheduler_Action)) #3 /web/htdocs4/szegedicukr in /web/htdocs4/szegedicukraszdainfo/home/www/wp-content/plugins/woocommerce/packages/action-scheduler/classes/migration/ActionScheduler_DBStoreMigrator.php on line 44

Súlyos hiba történt a webhelyünkön. Ellenőrizzük az adminisztrátori e-mail címhez tartozó postafiókot a részletekért. `

**Comment by rrennick** [comment]
@LGx0 That's not the same error message and is unrelated to the original issue. The issue you created a few weeks ago was #540. Please provide the feedback I requested on that issue.

**Comment by LGx0** [comment]
> 
> 
> @LGx0 That's not the same error message and is unrelated to the original issue. The issue you created a few weeks ago was #540. Please provide the feedback I requested on that issue.

what do i have to give?

**Comment by JulioNobre** [comment]
Today, after updating several outdated WordPress's plugins, our internal wordpress website started to behave exactly as @mendizzz  reported above.
Tracing our SQL Server database commands using Microsoft SQL Server Profiler I was able to assess that sql command LIMIT clause was causing an exception. Further digging, led me to a conclusion: commands sent database engine are based on MySQL language instead of MsSQL.

**Comment by rrennick** [comment]
> Therefore, it seems the plugin (wp-mail-smtp.php) is sending sql based on MySQL language instead of MSSQL.

@JulioNobre This is the repository for Action Scheduler. If your SMTP plugin is from WordPress.org, you can find a link to the support forum for the plugin on the plugin page.

**Comment by slaFFik** [comment]
@rrennick This is indeed an AS lib issue, not the WP Mail SMTP plugin.

**Comment by JulioNobre** [comment]
Good norming @rrennick.

Last week I've opened a case on **WP Mail STMP** plugin support team and provided them the details of my exception.
Since then, @slaFFik analysed it and told this seems to be a **Action Scheduler** issue.
For further details, please check https://github.com/awesomemotive/WP-Mail-SMTP/issues/73

**Comment by rrennick** [comment]
> Since I am a seasoned SQL Server developer, I may help translating Action Scheduler MySql's queries into T-SQL (MsSql).

@JulioNobre Would you be able to submit a pull request?

**Comment by JulioNobre** [comment]
After replacing **MySQL**'s **LIMIT** clausule by corresponding **SQL Server 2012** (check attached zip changeset file), tracing using **SQL Server Profiler**, I was able to assess that table **wp_actionscheduler_actions** does not exist.

Regarding to **WP ActionScheduler** specific tables, I only have the following ones:

- wp_actionscheduler_claims
- wp_actionscheduler_groups
- wp_actionscheduler_logs

Is there a way to create missing tables ?

Kind regards,

[MySql2MsSql.zip](https://github.com/woocommerce/action-scheduler/files/4781371/MySql2MsSql.zip)

**Comment by ovidiul** [comment]
It could be that the SQL Server 2012 edition does not like the actions table created query, could you try and manually run the query below:

```
SET SESSION sql_mode = '';
CREATE TABLE wp_actionscheduler_actions(
    	action_id BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
    	hook VARCHAR(191) NOT NULL,
    	STATUS VARCHAR(20) NOT NULL,
        scheduled_date_gmt DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
        scheduled_date_local DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
        args VARCHAR(191),
        SCHEDULE LONGTEXT,
        group_id BIGINT(20) UNSIGNED NOT NULL DEFAULT '0',
        attempts INT(11) NOT NULL DEFAULT '0',
        last_attempt_gmt DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
        last_attempt_local DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
        claim_id BIGINT(20) UNSIGNED NOT NULL DEFAULT '0',
        extended_args VARCHAR(8000) DEFAULT NULL,
        PRIMARY KEY(action_id),
        KEY hook(hook(191)),
        KEY
    	STATUS(STATUS),
    	KEY scheduled_date_gmt(scheduled_date_gmt),
    	KEY args(args(191)),
    	KEY group_id(group_id),
    	KEY last_attempt_gmt(last_attempt_gmt),
    	KEY claim_id(claim_id)
)
```

and confirm if it works or the errors received?

**Comment by barryhughes** [comment]
Going to go ahead and close this one.

I realize SQL Server is something that a number of people wish to use with WordPress (hence efforts [like Project Nami)](https://projectnami.org/), but WordPress itself does **not** directly support it—officially, it only supports MySQL and MariaDB—and, of course, Action Scheduler in turn is built for WordPress.
