### ISSUE TITLE
\ActionScheduler_StoreSchema::get_table_definition() is not mutlisite compatible

### ISSUE THREAD

**Issue by phylogram** [woocommerce/action-scheduler#558]
Using woocommerce action-scheduler in multisite-mode leads to following error notice and fatal php error (it is cut from nano, but I guess it shows enough information):
`[< a date >] WordPress-Datenbank-Fehler Table 'ngojobseu.wp_3_actionscheduler_actions' doesn't exist f  r Abfrage SELECT a.action_id FROM wp_3_actionscheduler_actions a WHERE a.hook='action_schedule$
[< a date >] WordPress-Datenbank-Fehler Table 'ngojobseu.wp_3_actionscheduler_groups' doesn't exist f  r Abfrage SELECT group_id FROM wp_3_actionscheduler_groups WHERE slug='action-scheduler-migrati$
[< a date >] WordPress-Datenbank-Fehler Table 'ngojobseu.wp_3_actionscheduler_groups' doesn't exist f  r Abfrage SHOW FULL COLUMNS FROM `wp_3_actionscheduler_groups` von require_once('wp-admin/admin$
[< a date >] PHP Fatal error:  Uncaught RuntimeException: Error saving action: Error saving action: Table 'ngojobseu.wp_3_actionscheduler_actions' doesn't exist in /www/< a directory :-) >/public/wp-conte$
Stack trace:
#0 /www/< a directory :-) >/public/wp-content/plugins/woocommerce/packages/action-scheduler/classes/data-stores/ActionScheduler_HybridStore.php(242): ActionScheduler_DBStoreMigrator->save_action(Object(ActionScheduler_$
#1 /www/< a directory :-) >/public/wp-content/plugins/woocommerce/packages/action-scheduler/classes/ActionScheduler_ActionFactory.php(177): ActionScheduler_HybridStore->save_action(Object(ActionScheduler_Action))
#2 /www/< a directory :-) >/public/wp-content/plugins/woocommerce/packages/action-scheduler/classes/ActionScheduler_ActionFactory.php(84): ActionScheduler_ActionFactory->store(Object(ActionScheduler_Action))
#3 /www/< a directory :-) >/public/wp-content/plugins/woocommerce/packages/action-scheduler/functions.php(36 in /www/< a directory :-) >/public/wp-content/plugins/woocommerce/packages/action-scheduler/classes/migration/Actio$
`
The reason is, that the tables in `\ActionScheduler_StoreSchema::get_table_definition()` are only created for the main site on multisite.switch_to_blogswitch_to_blog

As far as I understand, the **best** way to currently solve this, is to loop through each blog id, call switch_to_blog()` and do the database creation routine.

Thanks!

**Comment by phylogram** [comment]
Just found in https://actionscheduler.org/faq/ , that it is by choice. However some warning would be nice.

**Comment by rrennick** [comment]
@phylogram Sorry to hear you had an issue in multisite. 

Our unit test suite runs every change set against both single WP and multisite (eg. https://travis-ci.org/github/woocommerce/action-scheduler/builds/657160369).

**Comment by phylogram** [comment]
@phylogram  Thanks – I will have a look at the tests. Maybe I find out there, what you did right and I did wrong. If it is another issue of general concern, I will let you know.

**Comment by phylogram** [comment]
@rrennick I found the issue and a solution. I do not have time now to see if this is covered by your tests, but I guess you will see this in a second:

Issue: First install on multisite works well. In the second (3rd, …) install, the plugin looks up the option in the database blog-agnostic and finds there is no reason for a schema update. Unfortunately, this is for the wrong w-prefix.

My solution (for now) is: Rename the option from: 
`$option_name         = 'schema-' . static::class;`
to:
`$option_name = 'schema-' . get_current_blog_id() . '-' . static::class`
in \ActionScheduler_Abstract_Schema::schema_update_required Line 66.

Maybe this, or something similar is an option for you as well?

Thanks.

**Comment by rrennick** [comment]
> Issue: First install on multisite works well. In the second (3rd, …) install, the plugin looks up the option in the database blog-agnostic and finds there is no reason for a schema update.

@phylogram There is an `_options` table for each site so in normal use in multisite the a different table is checked for each site. You'll need to investigate why `get_option` is using the same set of options for all your sites.

**Comment by phylogram** [comment]
@rrennick 
 After uninstall and reinstall I am not able to reproduce the issue. Sorry to bother you. There must have been some other quirks on our site, though it was a fresh install. Thanks for your time!

**Comment by rrennick** [comment]
@phylogram Good to hear. Thanks for the followup.
