### ISSUE TITLE
Improve "Scheduled Date" for async actions

### ISSUE THREAD

**Issue by crstauf** [woocommerce/action-scheduler#564]
Yesterday I was providing support to a client, and took a look at the Scheduled Actions page, and saw several actions with `0000-00-00 00:00:00` in the _Scheduled Date_ column. Initially I thought something was wrong, but then recalled that particular hook was running asynchronously.

Is it objectionable to change the value of the _Scheduled Date_ column for async actions to something that is not in date format, to make it clear that the action was created as an async action?

Something like "Asynchronous" would be much clearer. Or perhaps just the time that the async action was registered would be clear enough (because actions don't always run at the scheduled time anyway).

**Comment by thenbrent** [comment]
> Is it objectionable to change the value of the Scheduled Date column for async actions to something that is not in date format, to make it clear that the action was created as an async action?

No objections from me. I thought I did include patches to display something like _async_ instead of a zero date, but must have missed it.

**Comment by crstauf** [comment]
Possible client wasn’t using the latest version; I’ll confirm and report back.

**Comment by rrennick** [comment]
The latest version still has the date time. 

> I thought I did include patches to display something like async instead of a zero date, but must have missed it.

`async` would work for me.
