### ISSUE TITLE
Total process for migration? Is it failsafe?

### ISSUE THREAD

**Issue by james-allan** [woocommerce/action-scheduler#566]
The original issue over on WC Subscriptions: https://github.com/woocommerce/woocommerce-subscriptions/issues/3697

From @jonathan-dejong 
> ### Related problem
> Running WP CLI migration of Action scheduler for a site with aloooot of subscriptions. 
The script works great. However it would've been super nice with a periodic "check in" output of how far along the migration process has come. I've ran it for a few hours now and it's not done but I can't tell the client when it'll be done either (for being able to test as soon as migration is complete). 
>
> A separate but related question:
> If the migration command fails due to too long execution time. Is it safe to just restart it and it'll pick up from where it ended? 
Or will it completely restart the process from the beginning?
>
> ### Describe the solution you'd like
> a periodic process notice (possibly at the same time as the memory cleaning notices) that gives you an idea of how far the process has gone.

**Comment by rrennick** [comment]
> If the migration command fails due to too long execution time. Is it safe to just restart it and it'll pick up from where it ended?

@jonathan-dejong The migration picks up where it left off.

> a periodic process notice 

Thanks for the suggestion. Currently the way of ball parking how long the migration will take with WP CLI is take the total number of actions / 100 then multiple that number by how long one cycle (progress bar) of migration takes on your server.

**Comment by barryhughes** [comment]
Closing (for essentially the same reasons [noted here](https://github.com/woocommerce/action-scheduler/issues/577#issuecomment-867839971)—and, similarly, can apply this idea if we make a comparable change in the future).
