### ISSUE TITLE
WooCommerce issues with e-mail marketing tools

### ISSUE THREAD

**Issue by raffor14c** [woocommerce/action-scheduler#571]
Hello guys, 
WooCommerce is driving me mad. I cannot sync e-mail marketing plug-in (such as MailChimp or MailerLite). 

At first, I tought was a MailChimp problem so I contact the support sending them the WooCommerce system status report, Fatal Error Logs and mailchimp_woocommerce logs. They reach be back saying everything looks fine form MailChimp side and the problems is WooCommerce related. 

I tried another e-mail marketing plug-in (MailerLite) and still have the same proble. 

I'm going to attach the some files I send MailChimp support hoping someone can hele me solve this. 

`### WordPress Environment ###

WordPress address (URL): http://calisthenicsprogram.it
Site address (URL): http://calisthenicsprogram.it
WC Version: 4.1.1
REST API Version: ✔ 1.0.7
WC Blocks Version: ✔ 2.5.16
Action Scheduler Version: ✔ 3.1.6
WC Admin Version: ✔ 1.1.3
Log Directory Writable: ✔
WP Version: 5.4.1
WP Multisite: –
WP Memory Limit: 768 MB
WP Debug Mode: –
WP Cron: ✔
Language: it_IT
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.3.16
PHP Post Max Size: 128 MB
PHP Time Limit: 120
PHP Max Input Vars: 3000
cURL Version: 7.59.0
OpenSSL/1.0.2r

SUHOSIN Installed: –
MySQL Version: 5.6.40-84.0-log
Max Upload Size: 128 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.9.3
WC Database Prefix: wp_
Dimensione totale database: 14.44MB
Dimensione dati database: 12.56MB
Dimensione indice database: 1.88MB
wp_woocommerce_sessions: Dati: 0.27MB + indice: 0.02MB + motore InnoDB
wp_woocommerce_api_keys: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
wp_woocommerce_attribute_taxonomies: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wp_woocommerce_downloadable_product_permissions: Dati: 0.02MB + indice: 0.06MB + motore InnoDB
wp_woocommerce_order_items: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wp_woocommerce_order_itemmeta: Dati: 0.06MB + indice: 0.03MB + motore InnoDB
wp_woocommerce_tax_rates: Dati: 0.02MB + indice: 0.06MB + motore InnoDB
wp_woocommerce_tax_rate_locations: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
wp_woocommerce_shipping_zones: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
wp_woocommerce_shipping_zone_locations: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
wp_woocommerce_shipping_zone_methods: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
wp_woocommerce_payment_tokens: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wp_woocommerce_payment_tokenmeta: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
wp_woocommerce_log: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wp_actionscheduler_actions: Dati: 0.17MB + indice: 0.17MB + motore InnoDB
wp_actionscheduler_claims: Dati: 0.06MB + indice: 0.05MB + motore InnoDB
wp_actionscheduler_groups: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wp_actionscheduler_logs: Dati: 0.08MB + indice: 0.06MB + motore InnoDB
wp_aepc_custom_audiences: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
wp_aepc_logs: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
wp_cartflows_ca_cart_abandonment: Dati: 0.11MB + indice: 0.02MB + motore InnoDB
wp_cartflows_ca_email_history: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
wp_cartflows_ca_email_templates: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
wp_cartflows_ca_email_templates_meta: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wp_commentmeta: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
wp_comments: Dati: 0.08MB + indice: 0.09MB + motore InnoDB
wp_edd_customermeta: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
wp_edd_customers: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
wp_links: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wp_mailchimp_carts: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
wp_mailchimp_jobs: Dati: 0.05MB + indice: 0.00MB + motore InnoDB
wp_mailerlite_checkouts: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
wp_options: Dati: 5.03MB + indice: 0.11MB + motore InnoDB
wp_postmeta: Dati: 2.42MB + indice: 0.13MB + motore InnoDB
wp_posts: Dati: 3.39MB + indice: 0.13MB + motore InnoDB
wp_termmeta: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
wp_terms: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
wp_term_relationships: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wp_term_taxonomy: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
wp_usermeta: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
wp_users: Dati: 0.02MB + indice: 0.05MB + motore InnoDB
wp_wc_admin_notes: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
wp_wc_admin_note_actions: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wp_wc_category_lookup: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
wp_wc_customer_lookup: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
wp_wc_download_log: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
wp_wc_order_coupon_lookup: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
wp_wc_order_product_lookup: Dati: 0.02MB + indice: 0.06MB + motore InnoDB
wp_wc_order_stats: Dati: 0.02MB + indice: 0.05MB + motore InnoDB
wp_wc_order_tax_lookup: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
wp_wc_product_meta_lookup: Dati: 0.02MB + indice: 0.09MB + motore InnoDB
wp_wc_tax_rate_classes: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wp_wc_webhooks: Dati: 0.02MB + indice: 0.02MB + motore InnoDB

### Post Type Counts ###

attachment: 260
cartflows_flow: 2
cartflows_step: 4
custom_css: 2
customize_changeset: 6
elementor_library: 50
envato_kits: 38
page: 18
post: 1
product: 5
revision: 283
shop_coupon: 4
shop_order: 160
shop_order_refund: 3

### Security ###

Secure connection (HTTPS): ❌
Il tuo negozio non utilizza HTTPS. Scopri di più su HTTPS e certificati SSL .
Hide errors from visitors: ✔

### Active Plugins (23) ###

CartFlows: by CartFlows Inc – 1.5.9
Elementor Pro: by Elementor.com – 2.9.5
Elementor: by Elementor.com – 2.9.9
Envato Elements: by Envato – 2.0.4
Facebook for WooCommerce: by Facebook – 1.11.3
Google Analytics for WordPress by MonsterInsights: by MonsterInsights – 7.10.4
Hotjar: by Hotjar – 1.0.7
Jetpack by WordPress.com: by Automattic – 8.5
Mailchimp for WooCommerce: by Mailchimp – 2.4.0 – Versione installata non testata con versione attiva di WooCommerce 4.1.1
Ocean Extra: by OceanWP – 1.6.3
Pixel Caffeine: by AdEspresso – 2.1.2 – Versione installata non testata con versione attiva di WooCommerce 4.1.1
SG Optimizer: by SiteGround – 5.5.5
Tidio Chat: by Tidio Ltd. – 4.2.1
UpdraftPlus - Backup/Ripristino: by UpdraftPlus.Com
DavidAnderson – 1.16.25

WooCommerce Cart Abandonment Recovery: by CartFlows Inc – 1.2.6
Checkout Field Editor for WooCommerce: by ThemeHigh – 1.4.2 – Versione installata non testata con versione attiva di WooCommerce 4.1.1
WooCommerce - MailerLite: by MailerLite – 1.4.8
WooCommerce PayPal Checkout Gateway: by WooCommerce – 1.6.21 (aggiornamento alla versione 2.0.1 disponibile) – Versione installata non testata con versione attiva di WooCommerce 4.1.1
WooCommerce Stripe Gateway: by WooCommerce – 4.4.0 – Versione installata non testata con versione attiva di WooCommerce 4.1.1
WooCommerce Services: by Automattic – 1.23.0 – Versione installata non testata con versione attiva di WooCommerce 4.1.1
WooCommerce: by Automattic – 4.1.1
Importatore WordPress: by wordpressdotorg – 0.7
WordPress Starter: by SiteGround – 1.1.1

### Settings ###

API Enabled: –
Force SSL: ✔
Currency: EUR (€)
Currency Position: right
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #889 - /shop/
Carrello: #376 - /carrello/
Cassa: #907 - /checkout-page/
Il mio account: #378 - /mio-account/
Termini e condizioni: ❌ La pagina non è impostata

### Theme ###

Name: Hello Elementor
Version: 2.3.0
Author URL: https://elementor.com/?utm_source=wp-themes&utm_campaign=author-uri&utm_medium=wp-dash
Child Theme: ❌ – Se stai modificando WooCommerce o un tema genitore che non hai costruito personalmente
ti consigliamo di utilizzare un tema child. Vedi: Come creare un tema child

WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

In attesa: 188
Oldest: -0001-11-30 00:00:00 +0000
Newest: 2020-05-27 19:19:56 +0000

Operazione annullata: 417
Oldest: -0001-11-30 00:00:00 +0000
Newest: -0001-11-30 00:00:00 +0000

[Fatal Error log.txt](https://github.com/woocommerce/action-scheduler/files/4723496/Fatal.Error.log.txt)
[MailchimpWooCommerce Log 24-05.txt](https://github.com/woocommerce/action-scheduler/files/4723499/MailchimpWooCommerce.Log.24-05.txt)
[MailchimpWooCommerceLog 25-05.txt](https://github.com/woocommerce/action-scheduler/files/4723500/MailchimpWooCommerceLog.25-05.txt)
[MailchimpWooCommerceLog 26-05.txt](https://github.com/woocommerce/action-scheduler/files/4723501/MailchimpWooCommerceLog.26-05.txt)
[MailchimpWooCommerceLog 27-05.txt](https://github.com/woocommerce/action-scheduler/files/4723502/MailchimpWooCommerceLog.27-05.txt)

**Comment by rrennick** [comment]
> I cannot sync e-mail marketing plug-in 

@raffor14c Can you explain how this is related to Action Scheduler?

**Comment by rrennick** [comment]
Closing for lack of feedback. We can re-open if needed on followup.
