### ISSUE TITLE
Multisite causes huge actionscheduler_logs table

### ISSUE THREAD

**Issue by joebillings** [woocommerce/action-scheduler#576]
Hey all, this is more a general query I guess. I've set up a multisite of cloned sites for a client and in the process have made a direct copy of all the tables (excluding the ones that I know aren't needed) from main to wp_N. 

While I was working on this I noticed a bunch of errors in the error log complaining of missing actionscheduler tables  so I've included them in the clone process but have now noticed that the a wp_N_actionscheduler_logs table is REALLY big. We're talking 950,000+ rows, compared to 15 rows in wp_actionscheduler_logs.

Should I in fact not clone the wp_N_actionscheduler_X tables?

Please help!

**Comment by rrennick** [comment]
@joebillings Sorry to hear you're having an issue with cloning. That sounds like an issue with the cloning process and you should contact support for that plugin.

**Comment by joebillings** [comment]
Hi @rrennick - I'm not using a plugin to do this. Can you let me know if the table is required or whether actionscheduler runs everything through the original tables. I noticed another issue and it seemed to suggest that the error about the missing tables was incorrect. Any help is much appreciated.

**Comment by crstauf** [comment]
@joebillings What’s the version of Action Scheduler?

**Comment by joebillings** [comment]
@crstauf v3.1.6 according to the woo status page.

**Comment by rrennick** [comment]
> Can you let me know if the table is required or whether actionscheduler runs everything through the original tables.

If you are manually copying the site then instead of copying the tables, visit the Tools -> Scheduled Actions screen of the new site.

**Comment by joebillings** [comment]
I'm copying the tables programmatically when a new multisite is created. If I go to the Tools -> Scheduled Actions before cleaning the table of 'action ignored via WP Cron' entries (4m rows today) I get an out of memory error. 

I just deleted all the "ignored" entries and I see this: 

<img width="1019" alt="Screenshot 2020-06-12 at 15 22 46" src="https://user-images.githubusercontent.com/411367/84512940-9d3de900-acc0-11ea-8595-274219828966.png">

Which looks like the async request gets fired and completed but never cleared so goes on creating entries in perpetuity.

In fact, I'm just refreshing the table on a local copy now and it's going up by a few thousand each second. Is there any way I can stop it?

**Comment by joebillings** [comment]
Ok, I manually deleted the entries in wp_5_actionscheduler_actions and it's stopped them from running. They were all marked as complete but I guess something somewhere isn't seeing that they're complete so attempting them again and again.

**Comment by joebillings** [comment]
I'll run some tests by spinning up a new multisite that isn't a clone to see what the difference is. I'm guessing there's an entry somewhere that specifies what site the background process is running on and it's still set to the main site that was cloned. When the background process code checks to see if the process is complete it's probably looking in the main site's actionscheduler table and can't see the process so it gets ignored (x 4 million until a memory limit is hit).

**Comment by rrennick** [comment]
> When the background process code checks to see if the process is complete it's probably looking in the main site's actionscheduler table and can't see the process so it gets ignored

Action Scheduler supports multisite so this wouldn't be the issue unless you have another plugin that is switching the site context in a non-standard way.

If you are copying the tables it would probably be best if the AS tables were empty.

**Comment by joebillings** [comment]
Ah of course - it'll be copying the running processes at the time. I'll copy the tables and clear the data. Thanks for the tip.

**Comment by joebillings** [comment]
FYI - I found the cause of the issue. The constraints on the duplicate wp_wp_download_log table weren't being created because the duplicate wp_32_woocommerce_downloadable_product_permissions table hadn't yet been created. I can now confirm that when the constraints are in place the scheduler behaves as expected. Just in case that helps anyone else :)

**Comment by rrennick** [comment]
@joebillings Thanks for the follow up.

**Comment by alex66210** [comment]
Hi,

I have the same issue andI do not understand how did you fix it.
I recently migrated my website to another hosting domain. After this migration, every time an action is created in action_scheduler_actions, the action_sheduler_logs table is bloating...

Thanks for you reply,

**Comment by alex66210** [comment]
Instead of woocommerce_update_marketplace_suggestions, the action is action_scheduler/migration_hook
Rest is exactly same as above...

**Comment by rrennick** [comment]
@alex66210 The issue you are having isn't related to the issue in the description. Can you create a new issue and include your WooCommerce system status report?

**Comment by alex66210** [comment]
Ok I am going to do it thanks.
