### ISSUE TITLE
[docs] Where to set timeout?

### ISSUE THREAD

**Issue by strarsis** [woocommerce/action-scheduler#583]
The default timeout is 300 seconds (by Action Scheduler).
The VHost supports much longer timeouts, 
how can I change that timeout to something higher, e.g. 600 seconds?
It may also be a good idea to add this to the documentation.

Why not set the Action Scheduler timeout to PHP max execution time?
```php
add_filter( 'action_scheduler_timeout_period', function() {
    $max_execution_time = (int) ini_get('max_execution_time'); // [s]
    return $max_execution_time; 
}
````

**Comment by rrennick** [comment]
> Why not set the Action Scheduler timeout to PHP max execution time?

Some hosting environments are set up where a resource limiting process runs on the server and the PHP execution time setting isn't reliable.

> how can I change that timeout to something higher, e.g. 600 seconds?

See https://actionscheduler.org/perf/

**Comment by strarsis** [comment]
After increasing the timeout, some tasks still time out with the following reason:
````
[...] action timed out after 0 seconds
````
Was the timeout too high and the task runner PHP script terminated without being able to store the soft time out?

**Comment by rrennick** [comment]
@strarsis That's most likely the reason.
