### ISSUE TITLE
Dependent actions

### ISSUE THREAD

**Issue by strarsis** [woocommerce/action-scheduler#584]
How is the Action Scheduler handling task dependencies? 
Will the actions executed in order (when not forced in CLI)?
I have to run three kinds of actions, the first actions fetch WordPress items, 
the third action should then correlate the fetched items (as taxonomy term, product attribute, featured image, etc.).
However, I have to run two full action runs because apparently the order/dependencies are not taken into account,
hence the third action starts before the two other actions, that have to prepare everything, ran or have finished.

**Comment by crstauf** [comment]
@strarsis I believe #205 answers your question.

> By default, they are processed in order of date/time (then ID if more than one is for the same time).

So long as you schedule them in the proper order, AS should maintain that order when executing.

**Comment by strarsis** [comment]
@crstauf: So the group that can be specified is used for better managing the scheduled actions, but has no influence on the execution order?

**Comment by crstauf** [comment]
@strarsis That is my understanding. 

The most functional use of groups I'm aware of is running CLI runners for specific groups: keeping your actions in the same group would ensure they ran in the correct order.

|Hook|Group|Time|
|---|---|---|
|hook_a|group_a|17:00|
|hook_b|group_a|17:00|

With that example if you ran `wp action-scheduler run --group="group_a"`, `hook_a` would run before `hook_b`.

However:

|Hook|Group|Time|
|---|---|---|
|hook_a|group_a|17:00|
|hook_b|group_b|17:00|

In this case, if you ran `wp action-scheduler run --group="group_b"`, then `hook_b` may run before `hook_a`.

There's more info in the [documentation for WP-CLI](https://actionscheduler.org/wp-cli/#cautionary-note-on-action-dependencies-when-using---group-or---hooks-options).

**Comment by strarsis** [comment]
And when just the actions are run without any group specified, then only the order of the actions will matter?

**Comment by crstauf** [comment]
@strarsis Yes, first by scheduled date/time, and secondly by scheduled action ID.

**Comment by strarsis** [comment]
@crstauf: When a scheduled action handler itself schedules new actions, would these actions inherit its priority and run right after the handler action?

**Comment by crstauf** [comment]
@strarsis Based on what you describe in OP, here's a similar situation I'm dealing with, that I think is similar to yours and will hopefully be helpful:

1. Get an array of content IDs
1. Get the content for each ID
1. Publish the new content

I've not started this yet (so it's unproven), but here's what I'm planning to do:

```php
# Schedule the action to get the IDs of new content.
# (This would likely be a recurring action, but for simplicity in this example.)
$timestamp = time() + HOUR_IN_SECONDS;
as_schedule_single_action( $timestamp, 'prefix__get_content_ids', array(), 'prefix_group' );

# Callback to get the content IDs.
add_action( 'prefix__get_content_ids', function() {

    # Get the IDs from endpoint.
    $response = wp_remote_get( 'https://example.com/endpoint' );

    $body = wp_remote_retrieve_body( $response );
    $body = json_decode( $body );

    # Enqueue async actions to get the content for each ID.
    foreach ( $body as $content_id ) {
        as_enqueue_async_action( 'prefix__get_content', array( $content_id ), 'prefix_group' );
    }

    # Enqueue async action to publish the new content.
    as_enqueue_async_action( 'prefix__publish_content', array(), 'prefix_group' );
} );

# Callback for async action to get content.
add_action( 'prefix__get_content', function( $content_id ) {
    $response = wp_remote_get( 'https://example.com/endpoint/' . $content_id );

    $body = wp_remote_retrieve_body( $response );
    $body = json_decode( $body );

    $new_content = get_option( 'prefix__new_content', array() );
    $new_content[] = $body;

    update_option( 'prefix__new_content', $new_content );
} );

# Callback for async action to publish new content.
add_action( 'prefix__publish_content', function() {
    $new_content = get_option( 'prefix__new_content' );
    update_option( 'prefix__published_content', $new_content );
} );
```

There's lots more to actually do (validation, maybe implement counters, etc), but that's the skeleton in my brain.

To directly answer your question:

> would these actions inherit its priority and right after the handler action?

I believe so, only if you enqueue them as async actions (recommended) or scheduled with a datetime in the past. If you schedule an action with the current time, they'll run after actions that were scheduled earlier.

**Comment by strarsis** [comment]
Enqueue them as async actions? Can these also be enqueued as something different? 🐱

**Comment by crstauf** [comment]
> also be enqueued as something different?

@strarsis Can you please provide more detail? At this point, perhaps you should describe in more detail what it is you are trying to do, or start experimenting and see what works and what doesn't.

**Comment by strarsis** [comment]
@crstauf:
> enqueue them as async actions (recommended) or scheduled with a datetime
So scheduled actions without a date/time are called "async actions" and scheduled actions with a date/time in the past/future are considered "scheduled actions"?

**Comment by crstauf** [comment]
> scheduled actions without a date/time are called "async actions"

Technically they're not scheduled, they're enqueued.

> scheduled actions with a date/time in the past/future are considered "scheduled actions"

Yes.

**Comment by strarsis** [comment]
Thanks for the explanation!

The goal:
An API has two endpoints and offers two lists of entities.
Entity A has a field with an ID of entity B.
First, both entities have to be fetched from the API (and modeled as post/term/etc.) and 
then both have to be linked/dereferenced, e.g. by assigning the post to the term.
So first both tasks for fetching the entities have to be completed, only then the third task is allowed to run.

One could devise some more dynamic way, like creating an empty dummy post/term with just the ID and 
then later filling it with content, but this is not always possible in WordPress, e.g. an empty attachment post which 
image is replaced is actually very hard and brittle to implement.

**Comment by crstauf** [comment]
You're welcome! 🙇

**Comment by rrennick** [comment]
@strarsis For that type of dependency you can schedule the second action at the end of the first one as an async action.

**Comment by strarsis** [comment]
@rrennick: Could you give me an example so I can be sure that I really use that approach? :)

**Comment by rrennick** [comment]
> Could you give me an example so I can be sure that I really use that approach? :)

```
as_schedule_single_action( time(), 'first_hook', $args, 'my-group' );
add_action( 'first_hook', function( $args... ) {
// you first code here
as_enqueue_async_action( 'second_hook', $second_args, 'my-group' );
}

add_action( 'second_hook', $args... ) {
// second code here
}
```

**Comment by strarsis** [comment]
So there is this call structure:
```php
as_schedule_single_action( 'first_hook', $args, 'my-group' );
add_action( 'first_hook', function( $args... ) {
  as_enqueue_async_action( 'sub_hook', $sub_args, 'my-group' );
});

add_action( 'sub_hook', function( $args... ) {
  // should run _before_ the second hook!
});


as_schedule_single_action( 'second_hook', $args, 'my-group' );
add_action( 'second_hook', function( $args... ) {
  // some code that should run _after_ the child-action sub_hook from first hook
}
````
So the first hook creates a sub hook. That sub hook should run before the second hook! Is this possible?

**Comment by crstauf** [comment]
@strarsis It would depend on the schedule times.

**Comment by crstauf** [comment]
@strarsis It’s possible, but not dependable. The runner claims actions to run, so if the first and second action are claimed, even though the async actions have an earlier time, they’ve not yet been claimed, so the second action would like run before the async actions.

**Comment by strarsis** [comment]
@crstauf: Any elegant solution to this? It is nice that action handlers can spawn own actions, now I need to chain them.
Example: An API offers a list of taxonomies and a list of posts and a third endpoint for a post-taxonomy mapping.
The WordPress plugin fetches the taxonomies and the posts in two separate tasks,
then for each post a separate action is spawned to fetch the post-taxonomy mapping for each one.
Only after all these individual post-taxonomy mappings have been fetched and saved in custom field data in the post, 
the last task should run to assign the posts to the taxonomies according to the custom field data.

**Comment by crstauf** [comment]
@strarsis Something like this I think should work.

1. Get taxonomies
2. Get posts
2b. Get post's taxonomy IDs
3. Assign taxonomies

```php
as_enqueue_async_action( 'get_taxonomies', array(), 'my-group' ); // 1. Get taxonomies
as_enqueue_async_action( 'get_posts', array(), 'my-group' ); // 2. Get posts

# 1. Get taxonomies
function get_taxonomies() {
    // get and store the taxonomies
}

# 2. Get posts
function get_posts() {
    $response = wp_remote_get( ... );

    // do validation and processing of response

    foreach ( $body as $post ) {
        # 2b. Get post's taxonomy IDs
        as_enqueue_async_action( 'get_post_taxonomies', array( $post->ID ), 'my-group' );
    }

    # 3. Assign taxonomies
    as_enqueue_async_action( 'assign_post_taxonomies', array( array_column( $body, 'ID' ) ), 'my-group' );
}

# 2b. Get post's taxonomy IDs
function get_post_taxonomies( $post_id ) {
    // get and store the taxonomies on the post
}

# 3. Assign taxonomies
function assign_post_taxonomies( $post_ids ) {
    foreach ( $post_ids as $post_id ) {
        $taxonomies = get_post_meta( ... );
        // assign taxonomies to posts
    }
}
```

**Comment by rrennick** [comment]
@strarsis @crstauf Feel free to continue the discussion. I'm going to close this as it's not an issue that would be addressed by making a PR.
