### ISSUE TITLE
Action schedule in database contains non-UTF characters, errors when editing the action manually

### ISSUE THREAD

**Issue by madeincosmos** [woocommerce/action-scheduler#585]
### Reported in
3095470-zen

### What I expected
To manually edit an existing action in site database.

### What happened instead
The schedule field contains some non-UTF characters which don't save properly when I update the record:

```
O:30:"ActionScheduler_SimpleSchedule":2:{s:22:"�*�scheduled_timestamp";i:1591367560;s:41:"�ActionScheduler_SimpleSchedule�timestamp";i:1591367560;}
```

![Screenshot](https://d.pr/i/CdZtQy+)
Screenshot: https://d.pr/i/CdZtQy 

Whenever I save such action, it no longer shows on the Scheduled Actions list in WP Admin and most likely can't be processed either. In the error log, I can see the following entry:

```
[01-Jul-2020 07:28:12 UTC] PHP Notice:  unserialize(): Error at offset 69 of 155 bytes in /Users/madeincosmos/dev/sites/new/wp-content/plugins/woocommerce/packages/action-scheduler/classes/data-stores/ActionScheduler_DBStore.php on line 193
```

### Expected result
Action schedule is stored in serialized form that can be unserialized manually and updated if needed.

Reproduced with: 

WooCommerce 4.2.2 
AS 3.1.6

**Comment by rrennick** [comment]
> The schedule field contains some non-UTF characters which don't save properly when I update the record:

@madeincosmos Those are `null` characters. When PHP serializes an object it uses nulls as delimiters. Serialized objects with embedded nulls cannot be editing manually in phpMyAdmin.
