### ISSUE TITLE
Action scheduler not running in background 

### ISSUE THREAD

**Issue by inceptionsoftware** [woocommerce/action-scheduler#586]
Hello,

We have a woocommerce based auction plugin using which admin can add auction products to their woocommerce (WC) site. 

As you might know that an auction product basically simulates the auction process we have in real auction houses. Below is a brief use-case which our plugin helps to simulate:

Admin adds an auction product with start and end date/time.
Users register to place their bids.
Plugin uses an action scheduler to check if an auction product is due to start or end. 
Let us say auction has started then users place their bids.
Then using the action scheduler, we check the expiration date in the background. And if the end date/time has come then we change the auction state from live to expired and send the winning email to the winner. 

We were using old action scheduler (version 1.4-dev) and we observed that when users are offline from the website i.e. the background action scheduler was not running. It was only running when anyone was online on the website. 

We then looked at the documents inside https://actionscheduler.org/version3-0/ and we updated our plugin to use latest action scheduler version but still we are facing the same problem that the background scheduler is not running.

Below is what we have used in our plugin:

1: We have loaded action scheduler inside our main plugin file using below code:  

 require_once( plugin_dir_path( __FILE__ ) . '/includes/action-scheduler/action-scheduler.php' );

2.  And we have then called action scheduler functions inside our attached file with name = “uwa-main-functions.php”. We have attached this file for your reference.
We have added three crons 

- add_action('init', 'woo_ua_cron_job');

- add_action('scheduled_woo_ua_update_status', 'woo_ua_update_status_callback', 10);

- add_action('scheduled_woo_ua_delete_completed_actions', 'woo_ua_delete_completed_actions_callback', 10); 

And we have called action scheduler’s recurring action function inside our init function:

- as_schedule_recurring_action(strtotime(time()),$cron_1_interval,'scheduled_woo_ua_update_status');

- as_schedule_recurring_action(strtotime(time()),'43200','scheduled_woo_ua_delete_completed_actions');

Could you please check this file to see why background cron is not running when no-one is online. Please do note that if there is any user online (visiting the site) then these actions work but they dont work when no-one is there visiting the website.

Please do let me know if you have any questions.

Regards,
Nitesh
[uwa-main-functions.txt](https://github.com/woocommerce/action-scheduler/files/4878659/uwa-main-functions.txt)

**Comment by crstauf** [comment]
@inceptionsoftware Are you familiar with how WP Cron works?

> WP-Cron does not run constantly as the system cron does; it is only triggered on page load.

https://developer.wordpress.org/plugins/cron/

**Comment by inceptionsoftware** [comment]
-- Please reply above this line --


Hello Woocommerce/action-Scheduler,

Thanks for reaching out to the Ultimate Auction Pro team (UAPro). You
are the reason we exist and our team is going to do everything we can
to help you. :-)

NOTE: We are experiencing a very unique & unprecedented situation due
to the Novel Coronavirus (COVID -19) outbreak in our country and the
whole world. In wake of this pandemic and in line with the government
advisory, we are working from home but with considerably reduced
employee strength. We therefore urge you to be more patient for our
responses to your queries and bear with us for any delay if it occurs.

We've received your request, so here's what you can expect from our
next response:

- It will be within the next 24 hours if your request was submitted
between Monday-Friday 9am-5pm IST. It may take a little longer than
that if it was made on the weekend or during a holiday.
- It will be friendly! We love our customers and welcome inquiries of
any type.

IMPORTANT: If you have a technical problem such as bids not appearing,
page is not displayed properly etc, then please do reply to this email
with following details:

	* Attach "WooCommerce System Report". You can find it here: WP Admin
> WooCommerce > Status
	* Share your Website url, temporary admin username and password. 
	* SFTP Details - FTP server, FTP user and FTP password. This is
needed to debug the Wordpress code and find out where the problem is.

Thanks again for choosing to place your confidence in UAPro, and we
look forward to serving you!

Nitesh Singh
Chief at Ultimate Auction

**Comment by rrennick** [comment]
@inceptionsoftware Action Scheduler includes a [WP CLI command](https://actionscheduler.org/wp-cli/) for use in sites with a large number of scheduled actions or sites where WP Cron is disabled / unreliable. If you install [WP CLI](https://wp-cli.org/) on your server then you can set up a server cron job to run action scheduler on a reliable schedule.
