### ISSUE TITLE
Action Scheduler seems not working

### ISSUE THREAD

**Issue by Demuri** [woocommerce/action-scheduler#588]
Since about July 6 exposed some problems which seems to be related to scheduler. Analytics doesn't import (or even delete) data, unpaid orders doesn't change their status etc. I found a lot of pending actions, after lot of experiments and manual run analytcs data became available, but i have no idea now how much useful actions I deleted in scheduler during experiments.

So actually it looks like all actions just stuck pending.

Please deliver any hint to debug. I already tried to turn on and off wp cron, but seems like it takes no effect. Please find system report below.

### WordPress Environment ###

WordPress address (URL): https://kniga.lv
Site address (URL): https://kniga.lv
WC Version: 4.3.0
REST API Version: ✔ 1.0.10
WC Blocks Version: ✔ 2.7.1
Action Scheduler Version: ✔ 3.1.6
WC Admin Version: ✔ 1.3.0
Log Directory Writable: ✔
WP Version: 5.4.2
WP Multisite: –
WP Memory Limit: 6 GB
WP Debug Mode: –
WP Cron: ✔
Language: ru_RU
External object cache: –

### Server Environment ###

Server Info: nginx/1.19.1
PHP Version: 7.3.20-1+ubuntu18.04.1+deb.sury.org+1
PHP Post Max Size: 8 MB
PHP Time Limit: 600
PHP Max Input Vars: 2000
cURL Version: 7.58.0
OpenSSL/1.1.1g

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.3.23-MariaDB-1:10.3.23+maria~bionic
Max Upload Size: 2 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 4.3.0
WC Database Prefix: wp_
Общий размер базы данных: 524.65MB
Размер данных в базе данных: 415.12MB
Размер индекса базы данных: 109.53MB
wp_woocommerce_sessions: Данные: 44.59MB + Индекс: 1.52MB + Движок InnoDB
wp_woocommerce_api_keys: Данные: 0.02MB + Индекс: 0.03MB + Движок InnoDB
wp_woocommerce_attribute_taxonomies: Данные: 0.02MB + Индекс: 0.02MB + Движок InnoDB
wp_woocommerce_downloadable_product_permissions: Данные: 0.02MB + Индекс: 0.06MB + Движок InnoDB
wp_woocommerce_order_items: Данные: 1.52MB + Индекс: 0.17MB + Движок InnoDB
wp_woocommerce_order_itemmeta: Данные: 5.52MB + Индекс: 4.03MB + Движок InnoDB
wp_woocommerce_tax_rates: Данные: 0.02MB + Индекс: 0.06MB + Движок InnoDB
wp_woocommerce_tax_rate_locations: Данные: 0.02MB + Индекс: 0.03MB + Движок InnoDB
wp_woocommerce_shipping_zones: Данные: 0.02MB + Индекс: 0.00MB + Движок InnoDB
wp_woocommerce_shipping_zone_locations: Данные: 0.02MB + Индекс: 0.03MB + Движок InnoDB
wp_woocommerce_shipping_zone_methods: Данные: 0.02MB + Индекс: 0.00MB + Движок InnoDB
wp_woocommerce_payment_tokens: Данные: 0.02MB + Индекс: 0.02MB + Движок InnoDB
wp_woocommerce_payment_tokenmeta: Данные: 0.02MB + Индекс: 0.03MB + Движок InnoDB
wp_woocommerce_log: Данные: 0.02MB + Индекс: 0.02MB + Движок InnoDB
wp_actionscheduler_actions: Данные: 0.52MB + Индекс: 0.58MB + Движок InnoDB
wp_actionscheduler_claims: Данные: 0.02MB + Индекс: 0.02MB + Движок InnoDB
wp_actionscheduler_groups: Данные: 0.02MB + Индекс: 0.02MB + Движок InnoDB
wp_actionscheduler_logs: Данные: 1.52MB + Индекс: 0.25MB + Движок InnoDB
wp_adtribes_my_conversions: Данные: 0.02MB + Индекс: 0.02MB + Движок InnoDB
wp_aepc_custom_audiences: Данные: 0.02MB + Индекс: 0.00MB + Движок InnoDB
wp_aepc_logs: Данные: 0.02MB + Индекс: 0.00MB + Движок InnoDB
wp_aryo_activity_log: Данные: 5.02MB + Индекс: 0.00MB + Движок InnoDB
wp_atum_order_itemmeta: Данные: 0.02MB + Индекс: 0.03MB + Движок InnoDB
wp_atum_order_items: Данные: 0.02MB + Индекс: 0.02MB + Движок InnoDB
wp_atum_product_data: Данные: 1.52MB + Индекс: 0.45MB + Движок InnoDB
wp_commentmeta: Данные: 0.02MB + Индекс: 0.03MB + Движок InnoDB
wp_comments: Данные: 2.52MB + Индекс: 1.11MB + Движок InnoDB
wp_dpd_barcodes: Данные: 0.02MB + Индекс: 0.03MB + Движок InnoDB
wp_dpd_manifests: Данные: 0.02MB + Индекс: 0.02MB + Движок InnoDB
wp_dpd_terminals: Данные: 0.02MB + Индекс: 0.02MB + Движок InnoDB
wp_eabi_carriermodule: Данные: 0.02MB + Индекс: 0.00MB + Движок InnoDB
wp_eabi_postoffice: Данные: 1.52MB + Индекс: 0.02MB + Движок InnoDB
wp_links: Данные: 0.02MB + Индекс: 0.02MB + Движок InnoDB
wp_options: Данные: 13.22MB + Индекс: 3.20MB + Движок InnoDB
wp_postmeta: Данные: 128.66MB + Индекс: 56.14MB + Движок InnoDB
wp_posts: Данные: 45.55MB + Индекс: 12.00MB + Движок InnoDB
wp_redirection_404: Данные: 0.30MB + Индекс: 0.30MB + Движок InnoDB
wp_redirection_groups: Данные: 0.02MB + Индекс: 0.03MB + Движок InnoDB
wp_redirection_items: Данные: 0.13MB + Индекс: 0.19MB + Движок InnoDB
wp_redirection_logs: Данные: 0.52MB + Индекс: 0.30MB + Движок InnoDB
wp_social_users: Данные: 0.02MB + Индекс: 0.02MB + Движок InnoDB
wp_termmeta: Данные: 1.52MB + Индекс: 1.89MB + Движок InnoDB
wp_terms: Данные: 2.52MB + Индекс: 2.00MB + Движок InnoDB
wp_term_relationships: Данные: 5.52MB + Индекс: 2.52MB + Движок InnoDB
wp_term_taxonomy: Данные: 1.52MB + Индекс: 3.03MB + Движок InnoDB
wp_tm_taskmeta: Данные: 0.16MB + Индекс: 0.03MB + Движок InnoDB
wp_tm_tasks: Данные: 0.06MB + Индекс: 0.02MB + Движок InnoDB
wp_usermeta: Данные: 3.47MB + Индекс: 3.78MB + Движок InnoDB
wp_users: Данные: 0.13MB + Индекс: 0.19MB + Движок InnoDB
wp_wcpdf_invoice_number: Данные: 0.06MB + Индекс: 0.00MB + Движок InnoDB
wp_wc_admin_notes: Данные: 0.02MB + Индекс: 0.00MB + Движок InnoDB
wp_wc_admin_note_actions: Данные: 0.02MB + Индекс: 0.02MB + Движок InnoDB
wp_wc_category_lookup: Данные: 0.02MB + Индекс: 0.00MB + Движок InnoDB
wp_wc_customer_lookup: Данные: 0.17MB + Индекс: 0.16MB + Движок InnoDB
wp_wc_download_log: Данные: 0.02MB + Индекс: 0.03MB + Движок InnoDB
wp_wc_order_coupon_lookup: Данные: 0.02MB + Индекс: 0.03MB + Движок InnoDB
wp_wc_order_product_lookup: Данные: 1.52MB + Индекс: 0.69MB + Движок InnoDB
wp_wc_order_stats: Данные: 0.22MB + Индекс: 0.19MB + Движок InnoDB
wp_wc_order_tax_lookup: Данные: 0.13MB + Индекс: 0.13MB + Движок InnoDB
wp_wc_product_meta_lookup: Данные: 1.52MB + Индекс: 1.47MB + Движок InnoDB
wp_wc_reserved_stock: Данные: 0.02MB + Индекс: 0.00MB + Движок InnoDB
wp_wc_tax_rate_classes: Данные: 0.02MB + Индекс: 0.02MB + Движок InnoDB
wp_wc_webhooks: Данные: 0.02MB + Индекс: 0.02MB + Движок InnoDB
wp_wfblockediplog: Данные: 0.13MB + Индекс: 0.00MB + Движок InnoDB
wp_wfblocks7: Данные: 0.09MB + Индекс: 0.08MB + Движок InnoDB
wp_wfconfig: Данные: 0.45MB + Индекс: 0.00MB + Движок InnoDB
wp_wfcrawlers: Данные: 0.02MB + Индекс: 0.00MB + Движок InnoDB
wp_wffilechanges: Данные: 0.02MB + Индекс: 0.00MB + Движок InnoDB
wp_wffilemods: Данные: 10.52MB + Индекс: 0.00MB + Движок InnoDB
wp_wfhits: Данные: 1.03MB + Индекс: 0.28MB + Движок InnoDB
wp_wfhoover: Данные: 0.02MB + Индекс: 0.02MB + Движок InnoDB
wp_wfissues: Данные: 0.02MB + Индекс: 0.06MB + Движок InnoDB
wp_wfknownfilelist: Данные: 6.52MB + Индекс: 0.00MB + Движок InnoDB
wp_wflivetraffichuman: Данные: 0.02MB + Индекс: 0.02MB + Движок InnoDB
wp_wflocs: Данные: 0.02MB + Индекс: 0.00MB + Движок InnoDB
wp_wflogins: Данные: 0.52MB + Индекс: 0.19MB + Движок InnoDB
wp_wfls_2fa_secrets: Данные: 0.02MB + Индекс: 0.02MB + Движок InnoDB
wp_wfls_settings: Данные: 0.02MB + Индекс: 0.00MB + Движок InnoDB
wp_wfnotifications: Данные: 0.02MB + Индекс: 0.00MB + Движок InnoDB
wp_wfpendingissues: Данные: 0.02MB + Индекс: 0.06MB + Движок InnoDB
wp_wfreversecache: Данные: 0.02MB + Индекс: 0.00MB + Движок InnoDB
wp_wfsnipcache: Данные: 0.08MB + Индекс: 0.08MB + Движок InnoDB
wp_wfstatus: Данные: 0.13MB + Индекс: 0.09MB + Движок InnoDB
wp_wftrafficrates: Данные: 0.02MB + Индекс: 0.00MB + Движок InnoDB
wp_woof_query_cache: Данные: 0.02MB + Индекс: 0.02MB + Движок InnoDB
wp_wpfb_badges: Данные: 0.02MB + Индекс: 0.00MB + Движок InnoDB
wp_wpfb_floats: Данные: 0.02MB + Индекс: 0.00MB + Движок InnoDB
wp_wpfb_forms: Данные: 0.02MB + Индекс: 0.00MB + Движок InnoDB
wp_wpfb_getapps_forms: Данные: 0.02MB + Индекс: 0.00MB + Движок InnoDB
wp_wpfb_gettwitter_forms: Данные: 0.02MB + Индекс: 0.00MB + Движок InnoDB
wp_wpfb_nofitifcation_forms: Данные: 0.02MB + Индекс: 0.00MB + Движок InnoDB
wp_wpfb_post_templates: Данные: 0.02MB + Индекс: 0.00MB + Движок InnoDB
wp_wpfb_reviewfunnel: Данные: 0.02MB + Индекс: 0.00MB + Движок InnoDB
wp_wpfb_reviews: Данные: 0.27MB + Индекс: 0.00MB + Движок InnoDB
wp_wpfm_backup: Данные: 0.02MB + Индекс: 0.00MB + Движок InnoDB
wp_wpmailsmtp_tasks_meta: Данные: 0.02MB + Индекс: 0.00MB + Движок InnoDB
wp_wpml_mails: Данные: 102.52MB + Индекс: 0.00MB + Движок InnoDB
wp_xoo_wl_list: Данные: 0.02MB + Индекс: 0.02MB + Движок InnoDB
wp_xoo_wl_list_meta: Данные: 0.02MB + Индекс: 0.03MB + Движок InnoDB
wp_yith_wcwl: Данные: 0.16MB + Индекс: 0.08MB + Движок InnoDB
wp_yith_wcwl_lists: Данные: 0.02MB + Индекс: 0.03MB + Движок InnoDB
wp_yoast_indexable: Данные: 19.55MB + Индекс: 11.06MB + Движок InnoDB
wp_yoast_indexable_hierarchy: Данные: 0.14MB + Индекс: 0.20MB + Движок InnoDB
wp_yoast_migrations: Данные: 0.02MB + Индекс: 0.02MB + Движок InnoDB
wp_yoast_primary_term: Данные: 0.02MB + Индекс: 0.03MB + Движок InnoDB
wp_yoast_seo_links: Данные: 0.20MB + Индекс: 0.08MB + Движок InnoDB
wp_yoast_seo_meta: Данные: 0.42MB + Индекс: 0.00MB + Движок InnoDB

### Post Type Counts ###

acf-field: 1
acf-field-group: 1
attachment: 10295
blocks: 9
custom_css: 2
flamingo_contact: 8102
flamingo_inbound: 8229
nav_menu_item: 75
page: 96
post: 18
product: 8921
revision: 54
shop_coupon: 18785
shop_order: 1513
shop_order_refund: 1
store: 12
wpcf7_contact_form: 7
wpcf7s: 9340
wpmm_theme: 3

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (59) ###

WP Review Slider Pro (Premium): от LJ Apps – 11.0.7.3
Advanced Cron Manager: от BracketSpace – 2.3.10
Advanced Custom Fields: от Эллиот Кондон – 5.8.12
Активность: от Activity Log Team – 2.5.2
ATUM Inventory Management for WooCommerce: от Stock Management Labs™ – 1.7.4
Autoclear Autoptimize Cache: от Theme Surgeons – 2.0.0
Autoptimize: от Frank Goossens (futtta) – 2.7.3
Contact Form 7 Conditional Fields: от Jules Colle – 1.9.7
Classic Editor: от Участники разработки WordPress – 1.5
Cloudflare: от Cloudflare
Inc. – 3.5.1

Honeypot for Contact Form 7: от Nocean – 1.14.1
Contact Form 7 Shortcode Enabler: от Tobias Zimpel (TZ Media) – 1.1
Contact Form 7: от Takayuki Miyoshi – 5.2
Contact Form Submissions: от Jason Green – 1.6.4
Уведомление о куки: от dFactory – 1.3.2
Custom Shipping Methods for WooCommerce Pro: от Algoritmika Ltd – 1.6.2 – Установленная версия не тестировалась с действующей версией WooCommerce 4.3.0
Webcraftic Cyrlitera – transliteration of links and file names: от Webcraftic  – 1.1.1
Duplicate Page: от mndpsingh287 – 4.2
Enhanced E-commerce for Woocommerce store: от Tatvic – 2.3.4 – Установленная версия не тестировалась с действующей версией WooCommerce 4.3.0
Flamingo: от Takayuki Miyoshi – 2.1.1
Loco Translate: от Tim Whitlock – 2.4.0
Max Mega Menu: от megamenu.com – 2.8
Nextend Social Login: от Nextendweb – 3.0.24
Доставка Omniva: от Omniva – 1.5.6 – Установленная версия не тестировалась с действующей версией WooCommerce 4.3.0
Order / Coupon / Subscription Export Import Plugin for WooCommerce (BASIC): от WebToffee – 1.6.6 – Установленная версия не тестировалась с действующей версией WooCommerce 4.3.0
Pixel Caffeine: от AdEspresso – 2.1.3 – Установленная версия не тестировалась с действующей версией WooCommerce 4.3.0
Product GTIN (EAN, UPC, ISBN) for WooCommerce: от Emanuela Castorina – 1.0.9 – Установленная версия не тестировалась с действующей версией WooCommerce 4.3.0
Redirection: от John Godley – 4.8
Regenerate Thumbnails: от Alex Mills (Viper007Bond) – 3.1.3
Импорт из RSS: от wordpressdotorg – 0.2
Smart WooCommerce Search PRO ( Smart Ajax Product Search ): от YummyWP – 1.1.16 – Установленная версия не тестировалась с действующей версией WooCommerce 4.3.0
Luminor E-commerce Gateway: от Luminor – 1.0.0 – Установленная версия не тестировалась с действующей версией WooCommerce 4.3.0
SSL Insecure Content Fixer: от WebAware – 2.7.2
Swiper Slider and Carousel: от WP OnlineSupport – 1.3.1
User Role Editor: от Владимир Гарагуля – 4.55.1
WooCommerce Waitlist Premium: от XootiX – 1.5 – Установленная версия не тестировалась с действующей версией WooCommerce 4.3.0
WC Pickup Store: от Keylor Mendoza A. – 1.5.28 – Установленная версия не тестировалась с действующей версией WooCommerce 4.3.0
Woocommerce Customers Order History: от javmah – 5.1.0 – Установленная версия не тестировалась с действующей версией WooCommerce 4.3.0
Advanced Order Export For WooCommerce: от AlgolPlus – 3.1.4 – Установленная версия не тестировалась с действующей версией WooCommerce 4.3.0
WooCommerce international phone input: от Alex Masliychuk (alex91ckua) – 2.0.3 – Установленная версия не тестировалась с действующей версией WooCommerce 4.3.0
Product Feed PRO for WooCommerce: от AdTribes.io – 8.4.7
WP Sheet Editor - WooCommerce Products (Premium): от WP Sheet Editor – 1.5.1.8
WooCommerce Shipping - DPD baltic: от DPD – 1.1.0 – Установленная версия не тестировалась с действующей версией WooCommerce 4.3.0
WooCommerce Extended Coupon Features FREE: от Soft79 – 3.1.4 – Установленная версия не тестировалась с действующей версией WooCommerce 4.3.0
Woocommerce E-Abi Postoffice plugin: от Matis Halmann
Aktsiamaailm LLC – 1.50 – Установленная версия не тестировалась с действующей версией WooCommerce 4.3.0

Бустер для WooCommerce: от Pluggabl LLC – 5.1.0 – Установленная версия не тестировалась с действующей версией WooCommerce 4.3.0
WooCommerce PDF Invoices & Packing Slips: от Ewout Fernhout – 2.5.3
WOOF - WooCommerce Products Filter: от realmag777 – 1.2.4.1 – Установленная версия не тестировалась с действующей версией WooCommerce 4.3.0
E-Abi Woocommerce Omniva Autosend method plugin: от Matis Halmann
Aktsiamaailm LLC – 1.15 – Установленная версия не тестировалась с действующей версией WooCommerce 4.3.0

E-Abi Omniva Shipping method plugin: от Matis Halmann
Aktsiamaailm LLC – 1.9 – Установленная версия не тестировалась с действующей версией WooCommerce 4.3.0

WooCommerce: от Automattic – 4.3.0
WooSidebars: от WooCommerce – 1.4.5
Wordfence Security: от Wordfence – 7.4.9
WordPress Importer: от wordpressdotorg – 0.7
Yoast SEO: от Команда Yoast – 14.5 – Установленная версия не тестировалась с действующей версией WooCommerce 4.3.0
WP Mail Logging: от MailPoet – 1.9.6
WP Mail SMTP: от WPForms – 2.2.1
WP-Optimize - Clean, Compress, Cache: от David Anderson
Ruhani Rabin
Team Updraft – 3.1.2

YITH WooCommerce Wishlist: от YITH – 3.0.11 – Установленная версия не тестировалась с действующей версией WooCommerce 4.3.0

### Inactive Plugins (5) ###

Akismet Anti-Spam: от Automattic – 4.1.6
Facebook for WooCommerce: от Facebook – 1.11.4 – Установленная версия не тестировалась с действующей версией WooCommerce 4.3.0
Smart WooCommerce Search: от YummyWP – 1.5.20
Woocommerce Waitlist( Back in stock notifier ): от  – 2.4 – Установленная версия не тестировалась с действующей версией WooCommerce 4.3.0
WP OPcache: от nierdz – 3.0.2

### Dropin Plugins (1) ###

advanced-cache.php: advanced-cache.php

### Settings ###

API Enabled: –
Force SSL: –
Currency: EUR (€)
Currency Position: left
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Ссылка магазина: #6 - /shop/
Корзина: #7 - /cart/
Оформление заказа: #8 - /checkout/
Мой аккаунт: #9 - /my-account/
Правила и условия: #3 - /privacy-policy/

### Theme ###

Name: Flatsome Child
Version: 3.0
Author URL: 
Child Theme: ✔
Parent Theme Name: Flatsome
Parent Theme Version: 3.12.0
Parent Theme Author URL: http://www.uxthemes.com/
WooCommerce Support: ✔

### Templates ###

Overrides: flatsome/woocommerce/archive-product.php
flatsome/woocommerce/cart/cart-empty.php
flatsome/woocommerce/cart/cart-shipping.php
flatsome/woocommerce/cart/cart.php
flatsome/woocommerce/checkout/form-checkout.php
flatsome/woocommerce/checkout/form-coupon.php
flatsome/woocommerce/checkout/terms.php
flatsome/woocommerce/checkout/thankyou.php
flatsome-child/woocommerce/content-product.php
flatsome/woocommerce/content-product_cat.php
flatsome/woocommerce/content-single-product.php
flatsome/woocommerce/content-widget-product.php
Есть обновления для flatsome-child/woocommerce/emails/admin-cancelled-order.php версии 3.7.0. Версия ядра — 4.1.0
flatsome-child/woocommerce/emails/admin-failed-order.php
flatsome-child/woocommerce/emails/admin-new-order.php
flatsome-child/woocommerce/emails/customer-completed-order.php
flatsome-child/woocommerce/emails/customer-invoice.php
flatsome-child/woocommerce/emails/customer-new-account.php
flatsome-child/woocommerce/emails/customer-note.php
flatsome-child/woocommerce/emails/customer-on-hold-order.php
flatsome-child/woocommerce/emails/customer-processing-order.php
flatsome-child/woocommerce/emails/customer-refunded-order.php
flatsome-child/woocommerce/emails/customer-reset-password.php
flatsome-child/woocommerce/emails/email-addresses.php
flatsome-child/woocommerce/emails/email-customer-details.php
flatsome-child/woocommerce/emails/email-downloads.php
flatsome-child/woocommerce/emails/email-footer.php
flatsome-child/woocommerce/emails/email-header.php
flatsome-child/woocommerce/emails/email-order-details.php
flatsome-child/woocommerce/emails/email-order-items.php
flatsome-child/woocommerce/emails/email-styles.php
Есть обновления для flatsome-child/woocommerce/emails/plain/admin-cancelled-order.php версии 3.7.0. Версия ядра — 4.1.0
flatsome-child/woocommerce/emails/plain/admin-failed-order.php
flatsome-child/woocommerce/emails/plain/admin-new-order.php
flatsome-child/woocommerce/emails/plain/customer-completed-order.php
flatsome-child/woocommerce/emails/plain/customer-invoice.php
flatsome-child/woocommerce/emails/plain/customer-new-account.php
flatsome-child/woocommerce/emails/plain/customer-note.php
flatsome-child/woocommerce/emails/plain/customer-on-hold-order.php
flatsome-child/woocommerce/emails/plain/customer-processing-order.php
flatsome-child/woocommerce/emails/plain/customer-refunded-order.php
flatsome-child/woocommerce/emails/plain/customer-reset-password.php
flatsome-child/woocommerce/emails/plain/email-addresses.php
flatsome-child/woocommerce/emails/plain/email-customer-details.php
flatsome-child/woocommerce/emails/plain/email-downloads.php
flatsome-child/woocommerce/emails/plain/email-order-details.php
flatsome-child/woocommerce/emails/plain/email-order-items.php
flatsome/woocommerce/global/breadcrumb.php
flatsome/woocommerce/global/quantity-input.php
flatsome/woocommerce/global/wrapper-end.php
flatsome/woocommerce/global/wrapper-start.php
flatsome/woocommerce/loop/loop-end.php
flatsome/woocommerce/loop/loop-start.php
flatsome-child/woocommerce/loop/no-products-found.php
flatsome/woocommerce/loop/pagination.php
flatsome/woocommerce/loop/result-count.php
flatsome/woocommerce/loop/sale-flash.php
flatsome/woocommerce/myaccount/form-login.php
flatsome/woocommerce/myaccount/navigation.php
flatsome/woocommerce/notices/error.php
flatsome/woocommerce/notices/notice.php
flatsome/woocommerce/notices/success.php
flatsome/woocommerce/product-searchform.php
flatsome-child/woocommerce/single-product/add-to-cart/simple.php
flatsome/woocommerce/single-product/photoswipe.php
flatsome/woocommerce/single-product/price.php
flatsome-child/woocommerce/single-product/product-image.php
flatsome/woocommerce/single-product/product-thumbnails.php
flatsome/woocommerce/single-product/rating.php
flatsome/woocommerce/single-product/related.php
flatsome/woocommerce/single-product/review.php
flatsome/woocommerce/single-product/sale-flash.php
flatsome/woocommerce/single-product/share.php
flatsome/woocommerce/single-product/short-description.php
flatsome/woocommerce/single-product/tabs/tabs.php
flatsome/woocommerce/single-product/title.php
flatsome/woocommerce/single-product/up-sells.php
flatsome/woocommerce/single-product-reviews.php
flatsome/woocommerce/single-product.php

### Action Scheduler ###

Выполнено: 1 745
Oldest: 2020-06-03 21:03:23 +0300
Newest: 2020-07-15 20:54:10 +0300

В процессе: 1
Oldest: –
Newest: –

Ожидает: 1
Oldest: 2020-07-16 20:19:52 +0300
Newest: 2020-07-16 20:19:52 +0300

**Comment by roykho** [comment]
Hi @Demuri 

Thanks for reporting. Could you please check your PHP error log and let us know if you see anything relating to Action Scheduler there? If so, could you please paste that information here?

Thanks!

**Comment by Demuri** [comment]
@code2prog , @roykho Sorry for delayed reply. The problem was that main Sction Scheduler job was somegow deleted from wp cron. I re-created it manually. Didn't find the reason but after that fix everything works fine.

**Comment by roykho** [comment]
Thanks @Demuri for the follow up! Glad you've got it figured out. I will be closing this issue now.
