### ISSUE TITLE
Add function_exists( 'add_action' ) check to initialization file

### ISSUE THREAD

**Issue by salcode** [woocommerce/action-scheduler#589]
This is the same issue as #303, which was resolved with #304 however while the PR was merged into `master` it appears it was never merged into the [version_3_0_0](https://github.com/woocommerce/action-scheduler/tree/version_3_0_0) branch and eventually the `version_3_0_0` branch was merged into `master` overwriting the fix (I believe this happened in 52bd355 as the fix exists in the parent commit (9275e2b)).

To summarize #303 

When we load Action Scheduler via Composer, we still need to execute the file `action-scheduler.php` to initialize everything.

Composer allows us to autoload a file, which handles this beautifully

```
"autoload": {
    "files": [
        "vendor/prospress/action-scheduler/action-scheduler.php"
    ]
},
```

**except** when we run a PHP tool added via Composer (e.g. `phpcs`) that runs _without_ WordPress

When `phpcs` runs, WordPress is not loaded and therefore the function `add_action()` does not exist and a Fatal Error is thrown.

By adding the check `function_exists( 'add_action' )`,

- when WordPress is loaded, everything works as it always has because `add_action()` exists
- when WordPress is NOT loaded (e.g. when `phpcs` is run), all of the Action Scheduler initialization is skipped (which isn't a problem because WordPress is not present) and we don't throw a Fatal Error

**Comment by roykho** [comment]
Closed via https://github.com/woocommerce/action-scheduler/commit/d512300dcd7818e647a37a7994bc01e825e14007
