### ISSUE TITLE
any way to limit 1 async concurrent action on specific actions?

### ISSUE THREAD

**Issue by xaviercshp** [woocommerce/action-scheduler#590]
sorry if this isn't the place to ask questions

**Comment by rrennick** [comment]
You can post future support questions at https://wordpress.org/support/plugin/action-scheduler/. 

The async runner only runs one action at a time. Can you clarify what you are seeing/looking to do?

**Comment by xaviercshp** [comment]
@rrennick thanks a lot sorry about that. if the `as_enqueue_async_action` will run one concurrent action at a time then im having a different issue, thanks.

**Comment by rrennick** [comment]
`as_enqueue_async_action` doesn't run actions. It adds them to the pending action list with an 'as soon as possible' schedule.

**Comment by juliaamosova** [comment]
Looks like this thread is resolved so closing it as a part of this repository's maintenance. Feel free to comment here again in case we missed something @xaviercshp and we'd take another look.
