### ISSUE TITLE
Database BlowOut!

### ISSUE THREAD

**Issue by Webxopt** [woocommerce/action-scheduler#592]
Hi, is there anyway to limit the storage that this system takes up? At the moment my database has wp_actionsheduler_actions.sql at 1.26GB and wp_actionscheduler_logs.sql at 1.43GB. This is causing chaos with my backup system which is in turn bringing the site to an almost total standstill.
Cheers

**Comment by lkraav** [comment]
See https://github.com/woocommerce/woocommerce/issues/26818#issuecomment-646568726

**Comment by rrennick** [comment]
Another reference when we worked through purging off the actions created by the above bug https://github.com/woocommerce/action-scheduler/issues/541

**Comment by Webxopt** [comment]
These don't seem like great fixes! Is there anything else in the works.

**Comment by rrennick** [comment]
> We should probably have a control that allows us to reduce the default time from 30 days to say a week (or about 20 minutes in this case).

You can do this with the filter `action_scheduler_retention_period`. The number passed through the filter is in seconds.

> It seems like quite a big bug to me still

The actions were created by another plugin vs being created by a bug in action scheduler.
