### ISSUE TITLE
Action Scheduler Crashing Wordpress

### ISSUE THREAD

**Issue by kumarec** [woocommerce/action-scheduler#593]
I have installed the latest plugin and it breaks my WordPress site. I have enabled the WordPress Debug here's the debug errors

`WordPress database error: [Table 'cd.wp_actionscheduler_actions' doesn't exist]
SELECT a.action_id FROM wp_actionscheduler_actions a WHERE a.hook='action_scheduler/migration_hook' AND a.status='in-progress' ORDER BY scheduled_date_gmt DESC LIMIT 1

WordPress database error: [Table 'cd.wp_actionscheduler_actions' doesn't exist]
SELECT a.action_id FROM wp_actionscheduler_actions a WHERE a.hook='action_scheduler/migration_hook' AND a.status='pending' ORDER BY scheduled_date_gmt ASC LIMIT 1

WordPress database error: [Table 'cd.wp_actionscheduler_actions' doesn't exist]
SELECT a.action_id FROM wp_actionscheduler_actions a WHERE a.hook='action_scheduler/migration_hook' AND a.status='in-progress' ORDER BY scheduled_date_gmt DESC LIMIT 1

WordPress database error: [Table 'cd.wp_actionscheduler_actions' doesn't exist]
SELECT a.action_id FROM wp_actionscheduler_actions a WHERE a.hook='action_scheduler/migration_hook' AND a.status='pending' ORDER BY scheduled_date_gmt ASC LIMIT 1

WordPress database error: [Table 'cd.wp_actionscheduler_groups' doesn't exist]
SELECT group_id FROM wp_actionscheduler_groups WHERE slug='action-scheduler-migration'

WordPress database error: [Table 'cd.wp_actionscheduler_groups' doesn't exist]
SHOW FULL COLUMNS FROM `wp_actionscheduler_groups`

WordPress database error: [Table 'cd.wp_actionscheduler_actions' doesn't exist]
SHOW FULL COLUMNS FROM `wp_actionscheduler_actions``

Resolve this issue asap.

**Comment by rrennick** [comment]
Please see https://github.com/woocommerce/action-scheduler/issues/577#issuecomment-655496284. Closing this issue as a duplicate.
