### ISSUE TITLE
Size of database is going up exponentially every day

### ISSUE THREAD

**Issue by jozeflambrecht** [woocommerce/action-scheduler#594]
WooCommerce: Version 4.3.1
WordPress: 5.4.2

![image](https://user-images.githubusercontent.com/11506957/88680601-ad6a2600-d0be-11ea-9593-a8300ed5384f.png)
![image](https://user-images.githubusercontent.com/11506957/88682574-d095d500-d0c0-11ea-940b-99c567c13777.png)

I only have a couple of orders (less than 100) and a couple of customers. However the size of my database is going up exponentially every day.
Can I empty the tables?
Is this normal behaviour? This is affecting the speed of my website according to my website monitor..

**Comment by rrennick** [comment]
> Is this normal behaviour?

No. If You have WooCommerce installed can you post your System Status Report?

**Comment by jozeflambrecht** [comment]
I found this article and just removed some records.. Site is fast again..
https://wpbeaches.com/removing-scheduled-actions-woocommerce-action-scheduler/

Here is my report (after I did the steps in the article above).

`
### WordPress Environment ###

WordPress address (URL): https://www.*****.com
Site address (URL): https://www.*****.com
WC Version: 4.3.1
REST API Version: ✔ 1.0.10
WC Blocks Version: ✔ 2.7.2
Action Scheduler Version: ✔ 3.1.6
WC Admin Version: ✔ 1.3.1
Log Directory Writable: ✔
WP Version: 5.4.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: fr_FR
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.4.8
PHP Post Max Size: 10 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.58.0
OpenSSL/1.1.1

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.1.44-MariaDB-0ubuntu0.18.04.1
Max Upload Size: 10 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 4.3.1
WC Database Prefix: 43nbK_
Taille totale de la base de données: 55.30MB
Taille de la base de données: 37.04MB
Taille de l’index: 18.26MB
43nbK_woocommerce_sessions: Données : 2.13MB + Index : 0.05MB + Moteur MyISAM
43nbK_woocommerce_api_keys: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
43nbK_woocommerce_attribute_taxonomies: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
43nbK_woocommerce_downloadable_product_permissions: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
43nbK_woocommerce_order_items: Données : 0.01MB + Index : 0.01MB + Moteur MyISAM
43nbK_woocommerce_order_itemmeta: Données : 0.10MB + Index : 0.05MB + Moteur MyISAM
43nbK_woocommerce_tax_rates: Données : 0.00MB + Index : 0.01MB + Moteur MyISAM
43nbK_woocommerce_tax_rate_locations: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
43nbK_woocommerce_shipping_zones: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
43nbK_woocommerce_shipping_zone_locations: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
43nbK_woocommerce_shipping_zone_methods: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
43nbK_woocommerce_payment_tokens: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
43nbK_woocommerce_payment_tokenmeta: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
43nbK_woocommerce_log: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
43nbK_actionscheduler_actions: Données : 4.02MB + Index : 13.11MB + Moteur InnoDB
43nbK_actionscheduler_claims: Données : 0.05MB + Index : 0.05MB + Moteur InnoDB
43nbK_actionscheduler_groups: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
43nbK_actionscheduler_logs: Données : 1.52MB + Index : 0.44MB + Moteur InnoDB
43nbK_commentmeta: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
43nbK_comments: Données : 1.05MB + Index : 0.09MB + Moteur InnoDB
43nbK_links: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
43nbK_nf3_actions: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
43nbK_nf3_action_meta: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
43nbK_nf3_chunks: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
43nbK_nf3_fields: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
43nbK_nf3_field_meta: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
43nbK_nf3_forms: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
43nbK_nf3_form_meta: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
43nbK_nf3_objects: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
43nbK_nf3_object_meta: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
43nbK_nf3_relationships: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
43nbK_nf3_upgrades: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
43nbK_options: Données : 2.39MB + Index : 1.11MB + Moteur InnoDB
43nbK_postmeta: Données : 16.17MB + Index : 2.27MB + Moteur InnoDB
43nbK_posts: Données : 8.50MB + Index : 0.13MB + Moteur InnoDB
43nbK_termmeta: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
43nbK_terms: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
43nbK_term_relationships: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
43nbK_term_taxonomy: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
43nbK_usermeta: Données : 0.05MB + Index : 0.03MB + Moteur InnoDB
43nbK_users: Données : 0.02MB + Index : 0.05MB + Moteur InnoDB
43nbK_wc_admin_notes: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
43nbK_wc_admin_note_actions: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
43nbK_wc_bookings_availability: Données : 0.02MB + Index : 0.02MB + Moteur MyISAM
43nbK_wc_bookings_availabilitymeta: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
43nbK_wc_booking_relationships: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
43nbK_wc_category_lookup: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
43nbK_wc_customer_lookup: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
43nbK_wc_download_log: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
43nbK_wc_order_coupon_lookup: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
43nbK_wc_order_product_lookup: Données : 0.02MB + Index : 0.06MB + Moteur InnoDB
43nbK_wc_order_stats: Données : 0.02MB + Index : 0.05MB + Moteur InnoDB
43nbK_wc_order_tax_lookup: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
43nbK_wc_product_meta_lookup: Données : 0.00MB + Index : 0.01MB + Moteur MyISAM
43nbK_wc_reserved_stock: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
43nbK_wc_tax_rate_classes: Données : 0.00MB + Index : 0.01MB + Moteur MyISAM
43nbK_wc_webhooks: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
43nbK_wfblockediplog: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
43nbK_wfblocks7: Données : 0.02MB + Index : 0.05MB + Moteur InnoDB
43nbK_wfconfig: Données : 0.09MB + Index : 0.00MB + Moteur InnoDB
43nbK_wfcrawlers: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
43nbK_wffilechanges: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
43nbK_wffilemods: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
43nbK_wfhits: Données : 0.02MB + Index : 0.05MB + Moteur InnoDB
43nbK_wfhoover: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
43nbK_wfissues: Données : 0.02MB + Index : 0.06MB + Moteur InnoDB
43nbK_wfknownfilelist: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
43nbK_wflivetraffichuman: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
43nbK_wflocs: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
43nbK_wflogins: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
43nbK_wfls_2fa_secrets: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
43nbK_wfls_settings: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
43nbK_wfnotifications: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
43nbK_wfpendingissues: Données : 0.02MB + Index : 0.06MB + Moteur InnoDB
43nbK_wfreversecache: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
43nbK_wfsnipcache: Données : 0.02MB + Index : 0.05MB + Moteur InnoDB
43nbK_wfstatus: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
43nbK_wftrafficrates: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
43nbK_woocommerce_bundled_itemmeta: Données : 0.02MB + Index : 0.03MB + Moteur MyISAM
43nbK_woocommerce_bundled_items: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
43nbK_woocommerce_shipping_table_rates: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM

### Post Type Counts ###

attachment: 132
custom_css: 2
fl-builder-template: 1
nav_menu_item: 20
page: 16
popup: 4
popup_theme: 7
post: 2
product: 60
revision: 349
shop_coupon: 8
shop_order: 30
shop_order_refund: 1
wafs: 1
wc_booking: 9

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (14) ###

Akismet Anti-Spam: par Automattic – 4.1.6
All-in-One WP Migration: par ServMask – 7.25
BackWPup: par Inpsyde GmbH – 3.7.1
Beaver Builder Plugin (Agency Version): par The Beaver Builder Team – 2.3.2.6
The Official Facebook Chat Plugin: par Facebook – 1.6
Popup Maker: par Popup Maker – 1.11.0
SiteOrigin Page Builder: par SiteOrigin – 2.11.1
SiteOrigin Widgets Bundle: par SiteOrigin – 1.17.3
Storefront Powerpack: par WooCommerce – 1.5.0
Theme Customisations: par WooThemes – 1.0.0
Checkout Field Editor for WooCommerce: par ThemeHigh – 1.4.3
WooCommerce Bookings: par WooCommerce – 1.15.5 – La version installée n’a pas été testée avec la version en cours de WooCommerce 4.3.1
WooCommerce Stripe Gateway: par WooCommerce – 4.5.0 – La version installée n’a pas été testée avec la version en cours de WooCommerce 4.3.1
WooCommerce: par Automattic – 4.3.1

### Inactive Plugins (6) ###

Facebook for WooCommerce: par Facebook – 1.11.4 – La version installée n’a pas été testée avec la version en cours de WooCommerce 4.3.1
Jetpack by WordPress.com: par Automattic – 8.7.1
Ninja Forms: par Saturday Drive – 3.4.24.3
WooCommerce PayPal Checkout Gateway: par WooCommerce – 2.0.3
Wordfence Security: par Wordfence – 7.4.9
Yoast Duplicate Post: par Enrico Battocchi & Team Yoast – 3.2.5

### Dropin Plugins (1) ###

maintenance.php: maintenance.php

### Settings ###

API Enabled: –
Force SSL: –
Currency: CAD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: booking (booking)
bundle (bundle)
external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Base de la boutique: #233 - /boutique-de-numerologie/
Panier: #234 - /panier/
Commander: #235 - /commande/
Mon compte: #236 - /mon-compte/
Conditions générales de vente et d’utilisation: ❌ Page non définie

### Theme ###

Name: Storefront
Version: 2.5.3 (une mise à jour de la version 2.5.8 est disponible)
Author URL: https://woocommerce.com/
Child Theme: ❌ – Si vous modifiez WooCommerce sur un thème parent que vous n’avez pas construit personnellement
nous vous recommandons d’utiliser un thème enfant. Voir : Comment créer un thème enfant

WooCommerce Support: ✔

### Templates ###

Overrides: –

### Product Bundles ###

Database Version: 5.12.0
Template Overrides: –

### Action Scheduler ###

Complete: 3 274
Oldest: 2020-07-28 10:58:57 -0400
Newest: 2020-07-28 11:13:54 -0400

Pending: 5 776
Oldest: 2020-07-27 23:48:24 -0400
Newest: 2020-07-28 11:14:54 -0400

`

**Comment by jozeflambrecht** [comment]
I think it is an issue with the Bookings plugin. 
![image](https://user-images.githubusercontent.com/11506957/88686627-456b0e00-d0c5-11ea-8f49-0de122207854.png)

**Comment by rrennick** [comment]
> I think it is an issue with the Bookings plugin.

The latest version is 1.15.23. There was an issue with the Google Calendar functionality recently so updating Bookings would be the first thing to do.

**Comment by jozeflambrecht** [comment]
thanks! updating bookings was the solution
