### ISSUE TITLE
Can I use as_get_scheduled_action args with a subset of the args

### ISSUE THREAD

**Issue by dan-lutd** [woocommerce/action-scheduler#595]
Using  as_get_scheduled_action wroks with the following args and returns the expected object
`$search_args = array(`
`	'hook'   => 'lutd_deposit_payments_auto_payment' ,`
`	'group'  => 'lutd_deposit_payments_auto_pay',`
`	'status' =>  ActionScheduler_Store::STATUS_PENDING, `
`	'args'   => array( `
`		'order_id' => '106174',`
`	       'payment' => 2,`
`		'customer_id' => $customer_id `
`	)`
`);`
`$scheduled_items = as_get_scheduled_actions( $search_args ); `

But only if I use all of the hook's  'args'. 
`'args'   => array( 
		'order_id' => '106174',
		'payment' => 2,
		'customer_id' => $customer_id 
	)`

In this case i only  want to know if `'customer_id' => $customer_id ` regardless of the order_id and payment values.
Is there a way to get all the scheduled actions matching only a subset of the hooks args?

**Comment by crstauf** [comment]
@dan-lutd I think #563 may be what you're hoping for.

**Comment by dan-lutd** [comment]
@crstauf that #563 answers my question. It would allow me partial match query.

**Comment by roykho** [comment]
Closing in favor of https://github.com/woocommerce/action-scheduler/pull/563
