### ISSUE TITLE
Suggest Page Title: Scheduled Actions by WooCommerce

### ISSUE THREAD

**Issue by elidelusa** [woocommerce/action-scheduler#599]
Hi, I'm a WP developer. I would like to suggest that it's better to change the Page Title of this WP Submenu in Tools to avoid confusion, what plugin implemented it.

Page Title Suggest: **Scheduled Actions by WooCommerce**

By having the 'WooCommerce', developer would know that Woocommerce plugin implemented it.

**Comment by rrennick** [comment]
@elidelusa Thanks for the suggestion. 

Action Scheduler can be installed as a standalone plugin. It is also used as a scheduling library in non-WooCommerce plugins. In both cases, the scheduled actions are not by WooCommerce.

If you have WooCommerce installed, the Scheduled Actions screen is also available in WooCommerce -> Status -> Scheduled Actions.
