### ISSUE TITLE
Admin list table screen options do not persist

### ISSUE THREAD

**Issue by crstauf** [woocommerce/action-scheduler#600]
Toggling a column's visibility does not persist upon page loads.

**Comment by crstauf** [comment]
Clarification: the state of the checkbox persists, but the state does not correctly impact the list table.

**Comment by juliaamosova** [comment]
Hi @crstauf,

Thanks for raising the issue. Can you please provide the steps to reproduce the issue? Unless I am missing something very obvious here on how to reproduce.

**Comment by crstauf** [comment]
@Aljullu Within WordPress admin:

1. Tools > Scheduled Actions
1. Toggle the Screen Options drawer in the upper-right of the screen
1. Uncheck Log checkbox (note the Log column disappears)
1. Reload the page (note the Log column is visible)
1. Toggle the Screen Options drawer (note the Log checkbox is unchecked)

The Log column's visibility should match the checked state of the Log checkbox.

**Comment by crstauf** [comment]
@juliaamosova Within WordPress admin:

1. Tools > Scheduled Actions
1. Toggle the Screen Options drawer in the upper-right of the screen
1. Uncheck Log checkbox (note the Log column disappears)
1. Reload the page (note the Log column is visible)
1. Toggle the Screen Options drawer (note the Log checkbox is unchecked)

The Log column's visibility should match the checked state of the Log checkbox.

**Comment by danielbitzer** [comment]
I've also just encountered this issue.

**Comment by barryhughes** [comment]
https://user-images.githubusercontent.com/3594411/120851745-1d8ed700-c52e-11eb-8c53-1d555cca663b.mov

Can confirm... seems like we need to add some logic in one of our ListTable classes to inspect `get_hidden_columns()` (possibly).
