### ISSUE TITLE
Action scheduler run in wp-cli

### ISSUE THREAD

**Issue by chathu020** [woocommerce/action-scheduler#605]
I am having a about 1000tasks which must run in concurrently and repeat in every 2minutes. ( at each task it calls a external api ->get the data ->process data->call another api ). So I am planning to use action-scheduler. My problem is how can I use wp-cli, Sorry I am lack of knowledge on wp-cli. What I am familiar is I can add as_schedule_recurring_action() in each time a task is created in my plugin.
How can I use wp-cli for this. and please note that task creation is dynamic and web user is doing that.

**Comment by rrennick** [comment]
Most WP CLI commands have `help`. You can access the action scheduler help with `wp help action-scheduler`. Your hosting documentation should have information on setting up server cron jobs in your environment.
