### ISSUE TITLE
Composer package type / install as library

### ISSUE THREAD

**Issue by strarsis** [woocommerce/action-scheduler#606]
When installing the `action-scheduler` composer package, it is installed as a WordPress plugin, not as a library.
Would it make more sense to define the type of this package as a "library" instead of a "wordpress-plugin"?
Or can the type be overridden when requiring the `action-scheduler` package in `composer.json`?

**Comment by strarsis** [comment]
Addendum: Using `composer` to install `action-scheduler` as dependency of an existing WordPress plugin resulted in git repository corruption of that requiring, custom plugin. Installing the custom plugin via `composer`, too, results in the resulting plugin folder being occupied by the original contents of the `action-scheduler` plugin. Aldo the git history seems to be different afterwards.

**Comment by rrennick** [comment]
> Would it make more sense to define the type of this package as a "library" instead of a "wordpress-plugin"?

Action Scheduler is a standalone WordPress plugin: https://wordpress.org/plugins/action-scheduler/. If you have a composer setup that is your entire WP project, there is no difference between it active standalone or used as an embedded library (eg. WC).
