### ISSUE TITLE
get_action_scheduler_scheduled_actions not working properly

### ISSUE THREAD

**Issue by electrobank** [woocommerce/action-scheduler#607]
When calling this with the default OBJECT return type, each object variable is 'protected' and can't be accessed. I can print_f the object but if I try to access any variable it won't let me. When requesting a ARRAY_A return format, it returns an array of empty arrays.

**Comment by Konamiman** [comment]
Hi @electrobank, thanks for your report. Not sure if I understand the issue, but the fact is that there's currently no function related to Action Scheduler named `get_action_scheduler_scheduled_actions`. The two ways to retrieve information about existing actions are the `as_has_scheduled_action` function and the `as_next_scheduled_action` function.

I'm closing this for now, but if you have further comments or questions on this please write them down in a comment and we'll be happy to reopen the issue.
