### ISSUE TITLE
WP mail SMTP Email test

### ISSUE THREAD

**Issue by yashg8706** [woocommerce/action-scheduler#608]
Hi,

I'm getting the following message for email test
"There has been a critical error on your website. Please check your site admin email inbox for instructions.

Learn more about debugging in WordPress."

Please help.

Thank you

**Comment by juliaamosova** [comment]
Hi @yashg8706,

Thanks for raising the issue! Is your request related to Action Scheduler in particular or WooCommerce in general? It is not clear what have you been trying to accomplish or the steps you took that lead you to that error.

**Comment by jaredatch** [comment]
@yashg8706 if you have an error log to provide that help.

WP Mail SMTP does include Action Scheduler, but it's not used for sending emails, including test emails.

**Comment by yashg8706** [comment]
Hi, the error comes when the email test on WP mail SMTP

**Comment by barryhughes** [comment]
Going to close (lack of activity/not enough information to proceed). 

Please do feel free to create a fresh issue, though, if you still need assistance and believe this is a bug in Action Scheduler. As above, more details such as error log entries would definitely be helpful.

Beyond that, if you only see this problem when using Action Scheduler via WP Mail SMTP, it may also be worth reaching out to their team—if only to make them aware.

Thanks!
