### ISSUE TITLE
Remove underscores from PHP filenames 

### ISSUE THREAD

**Issue by rrennick** [woocommerce/action-scheduler#614]
The underscores are interfering with some code loaders: pMz3w-bWp-p2

For classes named `ActionScheduler_ClassName` changing the name to `ActionSchedulerClassName` will still be quite readable.

The files in the `/lib/`folder should have an appropriate note at the top documenting the file name change.

**Comment by roykho** [comment]
I would suggest we stick to the WP standards here and use hyphens.

**Comment by rrennick** [comment]
@roykho I did that in the PR but didn't update the issue description.

**Comment by rrennick** [comment]
Addressed in #617
