### ISSUE TITLE
Unserialize DateTime instances

### ISSUE THREAD

**Issue by strarsis** [woocommerce/action-scheduler#624]
Passing an argument with a DateTime instance to an action handler results in that DateTime instance being passed serialized as array instead of a DateTime instance.

Alternatively, Action Scheduler library could offer a filter for serialization/deserialization customizations.

**Comment by rrennick** [comment]
> Action Scheduler library could offer a filter for serialization/deserialization customizations.

@strarsis Arguments are `json_encoded` for storage in the database. The way to implement an alternate method of serialization is through a custom data store. 

If it were allowed through a filter then disabling a plugin that had implemented that filter would make the `$args` stored in the database inaccessible.

**Comment by strarsis** [comment]
OK, I will deserialize the DateTime fields in the handler function ([`DateTime::__set_state()`](https://www.php.net/manual/en/datetime.set-state.php)).
