### ISSUE TITLE
Uncaught RuntimeException: Error saving action: Error saving action

### ISSUE THREAD

**Issue by beesalsht** [woocommerce/action-scheduler#625]
Whenever I try to activate this plugin it throws the following error and crashes my website. Same while trying to install woocommerce plugin. Any help??

An error of type E_ERROR was caused in line 44 of the file /home/u704112749/domains/beyondhimalayas.com/public_html/1602400311293/wp-content/plugins/action-scheduler-3.1.6/classes/migration/ActionScheduler_DBStoreMigrator.php. Error message: Uncaught RuntimeException: Error saving action: Error saving action: Table 'u704112749_y9Xv7.wpstg0_actionscheduler_actions' doesn't exist in /home/u704112749/domains/beyondhimalayas.com/public_html/1602400311293/wp-content/plugins/action-scheduler-3.1.6/classes/migration/ActionScheduler_DBStoreMigrator.php:44 Stack trace: #0 /home/u704112749/domains/beyondhimalayas.com/public_html/1602400311293/wp-content/plugins/action-scheduler-3.1.6/classes/data-stores/ActionScheduler_HybridStore.php(242): ActionScheduler_DBStoreMigrator->save_action(Object(ActionScheduler_Action), NULL) #1 /home/u704112749/domains/beyondhimalayas.com/public_html/1602400311293/wp-content/plugins/action-scheduler-3.1.6/classes/ActionScheduler_ActionFactory.php(177): ActionScheduler_HybridStore->save_action(Object(ActionScheduler_Action)) #2 /home/u704112749/domains/beyondhimalayas.com/public_html/1602400311293/wp-content/plugins/action-scheduler-3.1.6/classes/ActionScheduler_ActionFactory.php(84): ActionScheduler_ActionFactory->store(Objec

**Comment by balazsmts** [comment]
We're having the same issue on a number of sites. When we try to activate the standalone Action Scheduler plugin on the site, we see this error:

> Fatal error: Uncaught RuntimeException: Error saving action: Error saving action: Table 'dbname.prefix_wp8o_actionscheduler_actions' doesn't exist in /.../wp-content/plugins/action-scheduler/classes/migration/ActionScheduler_DBStoreMigrator.php:44

Looking around on the web, we can see that the same error has been reported many times in the recent months (related to WooCommerce and other plugins) but we found no definitive solution.

We use the Action Scheduler in the new version of [our plugin that has 500k+ active installs](https://wordpress.org/plugins/seo-by-rank-math/). This error shows up on hundreds of sites after updating.

**Comment by AkramiPro** [comment]
i have the same issue . any solution?

**Comment by roykho** [comment]
Hi @beesalsht,

So I am unable to replicate your issue. This is what I see when I activate the standalone plugin ![](https://d.pr/i/P83O6d+)

Could you perhaps give us some information on your hosting environment? Such as PHP version, database client..etc?

**Comment by barryhughes** [comment]
Closing in favour of #653.

(The trace suggests this was a problem with missing tables, encountered during the post table ↔ custom table migration.)
