### ISSUE TITLE
Test Action Scheduler with Subscriptions for PHP 8

### ISSUE THREAD

**Issue by peterfabian** [woocommerce/action-scheduler#627]
Reach out to folks from Lambda to test together.

**Comment by peterfabian** [comment]
Hi @Konamiman, have you had a chance to look into this one? If not, should we just close this one and leave this for subscriptions team to open any issues in AS when needed?

**Comment by Konamiman** [comment]
Hi, no, sorry. I agree that we could handoff this to the Subscriptions team, and provide them any help they might eventually need.
