### ISSUE TITLE
Double check action scheduled date in case they're processing too early

### ISSUE THREAD

**Issue by madeincosmos** [woocommerce/action-scheduler#634]
We've had a few reports of database errors causing actions to be processed ahead of the schedule. This happens when the database server's disk is full:

```
[11-Oct-2020 21:15:48 UTC] WordPress database error Disk full (/tmp/#sql_6ff4_0.MAI); waiting for someone to free some space… (errno: 28 "No space left on device") for query SHOW FULL COLUMNS FROM wpstg3_options made by shutdown_action_hook, do_action('shutdown'), WP_Hook->do_action, WP_Hook->apply_filters, ActionScheduler_QueueRunner->maybe_dispatch_async_request, ActionScheduler_OptionLock->set, update_option
```

As far as I understand, if an error like this comes up when looking for scheduled actions that are due for processing, the server sometimes sends back intermediate results (i.e. all rows, or all rows that are pending regardless of their scheduled date, etc) instead of only the actions that were due to process now.

Given that scheduled actions often control mission-critical functions like subscription renewals, could we add an extra check to make sure the scheduled date is not in the future before running it? Ideally this would only happen on queue runners so that users are still able to run an action manually if they need to.

**Comment by thenbrent** [comment]
An alternative solution, and/or additional safeguard, would be to halt execution of AS when the disk if full and the database can't write. There's going to be additional issue in that situation that would be good to prevent.

**Comment by AashikP** [comment]
Another report in 3495533-zen

**Comment by madeincosmos** [comment]
One more possible case of the same problem here:

https://wordpress.org/support/topic/mailchimp-and-woocommerce-subscriptions/

Subscription renewals started suddenly processing ahead of time after the Mailchimp plugin created a large number of scheduled actions. 1 action per 1 order shouldn't normally take that much disk space, so either the database was already at its disk space limits, or there's some process running amok and creating such actions continuously.

**Comment by rrennick** [comment]
> 1 action per 1 order shouldn't normally take that much disk space

Worth noting is there is a difference between MySQL running out of temporary disk space (this issue) and MySQL running out of space in the database. If a site is out of "permanent" database space it would be having errors throughout WP.

**Comment by jonathansadowski** [comment]
Note: We discussed splitting this into two parts. This issue will serve to put a check in place to make sure that the actions we're trying to process are valid (as the title of this issue currently suggests). We've create da separate issue with a spike to investigate the underlying issue in https://github.com/woocommerce/action-scheduler/issues/650
