### ISSUE TITLE
Critical ERROR_Woocommerce and Wordpress 4.6.1

### ISSUE THREAD

**Issue by kamadoandino** [woocommerce/action-scheduler#635]
Hi everyone.

I have a problem in my wordpress page, with woocommerce plugin.

Show this when i enter to wordpress:

Se ha producido un error del tipo E_ERROR en la línea 143 del archivo /var/www/wp-content/plugins/woocommerce/packages/action-scheduler/classes/abstracts/ActionScheduler.php. Mensaje de error: Uncaught Error: Class 'ActionScheduler_DataController' not found in /var/www/wp-content/plugins/woocommerce/packages/action-scheduler/classes/abstracts/ActionScheduler.php:143 Stack trace: #0 /var/www/wp-content/plugins/woocommerce/packages/action-scheduler/action-scheduler.php(44): ActionScheduler::init('/var/www/wp-con...') woocommerce/woocommerce#1 /var/www/wp-content/plugins/woocommerce/packages/action-scheduler/classes/ActionScheduler_Versions.php(59): action_scheduler_initialize_3_dot_1_dot_6() woocommerce/woocommerce#2 /var/www/wp-includes/class-wp-hook.php(285): ActionScheduler_Versions::initialize_latest_version() woocommerce/woocommerce#3 /var/www/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters(Object(GEM_Official), Array) woocommerce/woocommerce#4 /var/www/wp-includes/plugin.php(478): WP_Hook->do_action(Array) woocommerce/woocommerce#5 /var/www/wp-settings.php(409): do_action('plugins_loaded') woocommerce/woocommerce#6 /var/www/wp-config.php(97): require_once('/var/www/wp-set...') woocommerce/woocommerce#7 /var/www/wp-load.php(37): require_once('/var/www/wp-con...') woocommerce/woocommerce#8 /var/www/wp-login.php(12): require('/var/www/wp-loa...') woocommerce/woocommerce#9 {main} thrown
![critial error woocommerce](https://user-images.githubusercontent.com/73486688/97195651-97c9d280-1779-11eb-824c-fa233254dd59.jpg)

please help me

i dont know what i have to do

best regards

thanks

**Comment by rrennick** [comment]
> Error: Class 'ActionScheduler_DataController' not found

@kamadoandino that looks like you have an incomplete copy of the WooCommerce plugin. Can you re-install it?

**Comment by barryhughes** [comment]
Closing (lack of feedback/seems like the plugin was perhaps not installed correctly).
