### ISSUE TITLE
Not executing?

### ISSUE THREAD

**Issue by de-integratie-specialisten** [woocommerce/action-scheduler#636]
Hi,

I'm using as_enqueue_async_action to execute my function. No errors and the job/task is add to the table wp_actionscheduler_actions but my function never executes, 'status' is indicating 'pending'.

What could be the cause of this?

Row from wp_actionscheduler_actions:

```
           action_id: 16
                hook: mrc_send_message
              status: pending
  scheduled_date_gmt: 0000-00-00 00:00:00
scheduled_date_local: 0000-00-00 00:00:00
                args: [1,"+31612387242","new order 16"]
            schedule: O:28:"ActionScheduler_NullSchedule":0:{}
            group_id: 3
            attempts: 0
    last_attempt_gmt: 0000-00-00 00:00:00
  last_attempt_local: 0000-00-00 00:00:00
            claim_id: 0
       extended_args: NULL

```

**Comment by de-integratie-specialisten** [comment]
I am able to run it manually, from http://localhost:8081/wp-admin/admin.php?page=wc-status&tab=action-scheduler. Clicking 'Run' for a pending task works properly; my function is called and status changes to 'Complete'.

**Comment by rwngallego** [comment]
Maybe this is related: https://github.com/docker-library/wordpress/issues/531

**Comment by de-integratie-specialisten** [comment]
That seems to be (part of) the problem. Changing the port setting to 80:80 *seems* to run the task/job; it's status gets set to 'Complete'. However, the code's doesn't seem to run. Or it errors out for some reason.

All seems to be docker-related. The wordpress docker image somehow doesn't show the error_log so I don't have a clue what's going on :( 

Before, with the previous port setup, and manually clicking 'Run' did run the same code properly.

**Comment by rwngallego** [comment]
You can run `docker logs CONTAINER_ID`, all the wordpress logs are forwarded to `stdout/stderr`

**Comment by de-integratie-specialisten** [comment]
`docker logs -f CONTAINER_ID >/dev/null` does show `stderr`. Yet this function: 

function mrc_send_message(int $messageType, string $msisdn, string $message) {
	error_log('mrc_send_message');
}

Doesn't log anything. No other errors, just nothing in the error_log.

**Comment by de-integratie-specialisten** [comment]
Even triggering a divide by zero in my function gives no errors :( 

Can't figure it out.

**Comment by de-integratie-specialisten** [comment]
It's returning in wp-includes/plugin.php, in function do_action_ref_array:

`	if ( ! isset( $wp_filter[ $tag ] ) ) {
		if ( isset( $wp_filter['all'] ) ) {
			array_pop( $wp_current_filter );
		}
		return; // ##  <-- returns here, not executing the action.
	}
`
That's somewhere around line 539 (have been editing a bit in the file for debugging but it should be around there).

**Comment by de-integratie-specialisten** [comment]
I stripped my plugin so it only enqueues the job like below. I can see the task being properly loaded, all looks good. Yet it still returns in `do_action_ref_array` before it gets executed, apparently because my task is not in the `$wp_filter` array.

So why does all this not work for me but apparently for loads of others, it does? 


```
<?php

/**
 *
 * Plugin Name: Test Action Control
 *
 * Description: -
 *
 * Plugin URI: -
 *
 * Author: -
 *
 * Version: 0.1.0
 *
 * Author URI: -
 *
 */

defined('ABSPATH') || exit;

require_once( plugin_dir_path( __FILE__ ) . '/lib/action-scheduler/action-scheduler.php');

function mrc_send_message() {
	error_log('[mrc_send_message executing]');
}

function mrc_initiate_conversation() {
	as_enqueue_async_action('mrc_send_message');
}

function attach_mrc_plugin() {
	add_action('woocommerce_new_customer_note', 'mrc_initiate_conversation');
}

add_action('woocommerce_loaded', 'attach_mrc_plugin');

```

**Comment by de-integratie-specialisten** [comment]
Ok. Solved. You have to do an add_action in your plugin with a label (not sure if this is the correct name) that points to your function and is THAT as an argument to as_enqueue_async_action. NOT the actual function name.

This works:

```
<?php

/**
 *
 * Plugin Name: Test Action Control
 *
 * Description: -
 *
 * Plugin URI: -
 *
 * Author: -
 *
 * Version: 0.1.0
 *
 * Author URI: -
 *
 */

defined('ABSPATH') || exit;

require_once( plugin_dir_path( __FILE__ ) . '/lib/action-scheduler/action-scheduler.php');

function mrc_send_message() {
	error_log('[mrc_send_message executing]');
}

function mrc_initiate_conversation() {
	as_enqueue_async_action('mrc_send_message_action');
}

function attach_mrc_plugin() {
	add_action('woocommerce_new_customer_note', 'mrc_initiate_conversation');
}

add_action('woocommerce_loaded', 'attach_mrc_plugin');

add_action('mrc_send_message_action', 'mrc_send_message');

```

**Comment by de-integratie-specialisten** [comment]
Maybe the documentation for as_enqueue_async_action could be made clearer on this? Just a suggestion.

**Comment by rrennick** [comment]
@de-integratie-specialisten the documentation for the `as_*` functions is https://actionscheduler.org/api/.

**Comment by roykho** [comment]
Closing this as it is resolved.
