### ISSUE TITLE
Callback not always called (erratic behaviour)

### ISSUE THREAD

**Issue by staticblue38** [woocommerce/action-scheduler#637]
Hi,

I've tried to use the action-scheduler library in a plugin I'm creating. The action is scheduled, then performed just fine (as indicated by its status in the dashboard actions table). The problem is that the callback is called sometimes, but not each time, it's very unpredictable. I realize this isn't happening to everyone, so it must be something with my setup. This is making me go crazy because I can't seem to figure out why it's not always called. I've tried using "as_schedule_single_action" and "as_enqueue_async_action". I've tried on a live server and locally too. 

Any suggestions? Thanks!

**Comment by crstauf** [comment]
The first thing that comes to mind is that the callback registration occurs conditionally or later in the load process such that it is not always registered when the action runs.

Simple way to test: create an mu-plugin that registers a callback on the scheduled action hook that outputs to a file, and see the callback is executed consistently with the action.

**Comment by staticblue38** [comment]
Thanks for your reply. It seems you are quite right: I tried your suggestion of registering the callback inside a mu-plugin, and the callback is executed every time. This makes me wonder how I can achieve the same result without the mu-plugin? I feel like I am following the instructions from the "usage" page correctly (https://actionscheduler.org/usage), but maybe I am not?

Inside my main plugin PHP file, I have the following: 
```
require_once('libraries/action-scheduler/action-scheduler.php');

function submit_button_pressed()
{
    as_enqueue_async_action('my_custom_action_trigger',array('infos' => $infos)); // enqueue action when admin presses a button in the admin section; this seems to work fine
}

add_action('my_custom_action_trigger', 'my_callback', 10, 1); // register the callback
  
function my_callback($infos)
{
error_log('test'); // the callback isn't executed every time
}
```

**Comment by crstauf** [comment]
Okay great!

Your code sample all looks right, so the next question is when is that file being included?

**Comment by staticblue38** [comment]
Cool, thanks!

The file is the main file of my plugin, so I'm thinking it's included when the WordPress plugins are loaded. Is that not OK?

**Comment by crstauf** [comment]
Hmmm, that should be fine.

If I get time today I'll create a sample plugin in an effort to match your use-case to see if I can recreate the problem.

**Comment by staticblue38** [comment]
that would definitely be helpful, thanks!

**Comment by roykho** [comment]
Hi @staticblue38 - so I did some tests on my local setup and was not able to replicate the issue you're seeing. Please note that we're not able to help with implementations here. However if you're still experiencing this with Action Scheduler core, please reply back with documented detail steps to reproduce the issue consistently and we'll re-open this.
