### ISSUE TITLE
Set schedule action Timezone

### ISSUE THREAD

**Issue by bambootb** [woocommerce/action-scheduler#638]
Hi, I would like to know how to set a timezone on schedule action at the moment it set as default +0000 which isn't practical for me to check or see when it will be execute on my timezone which is GMT+7. 

Can anyone please show me the way to set this, thank you so much. 

![image](https://user-images.githubusercontent.com/25810154/97885140-92f8b600-1d59-11eb-882b-32b82461316e.jpeg)

Best,
T

**Comment by crstauf** [comment]
This has been discussed previously and labeled as `wontfix`: https://github.com/woocommerce/action-scheduler/issues/537#issuecomment-638397130.

> check or see when it will be execute on my timezone

The Scheduled Date value has a relative readout which works regardless of your timezone. At the time of your screenshot, the `terawallet_auto_credit` action would run in 23 hours and 29 minutes.

**Comment by roykho** [comment]
Closing this as it has been discussed in #537
