### ISSUE TITLE
Question: Best Hook to Use

### ISSUE THREAD

**Issue by bhubbard** [woocommerce/action-scheduler#639]
Hi woo team,

I want to build a quick integration for action-scheduler and slack. Would like a quick way to see action-schedular activity in a slack channel. What would be the best hook or hooks to use?

**Comment by roykho** [comment]
Hi there,

Thanks for your question but unfortunately this is an area to submit reproducible bugs and not a place to ask for extensibility questions. However to point you in the right direction, try searching through the codebase for `do_action` hooks. This will list all the hooks available in which you can use.

I hope that helps.
