### ISSUE TITLE
Searching for idea how to use action-scheduler with my case

### ISSUE THREAD

**Issue by oshrib** [woocommerce/action-scheduler#640]
Hi
I have woocommerce website with 3,000 products.

I have function that changes automatically the products prices if they are not equal to my competitors (i scrapping external website that have all the prices of my competitors).

I need this function to run once per 4 hours.
This function includes While loop.

As the external site not allowed more than 6 enters per 1 minute, i must to limit my while-loop to work on 5 products each time the while loop runs.

`$args= array(
'post_type' => 'product',
'posts_per_page' => 5,`

What is the best way to schedule while loop like this by action-scheduler each 4 hours?

Thanks.

**Comment by oshrib** [comment]
Maybe to use the action-scheduler with while loop without the 
'posts_per_page' => 5
Just using sleep(10) function, to sleep after each run of the loop for 10 seconds... what will bring me to run through 5-6 products per 1 minute?

**Comment by roykho** [comment]
Hi @oshrib - unfortunately we do not support implementations here. This is a place to submit reproducible bugs. Please try submitting your question here https://wordpress.org/support/plugin/action-scheduler Thanks!
