### ISSUE TITLE
WP-CLI command support to create missing AS related DB tables

### ISSUE THREAD

**Issue by lukecav** [woocommerce/action-scheduler#641]
There should be a way to force missing Action Scheduler DB tables from WP-CLI.

https://actionscheduler.org/wp-cli/

**Comment by roykho** [comment]
> force missing Action Scheduler DB tables

That or have logic in place to just create the tables before anything runs.

**Comment by barryhughes** [comment]
We forgot to close this after merging #676. Closing now!
