### ISSUE TITLE
Sending large number of emails

### ISSUE THREAD

**Issue by MehbubRashid** [woocommerce/action-scheduler#642]
Hi, i have 10,000 unique id saved in my database...i have a function which can make a curl request to an api with a unique id and the api returns the email address for that unique id.then i use wp_mail to send an email..if i want to process the whole 10000 unique id and send email to them in background, what should be my approach?

How much email i should process in per action execution?

I thought of processing 10 emails per run and after completing 10 emails, the single schedule action will be called again within itself (like a recursive function) using the current time as timestamp which will process the next 10 items. Is this method okay?

Thanks in advance

**Comment by roykho** [comment]
Hi @MehbubRashid - Unfortunately we do not support implementations here. This is a place for submitting reproducible bugs that requires developer attention. You can however try your question here https://wordpress.org/support/plugin/action-scheduler Thanks for your understanding.
