### ISSUE TITLE
Unable to query for multiple status with DBStore

### ISSUE THREAD

**Issue by alexmigf** [woocommerce/action-scheduler#643]
Currently I'm unable to query actions using `DBStore` for multiple status. I'm building a list table for a plugin with `failed` and `complete` status and I'm unable to do this with one query.

Do you want me to open a Pull Request that addresses this?

Let me know your thoughts.

**Comment by lkraav** [comment]
Have you identified where in AS source this gets blocked?

**Comment by alexmigf** [comment]
I believe it's here https://github.com/woocommerce/action-scheduler/blob/c899c34a06a987c5143218672c6c9e544c73fed4/classes/data-stores/ActionScheduler_DBStore.php#L313-L316

**Comment by roykho** [comment]
Hey @alexmigf - Thanks for reporting. Yes please feel free to submit a PR and we'll take a look.

**Comment by barryhughes** [comment]
Added as part of https://github.com/woocommerce/action-scheduler/pull/688 (for all stores).
