### ISSUE TITLE
WC Emails can't be sent with async requests

### ISSUE THREAD

**Issue by vdwijngaert** [woocommerce/action-scheduler#647]
I'm running into an issue where emails that are triggered using an async request (as opposed to WP-CLI) don't get triggered. This happens in some of my emails getting sent, while others don't.

As far as I can see, the action hook runs alright, but it seems that on async requests, this happens before the `woocommerce_email_classes` filter is called (you're only supposed to init your WC_Mail classes in this hook). So it appears as though there's a discrepancy in where in the WP lifecycle the actions get called. 

The ability to delay sending emails and save time during the main request itself is a big plus, gracefully handled by action-scheduler. This issue makes this totally unreliable however... Or am I missing something?

**Comment by vdwijngaert** [comment]
I see things like `WC_Background_Mailer` and `WC_Mails::queue_transactional` exist, so I should probably look into using those... 

Anyhow, I found this solves my problem:

```php
add_action('action_scheduler_run_queue', function() {
    if(!class_exists('WC_Emails')) {
        return;
    }

    WC_Emails::instance();
}, -1);
```

**Comment by barryhughes** [comment]
That seems like a reasonable solution.

I'll go ahead and close this, though, because we have some workarounds noted above (thanks!), plus it seems less like an issue with Action Scheduler itself, and more a matter of something that the callback logic needs to be aware of and handle as needed.
