### ISSUE TITLE
WP_CLI is checked with defined. isset should be used instead

### ISSUE THREAD

**Issue by olegabr** [woocommerce/action-scheduler#648]
```
If you want to see if a variable exists, use isset() as defined() only applies to constants. If you want to see if a function exists, use function_exists().
```
https://www.php.net/manual/en/function.defined.php

https://github.com/woocommerce/action-scheduler/blob/c899c34a06a987c5143218672c6c9e544c73fed4/classes/WP_CLI/Migration_Command.php#L31
https://github.com/woocommerce/action-scheduler/blob/c899c34a06a987c5143218672c6c9e544c73fed4/classes/WP_CLI/ProgressBar.php#L45
https://github.com/woocommerce/action-scheduler/blob/c899c34a06a987c5143218672c6c9e544c73fed4/classes/WP_CLI/ActionScheduler_WPCLI_QueueRunner.php#L31
https://github.com/woocommerce/action-scheduler/blob/c899c34a06a987c5143218672c6c9e544c73fed4/classes/migration/Controller.php#L120
https://github.com/woocommerce/action-scheduler/blob/c899c34a06a987c5143218672c6c9e544c73fed4/classes/abstracts/ActionScheduler.php#L167
https://github.com/woocommerce/action-scheduler/blob/c899c34a06a987c5143218672c6c9e544c73fed4/classes/migration/Runner.php#L60

**Comment by olegabr** [comment]
found it: https://wordpress.stackexchange.com/a/226163/137915
But the constant defined on line 4: https://github.com/wp-cli/wp-cli/blob/71626710db27d5202e4df063c5b664fd5eb6615c/php/wp-cli.php#L4 is replaced with class definition included on line 16: https://github.com/wp-cli/wp-cli/blob/71626710db27d5202e4df063c5b664fd5eb6615c/php/wp-cli.php#L16: 

Class defined in a global namespace: https://github.com/wp-cli/wp-cli/blob/71626710db27d5202e4df063c5b664fd5eb6615c/php/class-wp-cli.php

Not sure if/how constant and class can exists simultaneously with the same name :-(

**Comment by rrennick** [comment]
> Not sure if/how constant and class can exists simultaneously with the same name :-(

@olegabr I'm closing this issue as you will see the same checks and usage in any plugin that adds a WP CLI command. 

To briefly answer your question: in PHP the usage of constants and classnames do not overlap. Based on usage, PHP determines whether `WP_CLI` refers to the class or the constant.
