### ISSUE TITLE
Spike: Research the best way to detect when MySQL is out of temporary space

### ISSUE THREAD

**Issue by jonathansadowski** [woocommerce/action-scheduler#650]
There's a suggestion that #634 could be solved if we added a check to see if MySQL is out of temporary space.

Desired outcome of this spike: proposal for a way to detect MySQL has exhausted its temporary space and an understanding of whether or not we could apply that detection toward solving #634.

**Comment by barryhughes** [comment]
Some relevant docs/articles:

- [MySQL Docs ▸ How MySQL Handles a Full Disk](https://dev.mysql.com/doc/refman/8.0/en/full-disk.html)
- [Cyberciti ▸ MySQL Error 28 and Solution](https://www.cyberciti.biz/faq/mysql-error-28-and-solution/)

Possibly we can detect this specific error (whether that's through exception handling, or by inspecting `$wpdb->last_error`, or some other approach) and then we could perhaps put a temporary pause on further queue processing [(as proposed here)](https://github.com/woocommerce/action-scheduler/issues/634#issuecomment-717704510).

However, we also recently added an [extra set of safety checks](https://github.com/woocommerce/action-scheduler/pull/668) to prevent the AS-specific problem of actions being processed ahead-of-time. With that in place, I'm wondering if there is still value in doing more research here, or if this can be closed.

cc @jonathansadowski @vedanshujain

**Comment by barryhughes** [comment]
Closing, since #634 was merged some time back and should avoid the core issue of actions being inadvertently processed ahead of schedule.
