### ISSUE TITLE
The shutdown action is conflicting with other plugins

### ISSUE THREAD

**Issue by Kubitomakita** [woocommerce/action-scheduler#652]
Hi, when the `action_scheduled_run_queue` event is running in WP Cron, I noticed that no other actions hooked to `shutdown` runs, doesn't matter what priority they are registered with.

Easy way to replicate:

```php
add_action( 'custom_cron_event', function() {
	add_action( 'shutdown', function() {
		file_put_contents(
				dirname( __FILE__ ) . '/shutdown-event.log',
				print_r( 'This will never execute', true ) . "\r\n\r\n",
				FILE_APPEND
		);
	});
});
```

When the `custom_cron_event` runs without the `action_scheduled_run_queue`, it correctly runs the `shutdown` action.

**Comment by rrennick** [comment]
> When the custom_cron_event runs without the action_scheduled_run_queue

@Kubitomakita WordPress cron only runs one event/hook on each cron run. No two cron events are going to run at the same time. If I have misunderstood the issue you are describing can you please provide all the information needed to reproduce the issue.

**Comment by Kubitomakita** [comment]
Thanks for the reply @rrennick!

You are wrong about the cron. It [loops over all the due events](https://github.com/WordPress/WordPress/blob/master/wp-cron.php#L112) and executes the action one by one.

Steps to reproduce:
1. Install Action Scheduler as a plugin or another plugin that is using it, we tested with WooCommerce and RankMath SEO
2. Create a new custom event with the `custom_cron_event` hook and 1-minute schedule
3. Add `custom_cron_event` callback as in my first message
4. Wait until both `custom_cron_event` and `action_scheduled_run_queue` events are queued to be run, run the cron
5. `custom_cron_event` won't log anything, because `action_scheduled_run_queue` prevents the other `shutdown` callback to run

Of course, when the `custom_cron_event` event runs in a particular cron run, it logs into the file properly, but only when `action_scheduled_run_queue` wasn't running along with it.

Let me know if I should clarify more!

**Comment by rrennick** [comment]
@Kubitomakita I created the following cron schedule
<img width="1551" alt="Screen Shot 2021-01-21 at 10 28 57 AM" src="https://user-images.githubusercontent.com/343847/105364480-9589df80-5bd3-11eb-954a-be0cfb98e115.png">

Added the following code to a test plugin:

```
$my_cron_event_ran = false;
add_action( 'my_cron_event', 'my_cron_event_handler' );
function my_cron_event_handler() {
	global $my_cron_event_ran;
	$my_cron_event_ran = true;
	error_log( __FUNCTION__ . ' ran' );
}
add_action( 'shutdown', 'my_cron_event_shutdown' );
function my_cron_event_shutdown() {
	global $my_cron_event_ran;
	$message = 'My cron event ' . ( $my_cron_event_ran ? 'ran' : 'did not run' );
	error_log( $message );
}
add_action( 'action_scheduler_run_queue', function() {
	error_log( 'AS queue run' );
}, 0 );
```

I closed all connections to the site and waited until both the queue runner and `my_cron_event` would be pending. Repeated that a second time. This produced the following log:

```
[21-Jan-2021 14:07:23 UTC] My cron event did not run
[21-Jan-2021 14:07:23 UTC] AS queue run
[21-Jan-2021 14:07:23 UTC] My cron event did not run
[21-Jan-2021 14:07:35 UTC] My cron event did not run
[21-Jan-2021 14:07:35 UTC] my_cron_event_handler ran
[21-Jan-2021 14:07:35 UTC] My cron event ran
[21-Jan-2021 14:07:37 UTC] My cron event did not run
[21-Jan-2021 14:15:39 UTC] AS queue run
[21-Jan-2021 14:15:39 UTC] my_cron_event_handler ran
[21-Jan-2021 14:15:39 UTC] My cron event ran
[21-Jan-2021 14:15:39 UTC] My cron event did not run
[21-Jan-2021 14:15:40 UTC] My cron event did not run
[21-Jan-2021 14:15:40 UTC] My cron event did not run
[21-Jan-2021 14:15:41 UTC] My cron event did not run
[21-Jan-2021 14:28:35 UTC] My cron event did not run
[21-Jan-2021 14:28:35 UTC] AS queue run
[21-Jan-2021 14:28:35 UTC] my_cron_event_handler ran
[21-Jan-2021 14:28:35 UTC] My cron event ran
[21-Jan-2021 14:28:36 UTC] My cron event did not run
[21-Jan-2021 14:28:36 UTC] My cron event did not run
[21-Jan-2021 14:28:36 UTC] My cron event did not run
[21-Jan-2021 14:28:37 UTC] My cron event did not run
[21-Jan-2021 14:28:43 UTC] My cron event did not run
[21-Jan-2021 14:28:45 UTC] My cron event did not run
```

The log shows that each cron event ran on a separate request and that the `shutdown` hook does run after the AS queue runner.

I'm closing this issue. If you can reproduce this issue in an install with only AS or WooCommerce active and a default theme using the test code above please let us know and we can re-open the issue.

**Comment by Kubitomakita** [comment]
I just wanted to confirm that you're right, the problem is not with Action Scheduler. All the actions in a given cron batch are executing as well as the shutdown action on the end.
