### ISSUE TITLE
Check the existence of the actions table before attempting a migration (or at the appropriate place)

### ISSUE THREAD

**Issue by Konamiman** [woocommerce/action-scheduler#653]
Context: https://github.com/woocommerce/woocommerce/issues/25997, https://github.com/woocommerce/woocommerce/issues/25895, https://github.com/woocommerce/action-scheduler/issues/587

While the actions table shouldn't disappear in the first place, it would be a good idea to add a check for the table existence for robustness. Maybe checking before any access to the table would be overkill (and hurt performance), but the check should happen at least for some critical workflows (e.g. [when the absence of the table prevents activating WooCommerce](https://github.com/woocommerce/woocommerce/issues/25997#issuecomment-706685432), I have done some research on that case and it seems to be linked to migrations).

**Comment by barryhughes** [comment]
It sounds like some users [are still in need of this](https://github.com/woocommerce/action-scheduler/issues/577#issuecomment-867865784) in respect of the `wpPostStore` → `DBStore` migration.
