### ISSUE TITLE
How to force async action to process immediately?

### ISSUE THREAD

**Issue by gavin310** [woocommerce/action-scheduler#654]
In `init` I'm calling `as_enqueue_async_action` and adding the action handler below it:

```
add_action( 'init', function() {
    as_enqueue_async_action( 'my_test_hook', ['test' => 'hello'] );
} );

add_action( 'my_test_hook', function( $args ) {
    error_log( 'here' );
}, 10, 1 );
```

The problem is that the action isn't fired until I perform some action, like refreshing the page or when admin ajax starts polling. I know this is related to how WP Cron works, but is it possible to have the Action Scheduler being processing the action right away?

On another note, are there any Action Scheduler usage examples other than the `eg_midnight_log` example?

**Comment by crstauf** [comment]
@gavin310 You could trigger a request to WP Cron immediately after enqueuing the async action using [`spawn_cron()`](https://developer.wordpress.org/reference/functions/spawn_cron/).

**Comment by crstauf** [comment]
You could also use [`as_get_scheduled_actions()`](https://github.com/woocommerce/action-scheduler/blob/master/functions.php#L219) to retrieve your action's object, and then run the object's [`execute()`](https://github.com/woocommerce/action-scheduler/blob/master/classes/actions/ActionScheduler_Action.php#L21) function, though this wouldn't occur in a separate HTTP request, so would slow down the current request.

There may be some way to manually spawn the AS queue in a separate HTTP request, but I'm not confident on if/how this is done.

**Comment by gavin310** [comment]
Thanks @crstauf that's a good idea. I'll experiment with `spawn_cron()`. I definitely don't want to use anything that will process the action in the same request, since I'll be doing PDF generation and one action could take over a minute to complete. Thanks again!

**Comment by crstauf** [comment]
Welcome! 🙇

**Comment by gavin310** [comment]
Hey @crstauf,

I'm not able to get `spawn_cron` to begin processing the job right away. I'm hoping there's something wrong with my code rather than `spawn_cron` not being able to do what I want. Would you mind glancing at this quickly and seeing if there's something wrong?

From some answers on StackOverflow it seems `spawn_cron` should do what I want, at least with WP Cron, but maybe it doesn't work with Action Scheduler?

```
add_action( 'init', function() {
	if ( !empty( $_GET['as-test'] ) && $_GET['as-test'] === '1' ) {
		as_enqueue_async_action( 'background_process_test_hook', array( 'args' => ['test1' => 'hello', 'test2' => 'hello2', 'hello3'] ), 'mygroup' );
		spawn_cron();
	}
} );

add_action( 'background_process_test_hook', function( $args ) {
	if ( is_array( $args ) ) {
		foreach ( $args as $key => $value ) {
			error_log( sprintf( '%s: %s', $key, $value ) );
		}
	}
}, 10, 1 );
```

Thanks,
Gavin

**Comment by gavin310** [comment]
@crstauf Actually what I'm thinking now is that maybe `spawn_cron` _is_ working, but when they say it sends a request to start processing cron jobs, it doesn't mean it'll handle them immediately.

**Comment by gavin310** [comment]
Alright, I decided to give https://github.com/deliciousbrains/wp-background-processing a try and that's actually handling my async processes immediately, so I'm going to go with that. I wanted to use Action Scheduler because it seems like it'll be well-maintained long into the future, but I need immediate processing :)

**Comment by barryhughes** [comment]
Glad you found a solution that works for you :-)

I'll go ahead and close this issue.
