### ISSUE TITLE
Schedule for 3.2.0?

### ISSUE THREAD

**Issue by samimakela** [woocommerce/action-scheduler#655]
We're experiencing a significant amount of database deadlocks, which are discussed https://github.com/woocommerce/action-scheduler/issues/530 and addressed in https://github.com/woocommerce/action-scheduler/pull/535

Is there any estimation on when 3.2.0 will be released?

The deadlocks are currently filling up our error log. It seems that we are not the only ones experiencing issues with this one.

**Comment by barryhughes** [comment]
Hi @samimakela—apologies for the late response here. [3.2.0](https://github.com/woocommerce/action-scheduler/releases/tag/3.2.0) has now been released and you can [grab it from wordpress.org](https://downloads.wordpress.org/plugin/action-scheduler.3.2.0.zip), or even directly from GitHub if you prefer.
