### ISSUE TITLE
Modifying schema via custom plugin

### ISSUE THREAD

**Issue by samimakela** [woocommerce/action-scheduler#659]
While we wait for 3.2.0 to be released, we'd like to explore the option of updating the DB schema via a custom plugin. How would you recommend we do this? 

Essentially we'd like to achieve the same end result as in https://github.com/woocommerce/action-scheduler/pull/535

**Comment by barryhughes** [comment]
HI @samimakela,

GitHub is primarily a place to report bugs and we can't generally help with custom coding tasks (which this essentially would be, though of course we appreciate the motivations for wanting to do this).

Some possibilities you could explore:

1. Installing Action Scheduler as a standalone plugin and either checking out a commit that contains this fix or else, to reduce the number of changes you are introducing, you could use a fork with _only the modification in the linked PR applied_ (and increment the plugin version number, to ensure your custom version loads in preference to that bundled with WooCommerce, assuming you are also using that plugin).
2. Alternatively, extract the revised table definition and pass it through `dbDelta()` from a custom plugin.

I hope that helps, but please do take appropriate care (in terms of making sure you have a back-up and a roll-back plan).
