### ISSUE TITLE
Security Issue in Controller.php

### ISSUE THREAD

**Issue by amberhinds** [woocommerce/action-scheduler#664]
Hello!

We've included Action Scheduler in one of our plugins (thank you!) and while doing security audits on our plugin, identified problems related to Action Scheduler.

We ran the plugin through [WP Engine's linting test](https://github.com/wpengine/wpengine-coding-standards/) which helps identify best practices and potential problems. For this process, we are using [PHP Codesniffer](https://tracking.cirrusinsight.com/4bd98769-7476-4065-a754-2ca80b4094d2/github-com-squizlabs-php-codesniffer) with rules derived from both the [WordPress Coding Standards](https://tracking.cirrusinsight.com/4bd98769-7476-4065-a754-2ca80b4094d2/github-com-wordpress-coding-standards-wordpress-coding-standards) and [PHPCompatibility rulesets](https://tracking.cirrusinsight.com/4bd98769-7476-4065-a754-2ca80b4094d2/github-com-wimg-phpcompatibility). Below is a detailed line-by-line report of the sniff violation.  

Can you please let me know if these are actual errors that require fixes? If so, we may be able to submit a pull request with fixes.

```
FILE: /includes/action-scheduler/classes/migration/Controller.php
------------------------------------------------------------------------------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
------------------------------------------------------------------------------------------------------------------------------------------
 142 | ERROR | All output should be run through an escaping function (see the Security sections in the WordPress Developer Handbooks),
     |       | found '__'. (WordPress.Security.EscapeOutput.OutputNotEscaped)
------------------------------------------------------------------------------------------------------------------------------------------
```

**Comment by barryhughes** [comment]
Hi @amberhinds—thanks for this!

:memo: As a friendly note for the future, I'd ask first of all that you report any other security issues via [HackerOne](https://hackerone.com/automattic/). This is our preferred way to handle possible security issues (and I'll make a note to update our _readme_ file to make this clearer, as I don't think we currently cover this).

So to the specific issue, I agree with the linter: we should swap `__()` for `esc_html__()`. If you are happy to submit a pull request we'd appreciate it, or else we'll do our best to circle back and make the change from our side.

Thanks again!
