### ISSUE TITLE
Action Scheduler with external cronjob

### ISSUE THREAD

**Issue by NiekeRoos** [woocommerce/action-scheduler#669]
Hello,

I'm relatively new to this, so forgive me if this isn't the right place to pose my question.

We're using Action Scheduler together with Woocommerce Subscriptions to automatically generate subscription renewals. We would like to do this with an external cronjob instead of WP Cron. However, disabling WP Cron stops the action_scheduler_run_queue from executing pending renewal order requests. So we need a way to run the Action Scheduler with WP Cron disabled.

I gather from the FAQ that there are a couple of ways to do this:
1. ActionScheduler::runner()->run(); (but I don't know where to put this code);
2. do_action( 'action_scheduler_run_queue', $context_identifier ); (but I don't know what to use as context identifier);
3. WP CLI (but I don't know the exact call, wp-cli action-scheduler run or wp cron action-scheduler run?);
4. an async queue runner (but again I don't know the exact call and where to put it).

What's the best way and how do we exactly go about this? Your help is much appreciated.

Regards,
Nieke.

**Comment by aheckler** [comment]
3773031-zen as well. @mdmoore had one yesterday also.

**Comment by ovidiul** [comment]
Option 3. might work best, use WP CLI to first list the available scheduled actions like

```
wp cron event list
```

you should see the `action_scheduler_run_queue` there, then launch it with

```
wp cron event run action_scheduler_run_queue
```

This [comment](https://github.com/woocommerce/action-scheduler/issues/672#issuecomment-791368243) might help.

**Comment by barryhughes** [comment]
In addition to the options in the last comment, [per the docs](https://actionscheduler.org/wp-cli/)—which also include details of various flags and options you can specify—it is possible to execute the following:

`wp action-scheduler run`

You can do this manually, or add it to crontab as required. Hope that helps!
