### ISSUE TITLE
Automatic Migration to Action Scheduler from Native WP Cron

### ISSUE THREAD

**Issue by iamsayan** [woocommerce/action-scheduler#670]
I have written a plugin to automatically Migrate all WordPress Existing and future Cron Events to the Action Scheduler Library on WordPress version >=5.1.0. So, I just want to share my work. Hope it will help others.

Here is the GitHub Link: https://github.com/iamsayan/migrate-wp-cron-to-action-scheduler
And WordPress.org Link: https://wordpress.org/plugins/migrate-wp-cron-to-action-scheduler/

Thanks!

**Comment by barryhughes** [comment]
Thank you for sharing 😺
