### ISSUE TITLE
High traffic/transactional E-commerce site

### ISSUE THREAD

**Issue by cwhockey31** [woocommerce/action-scheduler#672]
Hi - I've been using Action Scheduler for about 6 months and it's helped a lot by spreading transactions and scheduled actions out so they're not all happening at once and crashing the site.  However, I need them to happen faster...  When we have 3000 subscription payments come through in one day, the scheduled actions are backed up over 24 hours to run the payments and any other scheduled actions including cron jobs.

I saw the High Volume Action Scheduler script in the documentation and am going to try that out.  We use liquidweb for hosting... one server for php and one for the SQL databases.

Another example would be today... we had a large blast sent out and it bogged down the website... not because of the high traffic, but because of the orders trying to come through within seconds/minutes of each other.

I think I might need to go the CLI route though... is there anyone you recommend that can help set this up and optimize our website for processing all of these transactions.

**Comment by lkraav** [comment]
> I think I might need to go the CLI route though... is there anyone you recommend that can help set this up and optimize our website for processing all of these transactions.

Absolutely, CLI cron is a must. It's mostly as simple as:

```
# https://easyengine.io/tutorials/wordpress/wp-cron-crontab/
*/5 * * * * /usr/local/bin/php /usr/local/bin/wp --path=$HOME/www --quiet cron event run --due-now # > /dev/null 2>&1
```

I have `/dev/null` redirect commented out, ready to be commented back in, in case of any ugly high-volume cron notification spam bug temporarily occurs.

**Comment by ovidiul** [comment]
Looking at this [doc](https://actionscheduler.org/perf/#increasing-initialisation-rate-of-runners) on increasing the rate of runners, it would be ideal if that could be done without a backend HTTP call, this needs to take into account that the CLI containers could run separately from the website itself, and to also take into consideration, for instance, the use of this plugin https://github.com/Automattic/Cron-Control for high load parallel events on distributed containers.

It would be ideal if for instance, to run 3 parallel batches, the user could setup 3 cron separate processes as:

```
# https://easyengine.io/tutorials/wordpress/wp-cron-crontab/
*/5 * * * * /usr/local/bin/php /usr/local/bin/wp --path=$HOME/www --quiet cron event run action_scheduler_run_queue # > /dev/null 2>&1
*/5 * * * * /usr/local/bin/php /usr/local/bin/wp --path=$HOME/www --quiet cron event run action_scheduler_run_queue_1 # > /dev/null 2>&1
*/5 * * * * /usr/local/bin/php /usr/local/bin/wp --path=$HOME/www --quiet cron event run action_scheduler_run_queue_2 # > /dev/null 2>&1
```

I did some tests and it seems this could work because of the current claiming mechanism, would you see a reason not to make this option available?

**Comment by barryhughes** [comment]
Hi @ovidiul ... you should be able to process multiple batches concurrently, but it does require some setup work. Set the max this way (let's suppose you want upto 5 batches to be processed concurrently):

```php
add_filter( 'action_scheduler_queue_runner_concurrent_batches', function() {
	return 5;
} );
```

You can then trigger multiple runners. If you want to kick off five queue runners, for instance, you could do this (zsh-style):

```zsh
repeat 5 { wp action-scheduler run & }
```

In relation to adding this or something similar to crontab, I'll just note that if the number of permitted concurrent batches is exceeded, execution should end _('There are too many concurrent batches')._ Does that sort of thing meet your needs, or would you still need a different strategy?

**Comment by ovidiul** [comment]
That would work @barryhughes, just thinking, if we are to add multiple cron events to run this automatically in parallel, will that introduce any issues with concurrency runners?

**Comment by barryhughes** [comment]
Well, supposing we allow upto 5 claims to be processed concurrently. _Ideally,_ when a new queue runner starts:

* If it detects that 5 claims are already in the midst of being processed, it will bail out.
* If there are no unclaimed pending actions it will also bail out.

So with this strategy (where you launch 5 new queue runners every minute, via cron) you have the potential to kick-off 5 new claims every minute but, if that number is not needed, the excess queue runners will quickly 'stand down'. However, some potential negatives:

* More concurrency, more potential for deadlocks as they set about claiming actions.
* More potential for overhead as the queue runners 'race' to claim pending actions, with some of those claims failing.

With that in mind, it is possibly better to stagger the creation of new queue runners if you can. For example, if you create a single runner every minute via `* * * * * wp action-scheduler run` there is still the potential to have upto 5 claims being actively processed (suppose a single claim takes 10 minutes to complete, then a new queue runner will be added as each further minute passes by up until the limit is met).

Of course, you could reduce the interval below 1 minute if you get creative or switch to something other than cron for this purpose.

Does that help? If I've misunderstood the question definitely let me know!

**Comment by ovidiul** [comment]
Hi @barryhughes thanks for the clarifications, that indeed helps, I will try to run with that next time.
