### ISSUE TITLE
Exception thrown on duplicate calls to cancel_action

### ISSUE THREAD

**Issue by leewillis77** [woocommerce/action-scheduler#675]
Occasionally, it's possible that cancel_action() can be triggered on an action that is already cancelled. In my case this was happening through a race condition between two calls to `bulk_cancel_actions()`. 

`bulk_cancel_actions()` generates a list of actions to be cancelled, and then works through them calling `cancel_action()` on each in turn. If this returns a reasonable amount of items, it's possible that a second caller will generate a list of actions that the first is already planning on cancelling. It's likely that by the time the second caller comes to issue the `cancel_action()`, the first has already cancelled the action. 

In `cancel_action()`, [the code](https://github.com/woocommerce/action-scheduler/blob/3.1.6/classes/data-stores/ActionScheduler_DBStore.php#L458) assumes that if no rows were updated then an error has occured, and the following exception is thrown:

```
PHP Fatal error:  Uncaught InvalidArgumentException: Unidentified action 21312 in /Users/lee/sites/wc/wp-content/plugins/woocommerce-product-feeds/vendor/woocommerce/action-scheduler/classes/data-stores/ActionScheduler_DBStore.php:458
```

I'd suggest that an additional check is added before throwing an exception that verifies if the status of the action is already cancelled, and if so returns cleanly rather than throwing an error.

Happy to raise a PR if you agree with the approach.

**Comment by ObliviousHarmony** [comment]
Howdy @leewillis77,

Thank you for your report, as well as your interest in raising a PR to solve it. I'm not sure I like the idea of adding another database query here, given the performance goals of ActionScheduler.

I would be curious to learn more about what circumstance this bug occurs under for you. It looks like the `ActionScheduler_DBStore` itself [doesn't actually call `cancel_action` during bulk deletion](https://github.com/woocommerce/action-scheduler/blob/3.1.6/classes/data-stores/ActionScheduler_DBStore.php#L494). The only case I can think of where this would be possible is during migration when the [`ActionScheduler_HybridStore` class](https://github.com/woocommerce/action-scheduler/blob/3.1.6/classes/data-stores/ActionScheduler_HybridStore.php#L15) uses the [bulk deletion defined by `ActionScheduler_Store`](https://github.com/woocommerce/action-scheduler/blob/3.1.6/classes/abstracts/ActionScheduler_Store.php#L288). If this is indeed the case, a more comprehensive solution might be to address the bulk cancellation of the hybrid store.

**Comment by leewillis77** [comment]
You're right here. My analysis of the cause was off here - I blame my editor picking up the wrong class instance ;)

There's definitely a situation where this can happen though, although annoyingly I'm no longer seeing the error appear in my logs, and I'm struggling to reproduce the fault. I'll close this for now, and if it rears its head again I'll do a better job of nailing it down and open a fresh issue. Thanks!
