### ISSUE TITLE
How to make wordpress action-scheduler run only with wp-cli and not on wp-admin? 

### ISSUE THREAD

**Issue by eduardoarandah** [woocommerce/action-scheduler#682]
## Problem

Scheduled action times out on wp-admin, killing it

`unexpected shutdown: PHP Fatal error Maximum execution time of 60 seconds exceeded in /xxx/wp-includes/class-wp-image-editor-gd.php `

## Description

I've a scheduled job that takes longer than `max_execution_time` for php-fpm 

This is no problem when running via wp-cli because it's execution time is much longer:

`wp action-scheduler run`

However, when a user logs in, wp-cron is called on the frontend, killing it and its future executions. 

My guess is that wordpress `heartbeat` is calling wp-cron 
https://developer.wordpress.org/plugins/javascript/heartbeat-api

I've tried disabling cron via wp-config.php with no luck 
`define("DISABLE_WP_CRON", true);`

## Question

How to make wp-cron or action-scheduler run only on wp-cli and not on the frontend?

**Comment by rrennick** [comment]
@eduardoarandah Sorry to hear you are having an issue with it. You can disable the cron and async runner by installing https://github.com/woocommerce/action-scheduler-disable-default-runner.

**Comment by eduardoarandah** [comment]
Thanks @rrennick ! 

If you got here searching for the answer, that plugin mentioned has this code, which can be included in your `functions.php` file

```
function asdds_disable_default_runner() {
	if ( class_exists( 'ActionScheduler' ) ) {
		remove_action( 'action_scheduler_run_queue', array( ActionScheduler::runner(), 'run' ) );
	}
}
// ActionScheduler_QueueRunner::init() is attached to 'init' with priority 1, so we need to run after that
add_action( 'init', 'asdds_disable_default_runner', 10 );
```
