### ISSUE TITLE
Composer install has wp-content folder in theme

### ISSUE THREAD

**Issue by imcodingideas** [woocommerce/action-scheduler#683]
When you install this with composer it installs in my theme a wp-content folder with lib and other things..

Why?

Anyone use sage theme?

**Comment by sanzeeb3** [comment]
That's the default path: `theme/wp-content/woocommerce/action-scheduler`, I'm not sure where is that coming from. But in your theme's composer.json you can use:

```
  "extra": {
    "installer-paths": {
      "vendor/{$vendor}/{$name}/": ["woocommerce/action-scheduler"]
    }
  }
```

which adds AS to `theme/vender/woocommerce/action-scheduler`, assuming you already have `composer/installers` required.

**Comment by eduardoarandah** [comment]
@sanzeeb3 I did it and it installed fine, inside `vendor/woocommerce/action-scheduler`

```
Installing dependencies from lock file (including require-dev)
Package operations: 1 install, 0 updates, 0 removals
  - Installing woocommerce/action-scheduler (3.1.6): Extracting archive
```

Next problem is, functions aren't recognized when running the server

`Call to undefined function as_next_scheduled_action()`

- Tried this: `\as_next_scheduled_action()`
- Tried `composer dump-autoload`

Whats weird is that intelephense language server recognizes the function alright:

![image](https://user-images.githubusercontent.com/4065733/113445364-fc392f80-93b2-11eb-94ce-35274ab56eca.png)

I also noticed package installed without a composer.json file. 

![image](https://user-images.githubusercontent.com/4065733/113445882-dc563b80-93b3-11eb-8ae4-c1e8848bb4f9.png)

**What could be happenning?**

**Comment by sanzeeb3** [comment]
@eduardoarandah composer.json won't be included in the package - you don't need that either. The function `as_next_scheduled_action()` isn't being recognized is a different problem. `\as_next_scheduled_action()` is only required when your file is namespaced. So, what is the full error message you're getting, and do you have the same problem when the function is called from elsewhere such as functions.php, etc,?

**Comment by eduardoarandah** [comment]
@sanzeeb3 thanks for your help! 

Here's how to reproduce:

In the theme (I'm using roots/sage https://github.com/roots/sage) 

Added to composer.json section:

```
  "extra": {
    "installer-paths": {
      "vendor/{$vendor}/{$name}/": ["woocommerce/action-scheduler"]
    }
  }

```

then:

```
composer require woocommerce/action-scheduler
```

check it's there:

```
cat vendor/woocommerce/action-scheduler/action-scheduler.php | grep Version:
* Version: 3.1.6
```

Move to your public folder and load wordpress in repl php

```
cd ../../../
php -a
require "wp-load.php";
```

Check functions exist:

```
php > echo function_exists('get_option'); # check wordpress function
1

php > echo ActionScheduler::class; # does exist
ActionScheduler

php > echo function_exists('as_next_scheduled_action'); # doesn't exist
php >
```

Is this helpful?

**Comment by imcodingideas** [comment]
@ObliviousHarmony any ideas?

**Comment by ObliviousHarmony** [comment]
Sorry for the wait @imcodingideas!

We have this [Usage Guide](https://actionscheduler.org/usage/) that covers how to use this package in the two main contexts we support. This package does not make use of Composer autoloading and must be included to be used.

**Comment by marijnbent** [comment]
For people searching a solution to be used today:

1. Change the installer path and, if using Imposter, exclude it.
```
    "extra": {
        "imposter": {
            "namespace": "...",
            "excludes": ["woocommerce/action-scheduler"]
        },
        "installer-paths": {
            "vendor/{$vendor}/{$name}/": ["woocommerce/action-scheduler"]
        }
    }
``` 

2. Create a file that requires action-schedular.php
```
class ScheduledActionController {

	public function __construct() {

		require_once( WORDPROOF_DIR_VENDOR . '/woocommerce/action-scheduler/action-scheduler.php');

	}
}
```

3. Load the file on plugins_loaded
```
add_action('plugins_loaded', [$this, 'setup'], -10);

...

public function setup() {
	new ScheduledActionController();
}

```
