### ISSUE TITLE
Make current subsubsub link clickable

### ISSUE THREAD

**Issue by abuyoyo** [woocommerce/action-scheduler#685]
ie. When on the Pending status-page - The "**Pending**" item is not a link. It should be a link.
That's how WordPress does it. That's how all plugins do it.

**Comment by barryhughes** [comment]
Hi @abuyoyo—nice observation, I'm sure we can make that change.

Out of curiosity, is the reason you want this simply to provide an alternative way of refreshing the page when you're looking at the list of pending actions?
