### ISSUE TITLE
Searching for and unscheduling tasks when $args are unknown

### ISSUE THREAD

**Issue by jonschr** [woocommerce/action-scheduler#687]
Is it possible to simply unschedule *all* upcoming actions on a particular hook, even if the $args are unknown? I ask this because I'm generating the $args based on some settings, and then when the settings change, I'm sometimes not able to unschedule recurring actions in time, which results in zombie recurring actions that just ... continue on.

It would be much simpler to clear the decks, so to speak, and just clear ALL scheduled actions off of a particular hook.

**Comment by crstauf** [comment]
`as_get_scheduled_actions()` should allow you to query actions by hook and not match by arguments. From there you'd have all the info needed to unscheduled the action.

**Comment by rrennick** [comment]
> Is it possible to simply unschedule all upcoming actions on a particular hook

[`as_unschedule_all_actions`](https://github.com/woocommerce/action-scheduler/blob/master/functions.php#L130) doesn't require that you match the `$args` if you provide a `hook` or `group`.

```
as_unschedule_all_actions( 'my_hook' );
```

**Comment by jonschr** [comment]
Facepalming all over the place right now. 

I tested this exact thing months ago when I started writing my code, and I must have typoed or something, because it didn't work. This will greatly simplify things, thank you!
