### ISSUE TITLE
Dropping Action Scheduler tables?

### ISSUE THREAD

**Issue by Luc45** [woocommerce/action-scheduler#690]
Howdy,

We decided to test Action Scheduler on our plugin, so we loaded the Action Scheduler, which created the tables on our user's sites as expected.

However, after one or two releases, we decided to remove it from our plugin due to internal reasons. We would like to know if there's a recommended approach for removing the leftover tables created by Action Scheduler, without conflicting with other plugins that might be using it?

**Comment by Luc45** [comment]
I thought about doing something like this minimalist example:

```php
// I'm hooking at "deactivate_plugin" to avoid running on every request.
// I need to double-check if there's a more approriate hook than "deactivate_plugin".
add_action('deactivate_plugin', function() {
  add_action('shutdown', function() {
    if (class_exists(\ActionScheduler::class)) {
      return;
    }
  
    // Drop Action Scheduler Tables if they exist, probably check if they are empty, too
  });
});

```

**Comment by barryhughes** [comment]
Hi @Luc45,

That's a really interesting question...but I'm afraid we don't have any recommended approaches for handling this, or not that I know of.

Probably the very best practice is for individual site operators to clean this up, once they are satisfied that those tables are no longer in use by any of their remaining plugins; but I'm assuming in your particular case you don't directly control the sites where your plugin is deployed and instead want to push out an update to your own plugin, and have it automagically determine if the tables can be cleaned up or not and go from there.

Testing if `ActionScheduler` exists late in the request (as you've outlined via the code snippet you shared) sounds like a pretty reasonable approach, but perhaps it needs to be backed up by additional tests and/or some sort of manual confirmation step? I'm just thinking here that it is possible that another plugin is present which also includes Action Scheduler, but:

* It has been temporarily deactivated, but still has various scheduled actions queued up that should still be processed upon reactivation.
* Or perhaps it includes AS but does not load it on every request (this would seem less likely, but then again it's hard to know what permutations exist in the wild).

Other heuristics to feel out if the AS tables are still needed, that might be considered:

* Checking to see if actions are queued up with a signature you don't recognize.
* Queuing up a test action and, after a reasonable interval of time, testing to see if it was processed.
* Testing to see if there was recent 'movement' in terms of processing actions that cannot be attributed to your own plugin.
* Some combination of the above, plus your own suggested strategy.

Giving the user the option to delete those tables or not (and presenting them with the findings of your tests) feels like at least the basis of a solution.

(cc @rrennick for any further ideas on this one)

**Comment by rrennick** [comment]
> We would like to know if there's a recommended approach for removing the leftover tables created by Action Scheduler, without conflicting with other plugins that might be using it?

If other plugins are using AS then you don't want to remove the tables. That's why AS doesn't remove them as part of its own deactivation/uninstall.

However, you can create actions with your own unique group. Then on uninstall or your use case, you can remove all the actions in that group. [See `as_unschedule_all_actions`](https://actionscheduler.org/api/)

**Comment by crstauf** [comment]
The check for any actions with a different group from your actions seems the best method to cleanup the tables, though certainly not perfect.

Probably best to leave this to the site's developer to determine and cleanup.
