### ISSUE TITLE
Please replace 404 link with new link

### ISSUE THREAD

**Issue by ravisoni6262** [woocommerce/action-scheduler#701]
Hello,
I was reading through this page [FQA](https://actionscheduler.org/faq/ )and found one link which is pointing on Github 404.

https://github.com/woocommerce/action-scheduler/blob/master/classes/ActionScheduler_WPCLI_QueueRunner.php

**Comment by barryhughes** [comment]
Thanks, @ravisoni6262 ... you're right, it probably should [point here](https://github.com/woocommerce/action-scheduler/blob/master/classes/WP_CLI/ActionScheduler_WPCLI_QueueRunner.php) instead. Will look into addressing this :+1:
