### ISSUE TITLE
WordPress database error Table

### ISSUE THREAD

**Issue by Gmulti** [woocommerce/action-scheduler#711]
Hello,

We use the library for our WP Umbrella plugin (https://wordpress.org/plugins/wp-health/) and we updated yesterday with your latest release.
However, we are receiving support with an error that we don't understand and can't fix: 

```
WordPress database error Table 'opkz21_opk2021z.wpkj_actionscheduler_logs' doesn't exist for query SHOW FULL COLUMNS FROM `wpkj_actionscheduler_logs` made by require('wp-blog-header.php'), 
require_once('wp-load.php'),
require_once('wp-config.php'), require_once('wp-settings.php'),
do_action('init'), WP_Hook->do_action, WP_Hook->apply_filters, WPHealth\Actions\TrackingError->init, as_schedule_single_action, 
ActionScheduler_ActionFactory->single, 
ActionScheduler_ActionFactory->store, 
ActionScheduler_DBStore->save_action, do_action('action_scheduler_stored_action'), 
WP_Hook->do_action, WP_Hook->apply_filters, 
ActionScheduler_Logger->log_stored_action, ActionScheduler_DBLogger->log
```

Could you tell us more about what to do or what our client should do?

**Comment by optimizegeek** [comment]
> Hi...
> 
> If that table is missing then your users can navigate to `Tools → Scheduled Actions` where they should see a message reading, _"It appears one or more database tables were missing. Attempting to re-create the missing table(s)."_ If they wait a moment and refresh, the message should be gone and the problem should be resolved.
> 
> Additionally/alternatively, from your own plugin, you could also run the following snippet as part of a migration routine to resolve this automatically:
> 
> ```
> ( new ActionScheduler_LoggerSchema() )->register_tables( true );
> ```
> 
> Can you tell me which version of Action Scheduler you were bundling within your plugin prior to the update? Ideally this would be handled seamlessly and transparently, so I'd love a little more information to help inform our picture of things 🙃

I own the website in question where the error above was quoted from, and the database table is not missing, and in fact I see some entries from back in May this year when I navigate to "tools >> scheduled actions" 

No mention on that screen about missing table (this was first time I ever seen that screen as well). 

This is a new (to me) problem as I never have had any errors like this previously. I'm on a very good VPS which rarely has issues, but I imagine there is something going on between WP Umbrella plugin and this Action Schedule that is causing the error.

My site goes down with the Critical Error warning, and not even able to login to WordPress at all unless I go rename the plugin or delete the plugin folder for WP Umbrella. 

![6ad07773-90d6-493f-b87c-781c76b3ac0a](https://user-images.githubusercontent.com/13683847/121441146-dac66800-c94e-11eb-8fc1-34085cf20041.png)

**Comment by Gmulti** [comment]
Thanks a lot for the additional information @optimizegeek 

For some it happens seamlessly but for others everything seems to be blocked and they would not be able to update the plugin.

We use the latest version **3.2.0** that we have just updated.

@barryhughes  don't hesitate to tell us if we are using it in the wrong way. You can download the plugin here : https://wordpress.org/plugins/wp-health

**Comment by barryhughes** [comment]
This may just be the result of information being sourced from different locations, however: in the screenshot two comments above, which I understand is from the same site as the initial error that was posted, it looks like the database prefix ends with `v9_` or perhaps `w9_` (though I can't be certain because of how it's cropped)...although in the opening notes the prefix seemed to be `wpkj_`.

If the log table definitely exists, and the table name etc is correct (and WPDB is connected to the correct database, etc), then I'm really not sure why this error would occur. What are your thoughts on the prefix discrepancy?

**Comment by optimizegeek** [comment]
> it looks like the database prefix ends with v9_ or perhaps w9_ (though I can't be certain because of how it's cropped)...although in the opening notes the prefix seemed to be wpkj_.

I have multiple sites (for testing only) on the same cPanel. The error message actually was for the top level domain but the screenshot is for the site in question. I get the same error on all the sites. I do have one site that does not have that database table, but as it doesn't have WooCommerce I can't get to "tools > action scheduler" 

Does that only show up when WooCommerce is activated on the site?

Apologies for my lack of knowledge on this as I have never dealt with Action Scheduler previously. 

It is possible the issue solved itself regarding the missing database table.

When I get an email about the critical error (from WordPress) it has the following at the bottom, although it seems cutoff at the end: 

`Error Details
=============
An error of type E_ERROR was caused in line 85 of the file /home/opkz21/public_html/wp-content/plugins/wp-health/vendor/woocommerce/action-scheduler/classes/data-stores/ActionScheduler_DBStore.php. Error message: Uncaught RuntimeException: Error saving action: ActionScheduler_Action::$args too long. To ensure the args column can be indexed, action args should not be more than 8000 characters when encoded as JSON. in /home/opkz21/public_html/wp-content/plugins/wp-health/vendor/woocommerce/action-scheduler/classes/data-stores/ActionScheduler_DBStore.php:85
Stack trace:
#0 /home/opkz21/public_html/wp-content/plugins/wp-health/vendor/woocommerce/action-scheduler/classes/ActionScheduler_ActionFactory.php(177): ActionScheduler_DBStore->save_action(Object(ActionScheduler_Action))
#1 /home/opkz21/public_html/wp-content/plugins/wp-health/vendor/woocommerce/action-scheduler/classes/ActionScheduler_ActionFactory.php(84): ActionScheduler_ActionFactory->store(Object(ActionScheduler_Action))
#2 /home/opkz21/public_html/wp-content/plugins/wp-health/vendor/woocommerce/action-scheduler/functions.php(36): ActionScheduler_ActionFactory->single('action_wp_umbre...', Array, 1623201917, 'umbrella_errors')
#3 /home/opkz21/public_html/wp-con
`

Appreciate the help :-)

**Comment by optimizegeek** [comment]
I think the issue is solved now with a patch from WP Umbrella.

I installed the patch and it did not crash the site like previously, and I was able to get into tools > scheduled actions 
On the site with the missing table, it went through normal process of detecting the issue and correcting it: 
![Scheduled Actions ‹ OP Kevin — WordPress - Google Chrome 2021-06-10 at 10 49 15 AM](https://user-images.githubusercontent.com/13683847/121557573-781aae00-c9da-11eb-9e80-1024bddc92a7.jpeg)

**Comment by barryhughes** [comment]
> Does that only show up when WooCommerce is activated on the site?

Yes, the `Tools → Scheduled Actions` screen should show up regardless of whether WooCommerce is active or not. If you don't see it then possibilities include a conflict of some kind with another plugin (or even your theme), or the user you logged in with may not have the required permissions.

> It is possible the issue solved itself regarding the missing database table.

Sounds good!

> When I get an email about the critical error (from WordPress) it has the following at the bottom ... `To ensure the args column can be indexed, action args should not be more than 8000 characters when encoded as JSON`

Just as the error notes, it's important to keep the size of the args passed to the scheduled action within reasonable bounds. 

In this case, it seems the limit is being exceeded. One way to solve this, on occasions where a potentially large payload needs to be passed across, is to store that data someplace else (for example, an option, transient or private custom post could be used to house data, and the args passed to Action Scheduler would simply reference that location).
