### ISSUE TITLE
Issue with DB tables causing stalled sync / empty list table

### ISSUE THREAD

**Issue by davedoesthings** [woocommerce/action-scheduler#718]
I'm having an issue on a client site where we use AS as part of a document syncing solution. I'll state early on that this is on a multi-site, and I recognise that AS isn't built for MS per se, **however**, the sub-sites do not use AS; all the actions run on the root site `1` using the `wp_*` tables. Generally speaking, AS is holding up wonderfully!

We've had a handful of occurences where AS is essentially dead in the water, with no actions firing and the Scheduled Actions list table is completely empty, even though historical actions should be visible as well as the current pending action.

The solution has been to simply delete the AS tables in the DB, and reload the `Scheduled Actions` page to trigger their re-creation.

Is this familiar/common?

This issue keeps rearing its head from time to time, and I'm having to investigate a workaround in code to prevent it from happening, by working out if the sync has stalled, deleting the tables if so, followed by a call to `register_tables` to re-create. 

Naturally, I'm keen to see if this is an actual bug in AS that could be patched, or if it is a broader issue involving the DB/server. 

I suspect that this could be explained away by a MySQL issue on the server preventing the AS tables from being accessed, but I don't have any evidence yet to support this conclusion.

Any insight very welcome!

**Comment by barryhughes** [comment]
Hi @davedoesthings,

That's an interesting scenario. I'll start by saying this is not at all common, to the best of my knowledge.

Action Scheduler does delete actions as part of a clean-up process [(see here)](https://github.com/woocommerce/action-scheduler/blob/3.2.0/classes/ActionScheduler_QueueCleaner.php#L32-L72) but there are fairly tight constraints around that: for instance, by default, only `complete` and `cancelled` actions are targeted, and only if they have been dormant for 1 month or more. I'm guessing what you're experiencing is a more general issue than that?

> The solution has been to simply delete the AS tables in the DB, and reload the Scheduled Actions page to trigger their re-creation.

So to clarify, the `wp_actionscheduler_actions` table is completely empty at this point and unless you recreate it things don't return to normal? If so ... I do rather suspect the problem has its source outside of Action Scheduler itself.

* Do you have any custom code that influences the way Action Scheduler behaves (for instance, are you filtering via hooks such as `'action_scheduler_retention_period'`)?
* Do you have anything 'non-default' in place to process the queue? For example, have you configured the system to process the queue exclusively via WP CLI?
* When things stall and the `wp_actionscheduler_actions` table is unexpectedly empty, do you see any errors in the MySQL log (either after this point, or in the run up)? Or indeed any PHP errors that relate to Action Scheduler?

**Comment by davedoesthings** [comment]
hi @barryhughes thanks for the reply!

To the best of my recollection, every time this has happened, the database tables were populated as you would expect, including the `wp_actionscheduler_actions` table with a couple of entries, but it has been a few weeks since this last happened, and I don't have any screenshots/DB dumps to hand, so I can't be definitive with regards to that table.

The next time this happens, I will grab the evidence to confirm!

> Do you have any custom code that influences the way Action Scheduler behaves (for instance, are you filtering via hooks such as 'action_scheduler_retention_period')?

The only filtering of AS behaviour we have in the codebase is the following callback for the `action_scheduler_retention_period` filter.

```
/**
* Change Action Scheduler default purge to 1 day.
 */
public function action_scheduler_purge() {
    return 86400;
}
```

> Do you have anything 'non-default' in place to process the queue? For example, have you configured the system to process the queue exclusively via WP CLI?

Nothing, very much a straight-forward implementation, nothing touching WP CLI etc. Once a sync is queued and scheduled, everything is triggered via cron.

> When things stall and the wp_actionscheduler_actions table is unexpectedly empty, do you see any errors in the MySQL log (either after this point, or in the run up)? Or indeed any PHP errors that relate to Action Scheduler?

The site runs on WPEngine so DB logs are something we need to ask for, which I will be doing next time this happens now that we have the time to investigate this issue. As for PHP, I've only ever really seen this:

```
Uncaught RuntimeException: Error saving action: Error saving action: Database error. in /nas/content/live/REDACTED/wp-content/mu-plugins/REDACTED/libraries/action-scheduler/classes/migration/ActionScheduler_DBStoreMigrator.php:44\nStack trace:\n#0 /nas/content/live/REDACTED/wp-content/mu-plugins/REDACTED/libraries/action-scheduler/classes/data-stores/ActionScheduler_HybridStore.php(242): ActionScheduler_DBStoreMigrator->save_action(Object(ActionScheduler_Action), NULL)\n#1 /nas/content/live/REDACTED/wp-content/mu-plugins/REDACTED/libraries/action-scheduler/classes/ActionScheduler_ActionFactory.php(177): ActionScheduler_HybridStore->save_action(Object(ActionScheduler_Action))\n#2 /nas/content/live/REDACTED/wp-content/mu-plugins/REDACTED/libraries/action-scheduler/classes/ActionScheduler_ActionFactory.php(84): ActionScheduler_ActionFactory->store(Object(ActionScheduler_Action))\n#3 /nas/content/live/REDACTED/wp-content/mu-plugins/REDACTED/libraries/action-scheduler/f in /nas/content/live/REDACTED/wp-content/mu-plugins/REDACTED/libraries/action-scheduler/classes/migration/ActionScheduler_DBStoreMigrator.php on line 44 
````

This leads me to suspect MySQL issues could be at play rather than AS being at fault.

**Comment by barryhughes** [comment]
Thanks for this info—agreed, I think we need more detail on the MySQL side. If it is possible to grab that info next time this occurs, that could be helpful. Also:

> including the wp_actionscheduler_actions table with a couple of entries

It could also be interesting to see a (suitably redacted) snapshot of some kind, assuming it is only a few rows. I'd be interested for instance in seeing the values of the `scheduled_date`, `status` and `claim` columns for the rows that do still exist (possibly you could query for those and omit the `hook` and `args` columns, to avoid sharing anything sensitive).

**Comment by barryhughes** [comment]
Closing: this has been inactive for a while and we don't have enough information as yet to identify a concrete bug. However, you can of course create a fresh issue at any time (and link back to this one if helpful).
