### ISSUE TITLE
This happens when wanting to delete a site: Fatal error: Uncaught RuntimeException: 

### ISSUE THREAD

**Issue by hidalgutzu** [woocommerce/action-scheduler#720]
WORDPRESS/WOOCOMMERCE MULTISITE

HELP !!... This happens when wanting to delete a site:

Fatal error: Uncaught RuntimeException: Error al guardar la acción: Table 'bkitmxmy_873hfuwie.ajz5makw_2_actionscheduler_actions' doesn't exist in /home/bkitmxmy/public_html/libs/plugins/woocommerce/packages/action-scheduler/classes/data-stores/ActionScheduler_DBStore.php:75 Stack trace: #0 /home/bkitmxmy/public_html/libs/plugins/woocommerce/packages/action-scheduler/classes/ActionScheduler_ActionFactory.php(177): ActionScheduler_DBStore->save_action(Object(ActionScheduler_Action)) #1 /home/bkitmxmy/public_html/libs/plugins/woocommerce/packages/action-scheduler/classes/ActionScheduler_ActionFactory.php(84): ActionScheduler_ActionFactory->store(Object(ActionScheduler_Action)) #2 /home/bkitmxmy/public_html/libs/plugins/woocommerce/packages/action-scheduler/functions.php(36): ActionScheduler_ActionFactory->single('wc-admin_delete...', Array, 1624057487, 'wc-admin-data') #3 /home/bkitmxmy/public_html/libs/plugins/woocommerce/includes/queue/class-wc-action-queue.php(44): as_schedule_single_action(1624057487, 'wc-admin_delete. in /home/bkitmxmy/public_html/libs/plugins/woocommerce/packages/action-scheduler/classes/data-stores/ActionScheduler_DBStore.php on line 75

**Comment by barryhughes** [comment]
Hi @hidalgutzu,

This sounds like it might be the same problem as reported in #699 _("Deleting subsite on multisite triggers table doesn't exist error")_ which may be solved by [WC Admin PR #7214](https://github.com/woocommerce/woocommerce-admin/pull/7214).

Since a solution is in the works I'll go ahead and close this issue, but let me know if you disagree.
