### ISSUE TITLE
Call to undefined function as_next_scheduled_action

### ISSUE THREAD

**Issue by olegabr** [woocommerce/action-scheduler#724]
When https://wordpress.org/plugins/ether-and-erc20-tokens-woocommerce-payment-gateway/ plugin is activated, product edit page crashes with error:

```
2021-06-25T04:47:09+00:00 CRITICAL Uncaught Error: Call to undefined function as_next_scheduled_action() in /site/wp-content/plugins/woocommerce/includes/queue/class-wc-action-queue.php:127
Stack trace:
#0 /site/wp-content/plugins/woocommerce/includes/admin/marketplace-suggestions/class-wc-marketplace-suggestions.php(200): WC_Action_Queue->get_next('woocommerce_upd...')
#1 /site/wp-content/plugins/woocommerce/includes/admin/class-wc-admin-assets.php(468): WC_Marketplace_Suggestions::get_suggestions_api_data()
#2 /site/wp-includes/class-wp-hook.php(292): WC_Admin_Assets->admin_scripts('post.php')
#3 /site/wp-includes/class-wp-hook.php(316): WP_Hook->apply_filters(NULL, Array)
#4 /site/wp-includes/plugin.php(484): WP_Hook->do_action(Array)
#5 /site/wp-admin/admin-header.php(102): do_action('admin_enqueue_s...', 'post.php')
#6 in /site/wp-content/plugins/woocommerce/includes/queue/class-wc-action-queue.php on line 127
```

The action scheduler is installed with a composer. Both 3.2.0 and 3.1.6 versions tested with same result.

The scheduler activation is done in the main plugin file with code:

```
        // Add autoloaders, and load up the plugin.
        require_once( dirname( __FILE__ ) . '/vendor/autoload.php' );
        require_once( dirname( __FILE__ ) . '/autoload.php' );

        require_once dirname( __FILE__ ) . '/vendor/woocommerce/action-scheduler/action-scheduler.php';

```

This code worked about a month ago.
[ether-and-erc20-tokens-woocommerce-payment-gateway-free.4.8.5 (3).zip](https://github.com/woocommerce/action-scheduler/files/6713859/ether-and-erc20-tokens-woocommerce-payment-gateway-free.4.8.5.3.zip)

**Comment by barryhughes** [comment]
@olegabr—I'm not immediately able to replicate this problem. 

Can you provide a set of steps to replicate, starting with a fresh WordPress installationw where WooCommerce and the other plugin are both activated (and, please clarify what you mean by 'plugin edit page'). 

Thanks!

**Comment by olegabr** [comment]
@barryhughes Thank you for a quick response!
Sorry for a mistake, the WC product edit page crashes. Fixed it in an original message also.

**Comment by barryhughes** [comment]
Thanks for clarifying, I was able to replicate.

> The scheduler activation is done in the main plugin file with code

So it looks to me like this happens pretty deep in a quite complex set of nested if/else structures, but I notice if the `require_once(...)` statement used to load Action Scheduler is moved to the top of the file (ie, immediately below the plugin docblock) then the problem seems to be resolved.

Are you the plugin author and would that be a viable change for you to make? Or, can you reach out to the plugin author and propose this?

**Comment by olegabr** [comment]
Many thanks @barryhughes!
Yes, I'm the plugin author. I'll apply this fix ASAP.
