### ISSUE TITLE
Admin panel not available

### ISSUE THREAD

**Issue by noplanman** [woocommerce/action-scheduler#728]
After installing the plugin and adding a few scheduled actions, I can't see the "Tools -> Action Scheduler" menu.

Do I need to enable it specifically somewhere?

**Comment by noplanman** [comment]
If I go directly to the page, it does load. There's just no menu item added 😕 

`/wp-admin/tools.php?page=action-scheduler` works 👍

**Comment by noplanman** [comment]
Culprit was WP Mail SMTP plugin. After disabling it the menu item appears.

Closing off here as it seems to be external.

**Comment by fidoboy** [comment]
WooCommerce also does the same. There is any way to restore it the same than WP Mail 

`add_filter("wp_mail_smtp_tasks_admin_hide_as_menu","__return_false");`

thanks,
