### ISSUE TITLE
Scheduled actions don't always restart after a migration

### ISSUE THREAD

**Issue by jonathanstegall** [woocommerce/action-scheduler#734]
Recently I've been working on launching an upgrade of [a plugin](https://github.com/MinnPost/object-sync-for-salesforce) that uses ActionScheduler. We've been running version 2.2.5 and are upgrading to version 3.2.1 and I've run it several times in local environments, and one time (so far) on a VIP Go staging environment.

What I've noticed is that sometimes the scheduled actions start as though nothing has happened after the migration is done, but other times they don't, and I find that I have to run `as_schedule_recurring_action` to get them to start up again.

I'm curious if this is something that I should build into our plugin. That is, when a user upgrades to this version of our plugin, it just runs that action for the schedules that need to run.

I'm thinking I would do this similarly to the way I check the database schema and other things that depend on plugin version. My question is if there's any risk in doing this, or if there's a way I should check to see whether it's necessary in a certain situation, especially since this doesn't seem to happen to me every time I run the upgrade process.

**Comment by jonathanstegall** [comment]
I'm realizing that my above idea wouldn't work because of course the migration wouldn't be done, so it wouldn't help. Is there an action I could hook onto that runs when the migration is finished, in which I could do the same thing?

**Comment by jonathanstegall** [comment]
This seems to work. It might be specific to my setup, where users configure how often they want their task to run. But it seems to work without any issue, as far as I can tell. I basically just update the option value and then revert it to what it was, and I've already got methods that run `as_schedule_recurring_action` whenever the option values change.

```php
add_action( 'action_scheduler/migration_complete', array( $this, 'resave_action_schedules' ) );
/**
    * When it finishes its migration, resave the scheduled tasks for ActionScheduler.
    */
public function resave_action_schedules() {
    // for each schedulable action, go ahead and resave it.
    $schedules_updated  = array();
    $schedules_restored = array();
    foreach ( $this->schedulable_classes as $key => $value ) {
        // make sure it has an initializer property; this is used on recurring tasks.
        if ( isset( $value['initializer'] ) ) {
            // toggle the schedule number setting.
            $schedule_option_name  = $this->option_prefix . $key . '_schedule_number';
            $previous_option_value = get_option( $schedule_option_name, 0 );
            $previous_option_value = filter_var( $previous_option_value, FILTER_SANITIZE_NUMBER_INT );
            $new_option_value      = $previous_option_value + 1;
            $schedule_updated      = update_option( $schedule_option_name, $new_option_value );
            if ( true === $schedule_updated ) {
                $schedules_updated[] = $key;
                $schedule_restored   = update_option( $schedule_option_name, $previous_option_value );
                if ( true === $schedule_restored ) {
                    $schedules_restored[] = $key;
                }
            }
        }
    }

    // create log entries below...
}
```

**Comment by barryhughes** [comment]
Hi @jonathanstegall,

> What I've noticed is that sometimes the scheduled actions start as though nothing has happened after the migration is done, but other times they don't, and I find that I have to run as_schedule_recurring_action to get them to start up again.

That's an interesting problem. You noted that sometimes it works as expected...is there anything outside of Action Scheduler that might be a contributing factor in the environments where it *doesn't* work?

**Comment by jonathanstegall** [comment]
@barryhughes I haven't been able to identify anything that unifies when it doesn't work. It has worked on some local tests, and not worked on some local tests. I only did one VIP Go staging test before adding the resave above, and it didn't work there.

It may be something odd with the way our plugin saves the recurring tasks, but I can't figure out what it would be.

**Comment by rrennick** [comment]
> I only did one VIP Go staging test before adding the resave above, and it didn't work there.

WP Cron is disabled in VIP Go. The async runner requires that the PHP backend is able to find the site through HTTP (DNS or hosts file). If both queue runners are disabled then actions won't run.

**Comment by jonathanstegall** [comment]
@rrennick that is helpful to know. What I learned was that if I resave them, it works in all environments including VIP Go, so that is what I built into the plugin using the hook I mentioned above. Unless there's a problem with that, I'd be fine with closing this issue. But it does make me wonder about how to account for that, either by documenting that folks should run a hook like this (if that's accurate) or by running some kind of event upon migration completion. But I realize there might not be that many folks left on the old version like we were, so maybe it's not significant. My main hope is that I didn't cause any problems by including that as a workaround.

**Comment by rrennick** [comment]
> What I learned was that if I resave them, it works in all environments including VIP Go, so that is what I built into the plugin using the hook I mentioned above.

Your code snippet isn't resaving scheduled actions. It looks like it's a setting related to something in your code. If the setting is related to action ID then your issue is probably related to the fact that migrated actions are assigned new IDs which are always higher than the existing ones.

**Comment by jonathanstegall** [comment]
@rrennick yeah, if the detail is helpful here, this is how my code works:

1. The migration completes, and the option values for scheduling get updated.
2. I have hooks that run for each schedulable action when those specific option values get updated.

This is the code that runs next:

```php
function set_action_schedule( $schedule_name, $action_group_name ) {

    // cancel previous task because now the frequency has changed.
    $this->queue->cancel(
        $this->schedulable_classes[ $schedule_name ]['initializer'],
        array(),
        $action_group_name
    );

    // create new recurring task for ActionScheduler to check for data to pull from Salesforce.
    $this->queue->schedule_recurring(
        time(), // plugin seems to expect UTC.
        $this->queue->get_frequency( $schedule_name, 'seconds' ),
        $this->schedulable_classes[ $schedule_name ]['initializer'],
        array(),
        $action_group_name
    );
}
```

Then, `$queue->schedule_recurring` is like this:

```php
/**
    * Schedule a recurring action
    *
    * @param int    $timestamp When the first instance of the job will run.
    * @param int    $interval_in_seconds How long to wait between runs.
    * @param string $hook The hook to trigger.
    * @param array  $args Arguments to pass when the hook triggers.
    * @param string $group The group to assign this job to.
    * @return string The action ID.
    */
public function schedule_recurring( $timestamp, $interval_in_seconds, $hook, $args = array(), $group = '' ) {
    return as_schedule_recurring_action( $timestamp, $interval_in_seconds, $hook, $args, $group );
}
```

And `as_schedule_recurring_action` is ultimately the ActionScheduler method that gets run, for each schedule, when migration is finished.

As far as I can tell, this works without issue, at least in our case. The events start running again as I would expect after the migration has finished.

**Comment by rrennick** [comment]
> if the detail is helpful here, this is how my code works:

I haven't seen anyone having to do that in the ~18 months since 3.0.0 was released so I'm not sure what would be the cause.

**Comment by jonathanstegall** [comment]
It's probably a thing I did wrong when I initially built our plugin, as we had a different queue system and were migrating to ActionScheduler in a bit of a rush. What I've done seems to work fine, even if it's not ideal. I'm fine with closing this, unless you think I've set up a future problem for myself.
