### ISSUE TITLE
Action Scheduler Not Auto Deleting Completed Tasks

### ISSUE THREAD

**Issue by MysticMedusa** [woocommerce/action-scheduler#735]
Hi - a former dev installed this on my site and it works perfectly with several plug-ins but it does not auto-complete completed tasks! So there are 50,000 of them in the database. I have Wp Optimize Database but it doesn't have a setting for this...do you have any suggestions for how I can remove them, apart from manually? I'd also like to set it up to auto-remove completed tasks in the future - I am the site owner, not a dev, in case it is not obvious lol. Thanks!

**Comment by barryhughes** [comment]
Hi @MysticMedusa,

> Hi - a former dev installed this on my site and it works perfectly with several plug-ins but it does not auto-complete completed tasks! 

I'm just a little unsure what you mean. If it's running perfectly I assume the actions are indeed being processed (and, when that happens and assuming no obvious failures, the status immediately updates to _complete)_ but on the other hand it sounds like that isn't what you are experiencing.

Can you give some examples/screenshots of what you're seeing to help us understand?

> I'd also like to set it up to auto-remove completed tasks in the future

This should already be happening, with complete and cancelled actions being deleted after one month. So long as the queue is being processed as expected, generally this is also taken care of. Is it possible the outstanding issues are still within that one month period?

**Comment by MysticMedusa** [comment]
Hi Barry,

 
thank you - sorry for being unclear. I just took a closer look and it appears the problem is that Woo Commerce has now added a crazy amount of admin actions.

 
I'm so sorry to have bothered you with a dumb question like this!

 
best, Jean

-----Original message-----

**Comment by barryhughes** [comment]
No problem, never hurts to discuss these things and confirm what's happening. Sometimes an unexpected flood of scheduled actions will happen and introduce delays—but we are iterating on some ideas for future releases to help with at least some of those situations.

Will close this issue, though, since it sounds like right now Action Scheduler itself is behaving as expected.

**Comment by MysticMedusa** [comment]
Thank you!

-----Original message-----
