### ISSUE TITLE
[WC5.5] After updating, database error on duplicate index 'claim_id_status_scheduled_date_gmt in table wp_actionscheduler_actions 

### ISSUE THREAD

**Issue by Danielspain22** [woocommerce/action-scheduler#737]
**Prerequisites (mark completed items with an [x]):**
- [ X] I have have carried out troubleshooting steps and I believe I have found a bug.
- [ X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
After updating to WC 5.5 from 5.4.2, a database error is logged caused by an ALTER TABLE sentence

**Expected behavior**
No error should appear

**Actual behavior**
Today I upgraded a site to WC 5.5 and everything works fine (payments are processed ok, etc.). But when I checked the logs I found this error at the exact time I upgraded:
[13-Jul-2021 12:14:29 UTC] Error Duplicate key name 'claim_id_status_scheduled_date_gmt' WordPress database error ALTER TABLE wp_actionscheduler_actions ADD KEY `claim_id_status_scheduled_date_gmt` (`claim_id`,`status`,`scheduled_date_gmt`) realizada por require('wp-blog-header.php'), require_once('wp-load.php'), require_once('wp-config.php'), require_once('wp-settings.php'), do_action('init'), WP_Hook->do_action, WP_Hook->apply_filters, ActionScheduler_DBStore->init, ActionScheduler_Abstract_Schema->register_tables, ActionScheduler_Abstract_Schema->update_table, dbDelta

I really don't know what it means...an attempt was made to create an index that already existed?
I paste here below the structure of the table **wp_actionscheduler_actions** and corresponding indexes in case it serves to diagnose what may have happened to me.
Could I run some SQL statement to check that there are no problems? No errors appeared after the upgrade,and payments are updated via action scheduler actions, but maybe you recommend me to run some check through sql?

**Screenshots**
![wp_actionscheduler_actions-structure](https://user-images.githubusercontent.com/61893634/125464277-c7546380-14d6-479f-b2b1-921189fa0552.PNG)
![INDEXESwp_actionscheduler_actions](https://user-images.githubusercontent.com/61893634/125464397-b1abda32-364f-4664-a34a-ef4d164e699a.PNG)

**WordPress Environment**
WP 5.7.2
PHP 7.3
Wordfence Plugin
WP Mail SMTP
WP Activity Log

Database check from Woocommerce tools says it's ok and every other check it's ok.
No other error or problem

Thanks in advance!

**Comment by barryhughes** [comment]
@Danielspin22—thanks for reporting this.

We can't seem to replicate, but it's just possible some sort of race condition was at play (especially as it looks like at least two of your plugins—WooCommerce being one, WP Mail SMTP being the other—both include the library).

The screenshot you shared suggests the index was successfully added: am I right to think this was a 'one off', or are you experiencing ongoing problems?

**Comment by Danielspain22** [comment]
I have not noticed any problems so far. Do you think the index/table is ok in my screenshot? Thanks in advance

**Comment by barryhughes** [comment]
It looks OK to me.

**Comment by barryhughes** [comment]
Closing (cannot replicate, so far there is only one report). If it occurs again, please feel free to create a new issue referencing this one.
