### ISSUE TITLE
E_ERROR woocommerce

### ISSUE THREAD

**Issue by Hugo120884** [woocommerce/action-scheduler#738]
Hola a todos, agradezco su ayuda para saber a qué se debe el siguiente problema: 

Se ha producido un error del tipo E_ERROR en la línea 671 del archivo /var/www/vhosts/euroopticas.net/httpdocs/aros/wp-content/plugins/woocommerce/includes/class-wc-product-variable.php. Mensaje de error: Maximum execution time of 60 seconds exceeded

gracias por su apoyo

**Comment by barryhughes** [comment]
Hi!

> An error of type E_ERROR occurred on line 671 of the file /.../woocommerce/includes/class-wc-product-variable.php. Err Msg: Maximum execution time of 60 seconds exceeded

This is the Action Scheduler issue tracker, but it would seem like the problem you are describing is better suited to the [WooCommerce issue tracker](https://github.com/woocommerce/woocommerce/issues).

If you have performed the [usual troubleshooting steps](https://docs.woocommerce.com/document/woocommerce-self-service-guide/) and are certain this is a bug with that plugin, [please post over there](https://github.com/woocommerce/woocommerce/issues/new?assignees=&labels=&template=4-Bug-report.md&title=) and supply as much information as you can, including steps to replicate.

Alternatively, you may wish to post in the [community forums](https://wordpress.org/support/plugin/woocommerce/) as an initial step with which to gather advice.
