### ISSUE TITLE
Message stuck In Progress

### ISSUE THREAD

**Issue by MarkSmithPLT** [woocommerce/action-scheduler#739]
Hello,

I have a message in the queue which does not get processed. It seems to happen when it is the last message in the group which has previously failed. I have code which handles timeouts and exceptions which re-queues these messages.

```
class Background_Process_Thumbnail {
    public static function retryTaskAfterTimeout(string $action_id, $timeout): void
    {
        $action = ActionScheduler::store()->fetch_action($action_id);
        if (strpos($action->get_hook(), 'process_image_task') !== false) {
            as_schedule_single_action(
                '+1 second',
                $action->get_hook(),
                array_merge(
                    $action->get_args(),
                    ['error' => 'Timeout of ' . $timeout . ' exceeded']
                ),
                $action->get_group()
            );
            self::log($action->get_args(), 'Retry due to timeout of ' . $timeout . ' exceeded');
        }
    }

    public static function retryTaskAfterException(string $action_id, Throwable $exception): void
    {
        $action = ActionScheduler::store()->fetch_action($action_id);
        if (strpos($action->get_hook(), 'process_image_task') !== false) {
            as_schedule_single_action(
                '+1 second',
                $action->get_hook(),
                array_merge(
                    $action->get_args(),
                    ['exception' => $exception->getMessage() . ' on line ' . __LINE__]
                ),
                $action->get_group()
            );
            self::log($action->get_args(), 'Retry due to exception ' . $exception->getMessage());
        }
    }
}
add_action('action_scheduler_failed_execution', ['Background_Process_Thumbnail', 'retryTaskAfterException'], 10, 2);
add_action('action_scheduler_failed_action', ['Background_Process_Thumbnail', 'retryTaskAfterTimeout'], 10, 2);

```
The results screenshot can be seen here: [https://ibb.co/GppTYhg](https://ibb.co/GppTYhg)

**Comment by barryhughes** [comment]
Hi @MarkSmithPLT,

I don't think there's enough information to know what's going wrong here. 

Looking at the screenshot you shared, I would expect the queue cleaner to fire the `action_scheduler_failed_action` action in relation to the timed-out task. Reasons this might not happen could include:

* If you have multiple timed out actions, and they exceed the queue cleaner batch size (by default, 20) then some may be temporarily 'left behind'.
* Or, if the `action_scheduler_timeout_period` cutoff value has been modified, that may be stopping the queue cleaner from picking this one up.
* Or, something may be modifying the query used by the queue cleaner.

That said, in a local test where I use your code and generate three in-progress (but timed out) actions, all in the same group, they are all successfully picked up by the queue cleaner and your code schedules three replacements as expected. None are left behind.

**Comment by barryhughes** [comment]
💡 As a sidenote, some work has been started with the goal of officially [adding retry support](https://github.com/woocommerce/action-scheduler/pull/612) to the library.

**Comment by barryhughes** [comment]
Closing.

Note that besides the work I linked to above (retry support), we also have another issue relating to [error trapping](https://github.com/woocommerce/action-scheduler/issues/391#issuecomment-904748934) which _may_ relate to the problem you noted.
