### ISSUE TITLE
Scheduled Actions remains pending (not run automatically) in multisite

### ISSUE THREAD

**Issue by bilalilyas90** [woocommerce/action-scheduler#740]
Hi
I am running a multisite website with 6 sub sites and I am having a problem in one of my sub site ..
No scheduled actions get fired for that sub site but it works on other subdomains .. I have tested cron job and its also working but I am really stuck with this issue . I have tried all possible ways which I knew but nothing helped ..
Please guide me what should I do ...
I am running WooCommerce 5.0.1 and action scheduler 3.1.6

**Comment by barryhughes** [comment]
Hi @bilalilyas90,

I'd like to highlight this entry from the [FAQs](https://actionscheduler.org/faq/) first of all:

> **How does Action Scheduler work on WordPress Multisite?**
> 
> Action Scheduler is designed to manage the scheduled actions on a single site. It has no special handling for running queues across multiple sites in a multisite network. That said, because its storage and Queue Runner are completely swappable, it would be possible to write multisite handling classes to use with it.

So, you may be hitting up against existing limitations here. That said, it sounds like it is mostly working in your case, except for one sub-site:

* Does anything stand out as being different about this one sub-site? Does it have a different parent domain, for instance, or does it have a different mix of plugins+theme than the others?
* Have you had an opportunity to try basic conflict testing, by deactivating other components to see if they are impacting?
* How are you including Action Scheduler—is it bundled with a plugin or are you using it as a standalone plugin (and, is it network activated or activated on individual sites)?
* How are you managing cron?

Something you may wish to try is adding WP CLI commands to your crontab, to trigger the Action Scheduler queue runner for this _specific_ subsite:

`wp --url=<URL_OF_SUBSITE> action-scheduler run`

**Comment by bilalilyas90** [comment]
> Hi @bilalilyas90,
> 
> I'd like to highlight this entry from the [FAQs](https://actionscheduler.org/faq/) first of all:
> 
> > **How does Action Scheduler work on WordPress Multisite?**
> > Action Scheduler is designed to manage the scheduled actions on a single site. It has no special handling for running queues across multiple sites in a multisite network. That said, because its storage and Queue Runner are completely swappable, it would be possible to write multisite handling classes to use with it.
> 
> So, you may be hitting up against existing limitations here. That said, it sounds like it is mostly working in your case, except for one sub-site:
> 
> * Does anything stand out as being different about this one sub-site? Does it have a different parent domain, for instance, or does it have a different mix of plugins+theme than the others?
> * Have you had an opportunity to try basic conflict testing, by deactivating other components to see if they are impacting?
> * How are you including Action Scheduler—is it bundled with a plugin or are you using it as a standalone plugin (and, is it network activated or activated on individual sites)?
> * How are you managing cron?
> 
> Something you may wish to try is adding WP CLI commands to your crontab, to trigger the Action Scheduler queue runner for this _specific_ subsite:
> 
> `wp --url=<URL_OF_SUBSITE> action-scheduler run`

Hi @barryhughes 
Thank you for your reply ...

- All sub sites are same and have same parent domain
- yes I deactivated all plugins and also deleted the action scheduler tables with options in wp_subsite_options and then activated plugins one by one and it creates tables too successfully for action schedulers in database but still it don't fires automatically any action scheduled at any time.
- Action scheduler is used from WooCommerce plugin and also I think added in WooCommerce Subscribers plugin
- for now I have set ALTERNATE_CRON in wp-config.php

I also run the wpcli command also and got this result : 
wp --url=https://ro.mysite.com action-scheduler run --allow-root
   0 batches executed.
   Success: 0 scheduled tasks completed.

And still action scheduler is working fine for all other subdomains except this one . One thing I noticed that It gives error in dashboard with unknown subscription id which doesn't exist for this subdomain instead is of main site subscription id after comparing the ids from database. Following is the error :

  <img width="1265" alt="Screenshot 2021-08-12 at 7 03 34 PM" src="https://user-images.githubusercontent.com/11154901/129210825-2f0da98e-ce05-413c-877b-5c0bfe82f281.png">

and when loon into the logs it say this error "Subscription doesn't exist in scheduled action" and this is because this subscription ID exists in main site not in this sub-site 

  <img width="1260" alt="Screenshot 2021-08-12 at 7 07 15 PM" src="https://user-images.githubusercontent.com/11154901/129211403-bdbaaa80-ebdb-4e2b-853a-c2cd871038e9.png">


in following screenshot you can see the pending actions and the scheduled date is 42 minutes ago and doesn't run automatically.

  ![Screenshot 2021-08-12 at 7 01 54 PM](https://user-images.githubusercontent.com/11154901/129210580-e7b528eb-1e30-430f-9350-6dca5ff4e6bf.png)

Any steps or help would be really appreciated as I have been stuck here for couple of days

**Comment by bilalilyas90** [comment]
I think I have found that there was some issue in my site setup which after solving I got the scheduler workingg fine again...
Thank you for your support :)
