### ISSUE TITLE
Max execution time of 0 is longer than 30

### ISSUE THREAD

**Issue by EdwardBock** [woocommerce/action-scheduler#745]
Hi there,

we use the plugin Mailchimp for WooCommerce which uses your action-scheduler. We run wordpress schedules with cli and a max_execution_time of 0 which means infinit. Problem is that your ActionScheduler_Compatibility.php class raises the execution time to 30 which is not more that 0. You should check for zero or larger than $limit as return conditions. Could that be?

https://github.com/woocommerce/action-scheduler/blob/master/classes/ActionScheduler_Compatibility.php#L89

**Comment by barryhughes** [comment]
Thanks for the report, @EdwardBock. If you are happy to submit a PR for this that would be great—though if not we'll do our best to address this from our side.

**Comment by ovidiul** [comment]
The 30 seconds time limit is probably taken from [here](https://github.com/woocommerce/action-scheduler/blob/master/classes/abstracts/ActionScheduler_Abstract_QueueRunner.php#L130), so you might actually need to modify that filter at the Action Scheduler level as:

```
// define the action_scheduler_maximum_execution_time callback 
function custom_action_scheduler_maximum_execution_time( $time_limit ){ 
   //custom code here
    $time_limit = 0;

    return $time_limit
} 

//add the action 
add_filter('action_scheduler_maximum_execution_time', 'custom_action_scheduler_maximum_execution_time', 10, 1);
```

so on that indicated line, the condition will check if 30 < 0, which will return false, and continue with the setting the upper time limit to 30.

**Comment by barryhughes** [comment]
📕  Closing as solved: https://github.com/woocommerce/action-scheduler/pull/755.

:bulb: Further related issue here: https://github.com/woocommerce/action-scheduler/issues/767
