### ISSUE TITLE
ActionScheduler_Compatibility::raise_time_limit imposes a limit

### ISSUE THREAD

**Issue by dgoring** [woocommerce/action-scheduler#754]
if max_execution_time is unlimited i.e. zero 
this function actually creates a limit

Can it please check for limit equals zero
```php
	/**
	 * Attempts to raise the PHP timeout for time intensive processes.
	 *
	 * Only allows raising the existing limit and prevents lowering it. Wrapper for wc_set_time_limit(), when available.
	 *
	 * @param int The time limit in seconds.
	 */
	public static function raise_time_limit( $limit = 0 ) {
		if ( (int)ini_get( 'max_execution_time' ) === 0 || ($limit !== 0 && $limit < ini_get( 'max_execution_time' ) )) {
			return;
		}

```

**Comment by barryhughes** [comment]
Related: https://github.com/woocommerce/action-scheduler/issues/745

**Comment by barryhughes** [comment]
Agreed.

If `max_execution_time` is zero ('unlimited') and if we then do something like `ActionScheduler_Compatibility::raise_time_limit( 10 )`, then we should **not** make any changes to `max_execution_time`.
