### ISSUE TITLE
Method to check if the current request will run an action

### ISSUE THREAD

**Issue by arnaudbroes** [woocommerce/action-scheduler#756]
We'd love to have a way to check if the current request is going to run an action. The only way I can think of to do this is by querying the actions table and check what's scheduled but that seems tricky since Action Scheduler takes a few conditions into account before it actually runs a job.

**Comment by barryhughes** [comment]
Hi @arnaudbroes,

There are several different ways in which a queue runner may be triggered:

* WP scheduled events (via a "WP Cron" async web request)
* WP scheduled events (triggered using WP CLI)
* Async web request (specific to Action Scheduler)
* WP CLI (directly)

I'm just a little unsure if you are trying to detect when you are 'inside' one of those requests, or if you are focused on detecting if (for example) an async web request to process the queue is about to be dispatched.

Could you perhaps give some more information about what you are trying to do? That might make it easier to provide guidance.

**Comment by arnaudbroes** [comment]
@barryhughes first of all, thank you for your response.

We basically want to run a cleanup routine after any of our actions have been processed. But we don't want to run that cleanup routine on every request to the site, so I basically am trying to figure out if there's a way to detect whether the request is going to process the queue. That way, I can register the cleanup routine on the `shutdown` hook for example and just run it once for that request only.

Does that make sense?

**Comment by barryhughes** [comment]
That makes sense. There are some challenges (mostly race conditions) to be aware of, though. 

In terms of doing cleanup, are you specifically trying to remove old actions? If so, it may be better to let Action Scheduler handle cleanup via its existing queue cleaner (which is configurable to a degree—so if for example you are finding that old actions are hanging around longer than you might like, you can probably tweak it accordingly).

Would that help?

**Comment by arnaudbroes** [comment]
Something like that. Can you define "old actions"? 

We're basically trying to clean up the records for our actions in the log table. We run a lot of actions and some users complain about the amount of records we're generating.

Right now we have an action (ironic 😉) that runs every week to clean up the table, but I was wondering whether we just can't do it after one of our actions has run. An easy way to do that would be to simply call the cleanup routine at the end of the action but I was wondering whether there was a smarter way to do it.

**Comment by barryhughes** [comment]
By default, "old actions" would mean those that have a status of either complete or cancelled, and that are older than 1 month (adjustable via the `action_scheduler_retention_period` filter).

If I'm understanding the situation correctly, though, it sounds like you specifically wish to target actions that belong to your own plugin/theme and so your existing approach (a recurring cleanup action) sounds like a perfectly valid approach.

> An easy way to do that would be to simply call the cleanup routine at the end of the action but I was wondering whether there was a smarter way to do it so that we don't have to call it in each action.

If you did want to explore this, you might look into the `action_scheduler_after_execute` action. It fires after an action has successfully been processed (there are other actions that fire if it failed) and the action object (through which you can inspect the hook—ie, to determine if it belongs to you) is available to callbacks.

**Comment by arnaudbroes** [comment]
@barryhughes I think that might be exactly what I am looking for. I will try that hook out. In the meanwhile I'll go ahead close the issue then since there's a way to achieve what I want.

Thank you so much for following up on this, I highly appreciate it!
