### ISSUE TITLE
Add parent plugin details to `Help` pulldown

### ISSUE THREAD

**Issue by barryhughes** [woocommerce/action-scheduler#772]
Following some (mostly internal) discussion around https://github.com/woocommerce/action-scheduler/issues/730 it was surfaced that it could be useful to add information about the plugin (or theme) responsible for loading Action Scheduler to the **Tools → Scheduled Actions** screen's **Help** tab.

Mock:

<img width="957" alt="modified-help-tab" src="https://user-images.githubusercontent.com/3594411/136425001-b5e80f8d-1fb9-4de4-a8ce-5d42c530b6f2.png">

This would be useful to assist with troubleshooting when:

* Multiple plugins/theme all include Action Scheduler.
* When an end-user does not know which of their components is including Action Scheduler, but needs assistance with it.

**Comment by crstauf** [comment]
@barryhughes see #271.

**Comment by barryhughes** [comment]
Recently submitted https://github.com/woocommerce/action-scheduler/pull/1218 reminded me of this issue. If it can successfully determine the active version (and, based on the description, it can) we could also use that as a foundation for *this* issue.

**Comment by crstauf** [comment]
Simple enough: all I did was use `dirname( __DIR__, $level )` to return the path to the root of Action Scheduler library.

**Comment by crstauf** [comment]
@barryhughes Are you interested in implementing the name of the theme or plugin from which Action Scheduler is being loaded (as in OP screenshot), or is the source path sufficient (what was merged)?

**Comment by barryhughes** [comment]
I think this is *sufficient,* but I also think if there is a reliable way to supplement that with the actual plugin name and version (assuming it is coming from a plugin), that would be a really nice addition.

**Comment by crstauf** [comment]
Understood. I had started working on that, so will open that up in a different branch and PR.

**Comment by barryhughes** [comment]
Excellent, thank you.
