### ISSUE TITLE
Pass an object as argument

### ISSUE THREAD

**Issue by astbarc** [woocommerce/action-scheduler#788]
Hi,

Is it possible to pass an object as an arg ?

I can do it in wp_schedule_single_event but I can't make it work with as_schedule_single_action

Example:

With wp-cron I can pass the $record object this way:

`wp_schedule_single_event( current_time( 'timestamp' ) + 120, 'my_action' , array($record) );`

But with action-scheduler I can't figure out how to do it. I've tried this way, but is not working:

`as_schedule_single_action(current_time( 'timestamp' ) + 120, 'my_action' , array('record'=> $record));`

I would appreciate your help

**Comment by barryhughes** [comment]
Hi @astbarc,

Arguments are JSON-encoded and so (with some exceptions, such as if you pass a simple `stdClass`) passing objects to scheduled actions won't work/will be problematic.

If you can, it would be better to pass the entity ID (and/or anything else you might need) to recreate your object when the callback fires, something like this:

```php
$record_id = $record->get_id();
as_enqueue_async_action( 'task_x', array( $record_id ) );
add_action( 'task_x', 'task_x_callback' );

function task_x_callback( $id ) {
    $record = new Record( $id );
    // ... do work ...
}
```

**Comment by astbarc** [comment]
Hi @barryhughes ,

May thanks for the explanation.

I think I have found a way to do it using following your suggestion.

**Comment by barryhughes** [comment]
Excellent!
