### ISSUE TITLE
Version conflict: undefined function as_has_scheduled_action

### ISSUE THREAD

**Issue by nhadsall** [woocommerce/action-scheduler#796]
Woo loads 3.4.0 and another plugin includes 3.1.6. In this case, I would assume 3.4.0 should load. However, when both included `as_has_scheduled_action` is not defined. When we disable only the include for 3.1.6, `as_has_scheduled_action` is found as expected. 

I'm not super well versed in the version loading, but both `action_scheduler_initialize_3_dot_1_dot_6` and `action_scheduler_initialize_3_dot_4_dot_0` are being called. However, it seems that the functions.php file from 3.4.0 must not be included or `as_has_scheduled_action` would be defined?

**Comment by barryhughes** [comment]
Unfortunately, I think you are experiencing the problem [described here](https://developer.woocommerce.com/2021/10/12/best-practices-for-deconflicting-different-versions-of-action-scheduler/).

In relation to [`as_has_scheduled_action()`](https://actionscheduler.org/api/#function-reference--as_has_scheduled_action) specifically, what you may wish to do (if you control the code in question) is write either a polyfill or a wrapper that tests for the existence of that function and falls back on [`as_next_scheduled_action()`](https://actionscheduler.org/api/#function-reference--as_next_scheduled_action) if the former is not available.

**Comment by barryhughes** [comment]
Closing this as I don't think there is more for us to do here, but if you disagree or have further questions just let me know.
