### ISSUE TITLE
$as_args only passing the first element of the array

### ISSUE THREAD

**Issue by btolle89** [woocommerce/action-scheduler#798]
I schedule an action using as_schedule_single_action and pass an array $as_args
I can see that the array made it into Action Scheduler in the UI within woo. (see attached)
![image](https://user-images.githubusercontent.com/29187982/152645298-f839d49f-15c3-471a-b48e-3048463866e3.png)

However, when the action runs, and the args do not seem to pass to the function properly. 
Only the first element of the array appears as $as_args

I have 
`add_action( "add_tag_and_user_callback" , "add_tag_and_user", 10, 1 ); `
and
```
function add_tag_and_user( $as_args ){

	error_log(print_r('add tag and user ran!',true));
	error_log(print_r($as_args,true));
}
```

but I can see in the error log, that the full array has not passed. it's only the first element
```
[05-Feb-2022 14:01:15 UTC] add tag and user ran!
[05-Feb-2022 14:01:15 UTC] 1938
```

what am I doing wrong?

**Comment by barryhughes** [comment]
Hi @btolle89,

The array represents a set of arguments for your callback (in other words, rather than supplying the array in its entirety, it is broken into individual elements and each acts as a single argument). So, if you do:

```php
as_enqueue_async_action( 'my_task', array( 'foo-foo', 'bar-bar' ) );
```

You would then do something like this, taking care to set the number of `$accepted_args` appropriately:

```php
add_action( 'my_task', 'my_callback', 10, 2 );

function my_callback( $foo, $bar ) {
    # $foo := (string) 'foo-foo'
    # $bar := (string) 'bar-bar'
}
```

Does that help?

**Comment by mischnu** [comment]
I’m having the same issue as @btolle89, only the first item of the array is passed as argument to the callback. The rest of the array seems to be omitted.

This is what my callback looks like:
```PHP
add_action( 'as_set_customer_status', 'set_customer_status' );
function set_customer_status( $customer_id, $status ) {
    wp_update_post( array(
        'ID'          =>  $customer_id,
        'post_status' =>  $status,
    ) );
}
```

Now when I schedule a single action like this:
```PHP
as_schedule_single_action( strtotime( '+1 min' ), 'as_set_customer_status', array( 128, 'trial-expired' ), 'set_customer_status' );
```
the task fails and throws a PHP fatal error:
> PHP Fatal error Uncaught ArgumentCountError: Too few arguments to function set_customer_status(), 1 passed in [...]/wp-includes/class-wp-hook.php on line 310 and exactly 2 expected in [...]/wp-content/plugins/my-plugin/includes/customer/customer-actions.php:79

@barryhughes, do I get something wrong or is there still a bug?

**Comment by mischnu** [comment]
🙈 Sorry, my bad – forgot to specify the number of arguments in my add_action call:
```
add_action( 'as_set_customer_status', 'set_customer_status', 10, 2 );
```
This will do the trick.

**Comment by barryhughes** [comment]
Glad you figured it out—though possibly this would be a good thing to add to a future 'Tips and Tricks' page on the docs site.

**Comment by EdithAllison** [comment]
I made the same rookie error. I followed the instructions https://actionscheduler.org/api/, maybe you could add a link to this issue page or include the explanation from @barryhughes which cleared up my array error. Thank you for the clear instructions!
