### ISSUE TITLE
Hook i set for action scheduler not running

### ISSUE THREAD

**Issue by RedAuthorium** [woocommerce/action-scheduler#800]
I make an action for action scheduler and its not running on my client website, 
the delay only 10 seconds, i try it on another live server and my local its work fine, what i notice from my other website and my client website, is my client using php 8.
the action just stuck on pending and the log says 
2022-02-14 04:32:18 +0000
action created

and nothing more
what am i missing ?

**Comment by barryhughes** [comment]
Hi @RedAuthorium,

Queue processing is triggered in one of two ways—via WordPress's own [Scheduled Events API ("WP Cron")](https://developer.wordpress.org/plugins/cron/scheduling-wp-cron-events/) and, additionally, via Action Scheduler's own mechanism (periodically spawning a queue runner at the end of admin requests, when needed). [More details here](https://actionscheduler.org/faq/#i-dont-want-to-use-wp-cron-does-action-scheduler-depend-on-wp-cron).

If the queue is not being processed, though, then _probably_ that also means other WP cron-based tasks are also failing to run. A plugin such as [WP Crontrol](https://wordpress.org/plugins/wp-crontrol/) could help you to see what's happening in this regard, and will also provide a convenient way to manually run things (look for the `action_scheduler_run_queue` event).

If it does indeed look like there are problems impacting WP Cron in general, you may wish to seek help from your webhost or, if you have direct access to the server command line, you could consider creating a manual crontab entry and trigger things that way. Should [WP CLI](https://wp-cli.org/) be installed you can take advantage of the following command:

```
wp action-scheduler run
```

There are other reasons things might be failing to run, but the above is probably worth looking at in the first instance. You may also wish to review the server error logs in case anything of note relating to Action Scheduler has been captured there.
